### ISSUE TITLE
"row.names" error after model run

### ISSUE THREAD

**Issue by atamkin** [brianstock/MixSIAR#100]
I just started a new model, but can't get it to run correctly.
The frustrating thing is that it's very similar models I've run successfully. 
Hoping the error message means something to someone. Wasn't able to find anything on it in past issues.

The files load fine, and the model seems to run fine, but when I process model output, after all the graphs are made, I get the following error message: 

> Error in `row.names<-.data.frame`(`*tmp*`, value = value) : 
>   invalid 'row.names' length

and the output processing stops - no diagnostics or anything.

When searching this site, I found row.names in the [load_discr_data.R file](https://github.com/brianstock/MixSIAR/blob/master/R/load_discr_data.R), line 19-21:

>   row.names(DISCR)<-DISCR[,1]     # store the row names of DISCR (sources)
>   DISCR <- as.matrix(DISCR[-1])   # remove source names column of DISCR
>   DISCR <- DISCR[order(rownames(DISCR)),]  # rearrange DISCR so sources are in alphabetical order

(Not sure why it's rownames in line 21, not row.names as in line 19?)
My suspicion is that something is wrong with my input files, some mismatch in dimension or something, but I have gone over them multiple times and can't see anything wrong - and I've used the discr and sources files successfully in other models.

My files:
[Model](https://github.com/brianstock/MixSIAR/files/966401/20160429_Ch2_out_MixSIAR_model.txt)
[Script, model, inputs](https://github.com/brianstock/MixSIAR/files/966413/tamkin.rownames.error.zip)

I'm running:

> platform       x86_64-w64-mingw32          
> arch           x86_64                      
> os             mingw32                     
> system         x86_64, mingw32             
> status                                     
> major          3                           
> minor          3.3                         
> year           2017                        
> month          03                          
> day            06                          
> svn rev        72310                       
> language       R                           
> version.string R version 3.3.3 (2017-03-06)
> nickname       Another Canoe  
> 
> RStudio Version 1.0.136
> MixSIAR version 3.1.7

**Comment by brianstock** [comment]
Definitely a bug in my code, no problem with your input files... sorry about that!  The error was unique to situations with 1 fixed effect + 1 random effect with some empty level combinations (i.e. fall mix data only in one outflow).  Thank you for posting your files and script, that made it easy for me to see what was going wrong and fix it.

Since this is a pretty minor change, I'm not going to push a new version to CRAN yet.  To get the fixed code, use `devtools` to install the latest version of MixSIAR from GitHub:
```
library(devtools)
install_github("brianstock/MixSIAR")
```

**Comment by atamkin** [comment]
Many thanks for the prompt reply and fix! Works fine now.
