### ISSUE TITLE
Access MCMC chains when 2 fixed effects OR 1 fixed + 1 random

### ISSUE THREAD

**Issue by brianstock** [brianstock/MixSIAR#101]
Problem 1: when I have 2 fixed effects OR 1 fixed + 1 random effect, users cannot access  `p.both` created in `output_JAGS.R`. 
Problem 2: for this case, posterior plots save over themselves, so only remain with the last level of `p.fac2`.

See also:
https://github.com/brianstock/MixSIAR/issues/100
https://github.com/brianstock/MixSIAR/issues/80

**Comment by brianstock** [comment]
Fixed now.

Data files and script: https://github.com/brianstock/MixSIAR/issues/100
With 1 fixed + 1 random effect, the proper proportions to use are created by combining the global intercept, the factor1 offset, and the factor2 offset:

1. `ilr.both[,f1,f2,src] = ilr.global[,src] + ilr.fac1[,f1,src] + ilr.fac2[,f2,src]`
2. Convert from ILR-space to proportion-space (messy)

Now the `output_JAGS` function returns `p.both`-- the MCMC chains for each factor-level combination. Now if you save the result of `output_JAGS`:
```
p.both <- output_JAGS(jags.1=RG.out,
            mix=data.mix, 
            source=data.source, 
            output_options=output_options)
```
This has dimensions = [n.draws, f1.levels, f2.levels, n.sources]. Check the order of the f1 levels, f2 levels, and sources (alphabetical) using:
```
data.mix$FAC[[1]]$labels
data.mix$FAC[[2]]$labels
data.source$source_names
```
So to get the proportion for Spring - Outflow_30 - SOM:
```
hist(p.both[,2,3,4])
```
Check that this matches the nicer looking posterior plot.

**Comment by atamkin** [comment]
Thanks for making this connection!
I finally got back to my model, but can't get the p.both to populate. It does appear in my list of variables:
![image](https://cloud.githubusercontent.com/assets/28202823/26006058/156e3d34-3709-11e7-80aa-c881f25d6ba0.png)
but is empty. :-/
I don't think I've changed anything about my code. I am running my chains at test length.

**Comment by brianstock** [comment]
Hmm, strange, it works for me.  Check:

1. You're using the latest GitHub version
```
library(devtools)
install_github("brianstock/MixSIAR")
```

2. See if there's any difference in your code and what I'm running (email me at b1stock@ucsd.edu, I'll send you the .R script)
