### ISSUE TITLE
Is it ok for consumer data points to fall outside the source convex hull?

### ISSUE THREAD

**Issue by brianstock** [brianstock/MixSIAR#109]
Question via email:

"One issue we're facing is aggregating prey groups so that the consumers fall within the convex hull. We've been trying to follow Phillips' best practices paper. So we realize that when mixing models are applied in a Bayesian context, the consumers don't strictly speaking have to be entirely within the convex hull (given some variance in prey tracers), but just how far outside of the hull can we get away with and still maintain some statistical rigor?"

**Comment by brianstock** [comment]
Your data look fine to me, I would have no qualms running a mixing model on them (assuming those have been already been adjusted by the TDF, what the model would 'see'). Two points you can give for this:
  1. source means and variances 'wiggle' a bit since they're fit in the model (how much depends on sample size - if you have few source data then the differences between fitted source means and source sample means can be greater than if you had a larger sample size)
  2. what really should be in the convex hull are the mix/consumer MEANS, not all of the individual points. See Eqn 3 in Moore and Semmens 2008:

![moore_semmens_eqn3](https://user-images.githubusercontent.com/5124211/30121671-2b2b47d2-92e1-11e7-81a7-25dac3d41df9.png)

You can also see this in the example dataset from that paper too - look at Fig 1b, has individual points outside the convex hull, but the important thing is that the consumer mean is inside:

![moore_semmens_fig1b](https://user-images.githubusercontent.com/5124211/30121685-35fff3a6-92e1-11e7-9eba-244aeefd80b5.png)

**Comment by ChrisHarrod** [comment]
Not sure if this paper is of any use?

Smith, J. A., D. Mazumder, I. M. Suthers, and M. D. Taylor. 2013. To fit or not to fit: evaluating stable isotope mixing models using simulated mixing polygons. Methods in Ecology and Evolution 4:612-618.

Cheers
Chris

**Comment by brianstock** [comment]
Hi Chris,

Thanks for adding that suggestion - yes, Smith et al. (2013) generally seems like a good approach. But note that it only takes my first point into account, not the second one. Bayesian mixing models (MixSIR, SIAR, etc.) all say that the consumer data points are normally distributed, with the mean a linear combination of the source means. So these models don't actually assume _individual_ consumer points lie in the convex hull (even after allowing for source means/variances to be fit), just the consumer _mean_. Using the Smith et al. (2013) method to exclude consumer points seems unwise to me.
