### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by Undergrad2017** [brianstock/MixSIAR#110]
I am using RStudio (not sure version number, latest version as of July 2017) on Windows and I have successfully downloaded and installed JAGS, but whenever I try to install the gWidgetsRGtk2, it gives me the following error:
Error: package ‘RGtk2’ required by ‘gWidgetsRGtk2’ could not be found
In addition: Warning message: package ‘gWidgetsRGtk2’ was built under R version 3.3.3

I have looked around online to try and find RGtk2, but the only can only find one paragraph assist (https://cran.r-project.org/web/packages/RGtk2/INSTALL) that sends me to a temporary website that's been around since 2008, and I'm still not sure which to download to find my missing RGtk2

I may just be missing something obvious, but any assistance would be greatly appreciated

**Comment by brianstock** [comment]
Hello,

Sorry you're having issues - the GTK+ installation is not an uncommon problem. Are you on PC, Mac, or Linux? Did you try the install instructions on the MIxSIAR main page/README?

If you're on PC, what happens when you run (you should be prompted to install GTK+):
```
install.packages("RGtk2")
library(RGtk2)
```

 If you're on Mac or Linux there are different install instructions - see main README page.

**Comment by Undergrad2017** [comment]
I get an error saying that RGtk2 is unavailable for this version of R. Is there a place I can download it, and if so, how would I go about doing so?

![capture](https://user-images.githubusercontent.com/31868428/30653567-4b7f49a2-9de0-11e7-946b-fd87338f5436.PNG)

**Comment by brianstock** [comment]
It's probably (hopefully) because you have an old version of R, not only a minor but a major update. Try updating to R 3.4.1 and try again.

**Comment by Undergrad2017** [comment]
Update worked, thanks for the assist!

**Comment by EGIwuxue** [comment]
Hello! I am using RStudio(R version 3.4.2) on Windows and I have successfully downloaded and installed JAGS, but whenever I try to install the "github", it gives me the following error:
 Error in github("brianstock/MixSIAR@*release", dependencies = TRUE) : 
  could not find function "github"
I have looked around online to try to solve this problem but I failed。Can you help me? Thanks！

**Comment by EGIwuxue** [comment]
I found the solution! Thanks , Best wishes!
