### ISSUE TITLE
Allow sources to vary by continuous covariate (e.g. time)

### ISSUE THREAD

**Issue by brianstock** [brianstock/MixSIAR#112]
By email:

Thank you for writing MixSIAR. I have two quick questions I was hoping you could answer:
  1. Though I have successfully built run a JAGS model using a continuous variable (time, as this was a seasonal programme), I cannot find a way to consider a covariance structure for the residuals as a function of time. Is there a way of doing this?
  2. Further, I can add the continuous covariate for consideration in the mixture but I cannot make the software accept it in the sources (source info per time point). Is there a way to do this?

**Comment by brianstock** [comment]
1. No, MixSIAR cannot currently do this. When you include a continuous covariate on the mixture, MixSIAR fits one static covariance matrix, constructed in 3 different ways depending on what data you have: from the proportions and source covariances = "multiplicative error" if you have more than 1 mix data point / "process error" if you only have 1 mix data point, or independent of the source covariances = "residual error only".

2. Sadly, no, MixSIAR cannot currently include time-varying sources either. The model you want sounds like the 3rd case study in [Parnell et al. (2013)](http://onlinelibrary.wiley.com/doi/10.1002/env.2221/full). @AndrewLJackson @andrewcparnell Have you shared your code for this paper somewhere?

**Comment by AndrewLJackson** [comment]
I've pinged @andrewcparnell an email to alert him to this request (he is not listed as a collaborator here so might not have seen this thread.. might be an idea to add him?). Im sure he has code for time varying sources, and im sure he will share.

**Comment by andrewcparnell** [comment]
Hi All. Yes I've shared this code with a few different people. However it's complicated so you need a good knowledge of R and JAGS to get it running. If you're ok with that, drop me an email at andrew.parnell@ucd.ie and I will send it on.

**Comment by DrAnaQueiros** [comment]
Thanks andrewcparnell! Will do!
Kind regards,
Ana
