### ISSUE TITLE
Working with mean values for consumers?

### ISSUE THREAD

**Issue by Mermessus** [brianstock/MixSIAR#115]
Hi, 

I am trying to use previously published dataset for a meta-analysis. Usually, only mean + sd values per sampling site are provided for consumers and sources. Is there a way to run mixing models with only mean values?

Best regards

**Comment by brianstock** [comment]
Not really, MixSIAR works by writing down the likelihood of each consumer data point, and then maximizing the likelihood given the data and prior. If you also have the sample size, you could generate random datasets using the mean, SD, and N assuming the consumer data were normally distributed.

I had this same issue when doing a literature search... Only 13/387 articles I found from 2012-2014 published their raw isotope data.
