### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by EGIwuxue** [brianstock/MixSIAR#118]
Hello!
 I am using RStudio(R version 3.4.2) on Windows and I have successfully downloaded and installed JAGS, but whenever I try to install the "github", it gives me the following error:
 Error in github("brianstock/MixSIAR@*release", dependencies = TRUE) : 
  could not find function "github"

I have looked around online to try to solve this problem but I failed。Can you help me? Thanks！

**Comment by brianstock** [comment]
You want the `install_github` function from the `devtools` package. Or `install.packages`, which will get the CRAN version. Check the readme again.
