### ISSUE TITLE
Modifying figures

### ISSUE THREAD

**Issue by jmlogan79** [brianstock/MixSIAR#121]
The figures provided in the package are great, but I would like to modify them slightly for publications.  For example, I would like to modify the position of the legend in posterior density plots, remove the "Group 1" header, etc.  If the full code available to allow for these sorts of manipulations?

**Comment by brianstock** [comment]
Hi John,

Sorry for the slow reply!  Hope this helps:

Yes, all of the code is here on Github: https://github.com/brianstock/MixSIAR/tree/master/R. If you fork this repository, it will make a new copy of all the .R files in your account that you can modify as you see fit.

The mix/source data plot code is `plot_data.R`, which calls `plot_data_two_iso.R` if you have 2 tracers, or `plot_data_one_iso.R` if you have 1. The posterior density plots start at line 232 of `output_JAGS.R`, and there are several sections depending on what covariates you have:
  - p.global (overall): 236-263
  - p.fac1 (factor 1): 265-294
  - p.fac2 (factor 2): 296-328
  - p.both (when 2 FE or 1FE + 1RE): 330-361
  - variance of random effects: 363-406

See also https://github.com/brianstock/MixSIAR/issues/30 and https://github.com/brianstock/MixSIAR/issues/55.

**Comment by icer182** [comment]
I think this also helps to answer my previous question entitled "Output Plots Font". Would we have to reinstall MixSIAR using our own GitHub account as the install directory?
