### ISSUE TITLE
Error: Error in which(S_SIG == 0) : object 'S_SIG' not found 

### ISSUE THREAD

**Issue by jnelson54** [brianstock/MixSIAR#122]
While trying to load source values I keep getting this.
Error in which(S_SIG == 0) : object 'S_SIG' not found

 I cannot find it in the code anywhere. Any idea what it is related to?

**Comment by jnelson54** [comment]
Got it to work but 

This gives the error
sources <- load_source_data(file=source.filename,
                            source_factors= "Season",  
                            conc_dep=FALSE,
                            data_type="mean",
                            mix)
This loaded
sources <- load_source_data(filename=source.filename, 
                           source_factors="Season", 
                           conc_dep=FALSE, 
                           data_type="means", 
                           mix)
So something in the file vs filename? 
anyway it is running so no big deal but if you have any idea why it errored let me know. 

happy coding days

**Comment by brianstock** [comment]
Yes, looks like you weren't using the right syntax to specify the file name. Glad you figured it out. In the future, look up the help file for a function that gives an error using `?load_source_data`.
