### ISSUE TITLE
Can you use variance in place of SD for discrimination data?

### ISSUE THREAD

**Issue by Justine9** [brianstock/MixSIAR#128]
It has been suggested that I incorporate the variance in discrimination factors within my mixing models, but noted that MixSIAR specifically requires a field with "SD" in the name. Would replacing standard deviation with variance to run the model provide an equally robust analysis?

**Comment by raphael-lavoie** [comment]
Including variance would inflate error. Variance = SD^2, so you can just do the square root of your variance to get SD. SD can then be used in your MixSIAR model.

**Comment by Justine9** [comment]
Thank you!
