### ISSUE TITLE
No diagnostics file or output

### ISSUE THREAD

**Issue by raphael-lavoie** [brianstock/MixSIAR#129]
I cannot get the diagnostics from any model. When I run the model with my data or any runnable examples e.g., wolves, I get:

`jags.1 <- run_model(run="test", mix, source, discr, model_filename, alpha.prior = c(1,1), resid_err, process_err)`
Compiling model graph
   Resolving undeclared variables
   Allocating nodes
Graph information:
   Observed stochastic nodes: 60
   Unobserved stochastic nodes: 53
   Total graph size: 2213

Initializing model

  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100%
  |**************************************************| 100%
Warning messages:
1: In structure(c(), class = c(class(x), class(y))) :
  Calling 'structure(NULL, *)' is deprecated, as NULL cannot have attributes.
  Consider 'structure(list(), *)' instead.
2: In structure(c(), class = c(class(x), class(y))) :
  Calling 'structure(NULL, *)' is deprecated, as NULL cannot have attributes.
  Consider 'structure(list(), *)' instead.
3: In structure(c(), class = c(class(x), class(y))) :
  Calling 'structure(NULL, *)' is deprecated, as NULL cannot have attributes.
  Consider 'structure(list(), *)' instead.

When I call:  
`output_options <- list(summary_save = TRUE,summary_name = "summary_statistics",sup_post = FALSE,plot_post_save_pdf = TRUE,plot_post_name = "posterior_density",sup_pairs = FALSE,plot_pairs_save_pdf = TRUE,plot_pairs_name = "pairs_plot",sup_xy = TRUE,plot_xy_save_pdf = FALSE,plot_xy_name = "xy_plot",gelman = TRUE,heidel = FALSE,geweke = TRUE, diag_save = TRUE,diag_name = "diagnostics",indiv_effect = FALSE,plot_post_save_png = FALSE,plot_pairs_save_png = FALSE,plot_xy_save_png = FALSE)`

`output_JAGS(jags.1, mix, source, output_options)`
Error: Casting formula contains variables not found in molten data: Var3, Var2, Var1

I cannot get the diagnostics output (gelman, heidel, geweke) and it does not save the diagnostics file. I can get the posterior graphs, the posterior probabilities, but I don’t know if my model performs well or if it converges because I don’t have the diagnostics. 

I know that the model is working because I have most graphs and the posterior probabilities. I can even get the diagnostics when using the GUI `mixsiar_gui()`, but not when using the scripts. I would rather use the scripts so I would like to solve that issue. 

Any help would be appreciated!
Thanks!
Raph

**Comment by brianstock** [comment]
Thanks for reporting this... I also get those warning messages when I run the wolves example now. However, I do get two saved diagnostics files (`diagnostics.txt`and `diagnostics.pdf`).

What version of R and MixSIAR are you running? And can you confirm that you're getting that behavior when you run:
```
library(MixSIAR)
mixsiar.dir <- find.package("MixSIAR")
source(paste0(mixsiar.dir,"/example_scripts/mixsiar_script_wolves.R"))
```

I'll look into the underlying problem.

**Comment by raphael-lavoie** [comment]
Hi Brian, 

Thank you very much for your reply!

I use MixSIAR 3.1.7 and here is my R session/version info:

> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1
Matrix products: default
...


I was able to get the diagnostics files working (on and off) after re-updating all packages. After some attempts by trial and error, I think that I can only load MixSIAR and no other packages in order to run the model. Otherwise, when calling:

`output_JAGS(jags.1, mix, source, output_options)`

it provides the posterior histograms, but then stops suddenly and gives this error without giving the diagnostics:

> Error: Casting formula contains variables not found in molten data: Var3, Var2, Var1

I am not sure if (and why) loading other packages causes the problem, but it seems to solve the issue in my case. So when I get that error, I detach the package(s) (in this example "reshape"):

`pkg <- "package:reshape"
detach(pkg, character.only = TRUE)`

and then I run the model.

Please let me know if there is another way to solve this issue or let me know what I am doing wrong. 

Thanks!
Raph

**Comment by brianstock** [comment]
Hmm, I'm not sure what's causing that. `output_JAGS` uses `cast` from the `reshape` package and `melt` from `reshape2`. I've been using the `tidyverse` set of packages recently, which accomplish the same tasks, but I don't really want to mess with changing the old `reshape` code... 

I solved your original bug report with the error warning coming from the `compositions` package. Download the most recent MixSIAR from Github and check. I'll soon submit a new version to CRAN, but not ready quite yet
