### ISSUE TITLE
Effective number of parameters

### ISSUE THREAD

**Issue by dianalafferty** [brianstock/MixSIAR#13]
Is it possible to get pD (effective number of parameters) in the output files?

**Comment by brianstock** [comment]
Yes. If you're running the GUI, the raw rjags output exists in the "mixsiar" environment.  You can print it to the screen with:
````
mixsiar$jags.1
````
To output the pD by itself with:
````
mixsiar$jags.1$BUGSoutput$pD
````

**Comment by robynpaice** [comment]
The mixsiar$jags.1 command still gives summary statistics, can I access raw data for all iterations somehow to combine sources and determine the statistics myself?

**Comment by brianstock** [comment]
`mixsiar$jags.1` is the rjags object, which contains the MCMC chains. To access the MCMC chains (p.global, p.fac1, p.fac2, depending on the random/fixed effects you included), use:
````
attach.jags(mixsiar$jags.1)
````
Now if you type `dim(p.global)` you should see that p.global is a matrix, where the number of columns is n.sources, and the number of rows is chain.length*n.chains. Full chain for proportion source 2 (overall/global population):
````
p.global[,2]
````
If you have random/fixed effects in your model, you'll see that p.fac1 and p.fac2 are 3-D arrays, where the dimensions are chain.length\*n.chains x factor level x source.

Full chain for proportion source 1, level 1 of factor 1 (Region 1 Deer in wolves ex):
````
p.fac1[,1,1]
````
Full chain for proportion source 3, level 8 of factor 2 (Pack 8 Salmon in wolves ex):
````
p.fac2[,8,3]
````
To confirm you understand the indexing correctly, quickly plot a histogram of the chain and compare it to the output plot, e.g.
````
hist(p.fac2[,8,3])
````
should match the blue curve in "posterior_density_diet_p_Pack 8.pdf".

**Comment by robynpaice** [comment]
Thank you very much Brian that worked perfectly.
