### ISSUE TITLE
Compatibility with major update to the loo package

### ISSUE THREAD

**Issue by jgabry** [brianstock/MixSIAR#134]
Hi @brianstock, I hope you got the email I sent a while back to package maintainers with packages that depend on the __loo__ package, but I also wanted to comment here to give you some details more specific to compatibility with your package. 

We're finally going to be submitting __loo__ version 2.0.0 this week and I think the one change that affects you is that the structure of the objects returned by the `loo` and `waic` functions will change slightly in order to accommodate some of the new features. In your case you'll just need to make minor tweaks where you pull out results from the loo objects, e.g.

https://github.com/brianstock/MixSIAR/blob/b485c62b1a5a3a09de90caa553f609e72c251f00/R/compare_models.R#L120-L126

With __loo__ 2.0.0, if `x` is an object returned by `loo()` then then `x$estimates` will be a matrix of the form 

```
           Estimate       SE
elpd_loo -83.614057 4.289943
p_loo      3.353629 1.159908
looic    167.228115 8.579885
```

and so you get `looic` and it's SE with `x$estimates["looic", "Estimate"]` and `x$estimates["looic", "SE"]`. For `waic()` it is analogous. The __loo__ 2.0.0 update is currently available from github (`stan-dev/loo`) if you want to install it and I will also send a follow up email when the submission is accepted to CRAN.

**Comment by brianstock** [comment]
Hi Jonah, 
Thanks for the heads up! I only pushed an update to CRAN that uses `loo` last week. Looks like an easy fix.

Unless you know otherwise, I don't believe I can submit a package to CRAN that depends on a github version of another package... so I'll wait until `loo` 2.0.0 is on CRAN, then make the change and resubmit MixSIAR to CRAN.

**Comment by jgabry** [comment]
@brianstock Just following up to let you know that the loo package update is now on CRAN.

**Comment by brianstock** [comment]
Done - thanks for making this easy!

**Comment by jgabry** [comment]
Awesome. And glad you’re including loo functionality in your package!

**Comment by jgabry** [comment]
One other thing:

If you’re interested, I recommend pointing your users (somewhere in the doc
maybe?) to the new vignettes we made for loo. They come with the package
but nicer looking versions are hosted at

http://mc-stan.org/loo/articles/

They don’t use MixSIAR but all the content is still relevant for people who
do.
