### ISSUE TITLE
Hypothesis testing in MixSIAR

### ISSUE THREAD

**Issue by emmmcooop** [brianstock/MixSIAR#138]
I have found MixSIAR to be very user-friendly with all the examples and such, but I am curious about hypothesis testing (maybe that's just a frequentist kind of thing, but many reviewers still like them). Based on my understanding, I can say "Group A eats more plants than Group B", and give the credible intervals, but that's the end of it. Is that correct?

Also, is there any way to get any more details from fits for continuous variables? I get a line as output without an equation for it, etc. Thank you very much.

**Comment by AndrewLJackson** [comment]
hi

yes thats pretty much it, re the credible intervals but you can attach a probability (which is not a million miles away from a p-value) to what the probaility of one group being higher, or different to the other might be. Bhattacharyya coefficients are your friend here. https://en.wikipedia.org/wiki/Bhattacharyya_distance#Bhattacharyya_coefficient

for the coefficients esimates.. if you run the “lakes” example from the vignettes, then head(jags.1$BUGSoutput$sims.matrix) will give you all the posterior estimates for the model you ran. In this one, the coefficiences of the the continuous effects in ILR transformed space are given as “ilr.cont1[1]” and “ilr.cont1[2]” for “ilr continuous explanatory variable 1” which in this example is the “Secchi depth”. While there are three sources each of which has a linear effect with secchi depth, the sum-to-one restriction and the corresponding use of the ilr transformation means that we only estimate the coefficients for two of the three sources, with the remainder being a function of these two.

moving back and forth between IRL transformed space and “actual” proportion space is not straight forward or easy to explain, hence we often rely on the visualisation of the outputs to make sense of it.

hope that helps

best wishes

andrew

--

Dr Andrew Jackson, PhD, FTCD
Associate Professor
Irish Research Council Laureate
School of Natural Sciences, Department of Zoology
Trinity College Dublin, the University of Dublin
Dublin 2, Ireland.

+353 1 896 2728 | a.jackson@tcd.ie<mailto:a.jackson@tcd.ie>
Twitter: @yodacomplex<https://twitter.com/yodacomplex>
http://www.tcd.ie/Zoology/research/<http://www.tcd.ie/Zoology/research/groups/jackson/>groups/jackson/

Trinity College Dublin, the University of Dublin is ranked 1st in Ireland
and in the top 100 world universities by the QS World University Rankings.

On 17 May 2018, at 06:45, emmmcooop <notifications@github.com<mailto:notifications@github.com>> wrote:


I have found MixSIAR to be very user-friendly with all the examples and such, but I am curious about hypothesis testing (maybe that's just a frequentist kind of thing, but many reviewers still like them). Based on my understanding, I can say "Group A eats more plants than Group B", and give the credible intervals, but that's the end of it. Is that correct?

Also, is there any way to get any more details from fits for continuous variables? I get a line as output without an equation for it, etc. Thank you very much.

**Comment by brianstock** [comment]
Hi Emma,

Yes, like Andrew said, you can directly calculate the probability that "Group A eats more of source X than Group B". See the bottom of https://github.com/brianstock/MixSIAR/issues/21.

You can backtransform the linear fits in ILR-space to proportion-space, but it's not trivial. 
To make the plot below, I calculate the linear regression for the full range of Length in ILR-space (for each MCMC draw individually), calculate the median and 95% CI, then transform to p-space to create the line + shading. The code to do this is in the new [Alligator Example](https://github.com/brianstock/MixSIAR/blob/master/inst/example_scripts/mixsiar_script_alligator.R). In this manner you could get a full posterior for the contribution of any source at any specific value of Length. 

![alligator_p_length](https://user-images.githubusercontent.com/5124211/40850641-0ae9df94-657a-11e8-9899-cf2da0024bdc.png)
