### ISSUE TITLE
Informative priors and source order

### ISSUE THREAD

**Issue by andrewcparnell** [brianstock/MixSIAR#139]
Hi,

Teaching MixSIAR this week and came across an odd feature/bug. It seems that, when providing informative prior information, it applies this to the sources alphabetically. This seems to be a desired feature, but the comment that the sources are treated this way is buried in the killer whale vignette. I would suggest adding a warning/note in `run_model` that reminds the users of this when they provide a non-equal set of alpha values. 

Andrew

**Comment by brianstock** [comment]
Hi Andrew,

Thanks, that's a good idea to make it more obvious. I've just made 2 small changes to `plot_prior`:
  1. added source names to the titles of the prior plots
  2. added warning message in console that sources are sorted alphabetically and users should check their alpha vector matches the plot

These changes are too minor to warrant a new CRAN release, so you'll have to install via 
```
devtools::install_github("brianstock/MixSIAR", dependencies=TRUE, build_vignettes = TRUE)
```
