### ISSUE TITLE
Resolved JAGS error "unknown variable"

### ISSUE THREAD

**Issue by cmhalffman** [brianstock/MixSIAR#143]
I resolved my problem described below involving using the script version of MixSIAR after successfully using the GUI version.  My problem had a simple cause: I had failed to include the "write_JAGS_model" command! No wonder the model did not run.  

"Moot" problem described below: 
I have successfully used the GUI version of MixSIAR on my single consumer (N=1) data set, but am now trying to use the script version so that I can access some of the additional features. However, I keep getting the following JAGS error pointing to an unknown variable:

Error in jags.model(model.file, data = data, inits = init.values, n.chains = n.chains,  : 
  RUNTIME ERROR:
Compilation error on line 91.
Unknown variable factor2_levels
Either supply values for this variable with the data
or define it  on the left hand side of a relation.

Is this related to my single-consumer data?  By the way, here is my script (everything works until the run JAGS model):

> mix <- load_mix_data(filename="consumer_USR2.csv", iso_names=c("d13C", "d15N"), factors=NULL, fac_random=NULL, fac_nested=NULL, cont_effects=NULL)

> source <- load_source_data(filename="sources4_USR.csv", source_factors=NULL, conc_dep=FALSE, data_type="means", mix)

> discr <- load_discr_data(filename="discrimination4_USR.csv", mix)

> plot_data (filename="isoscape_plot", plot_save_pdf=FALSE, plot_save_png=FALSE, mix, source, discr)

> if(mix$n.iso==2) calc_area(source=source, mix=mix, discr=discr)

> model_filename <- "MixSIAR_model.txt"

> resid_err=FALSE

> process_err=TRUE

> jags.1 <- run_model (run="test", mix, source, discr, model_filename, alpha.prior=1, resid_err, process_err)

**Comment by MaartenWynants** [comment]
After some trial and error I think I have fixed this issue.
This error only occurs if you only use 1 error class (either residual or process error only).
For example in my case :
>
model_filename <- "MixSIAR_model.txt"
process_err <- FALSE
resid_err <- TRUE
write_JAGS_model(model_filename, process_err, resid_err, mix, source)

jags.1 <- run_model(run="test",mix,source,discr,model_filename, alpha.prior = alpha, process_err,resid_err)
<
Make sure in your code these are in the same order: 1. process and 2. residual

Hope that helps.
Maarten
