### ISSUE TITLE
Posterior density plots for combined sources?

### ISSUE THREAD

**Issue by cmhalffman** [brianstock/MixSIAR#144]
Hello! Is it possible to get posterior density plots for combined sources (sources combined a posteriori using the combine_sources function)?
Thanks!

**Comment by Jordan-a-Iles** [comment]
Hi @cmhalffman 
Here is a work around for 5 sources. You could probably melt the df dataferame into long format to make the ggplot more elegant... 

`require(mixsiar)
require(ggplot2)

combined <- combine_sources(jags.1, mix, source, alpha.prior = 1, groups = grp)
df <- as.data.frame(combined$post)

ggplot(df) +
  geom_density(alpha = 0.3, aes(x = `p.fac1[1,1]`, y = ..scaled..), col = 'green', fill = 'green') +
  geom_density(alpha = 0.3, aes(x = `p.fac1[1,2]`, y = ..scaled..), col = 'purple', fill = 'purple') +
  geom_density(alpha = 0.3, aes(x = `p.fac1[1,3]`, y = ..scaled..), col = 'orange', fill = 'orange') +
  geom_density(alpha = 0.3, aes(x = `p.fac1[1,4]`, y = ..scaled..), col = 'yellow', fill = 'yellow') +
  geom_density(alpha = 0.3, aes(x = `p.fac1[1,5]`, y = ..scaled..), col = 'blue', fill = 'blue') +
  theme_bw() +
  xlab("Proportion of Diet") + 
  ylab("Scaled Posterior Density") + 
  xlim(0, 1) +
  labs(title = "Species 1") + 
  theme(legend.position = c(1, 1), 
        legend.justification = c(1,1), 
        legend.title = element_blank())`

**Comment by brianstock** [comment]
Yes, the posterior chains of the aggregated/combined source proportions are in the `$post` element returned by `combine_sources`. You can plot these as you wish. I should have made this easier to do, sorry... Looking at lines 231-361 of [`output_JAGS`](https://github.com/brianstock/MixSIAR/blob/master/R/plot_intervals.R) may help - this is the code that produces the MixSIAR posterior density plots. You could also use the nice posterior plotting functions from the [`bayesplot`](http://mc-stan.org/bayesplot/articles/plotting-mcmc-draws.html) package.

Also, the `plot_intervals` function operates directly on the output of `combine_sources` to produce posterior uncertainty intervals. See examples in [`plot_intervals`](https://github.com/brianstock/MixSIAR/blob/master/R/plot_intervals.R) (help file accessed via `?MixSIAR::plot_intervals`).
