### ISSUE TITLE
Changing summary statistics using the MixSIAR GUI

### ISSUE THREAD

**Issue by MDelongWSU** [brianstock/MixSIAR#145]
I would like to add  1% and 99% to the summary statistics.  Is there a way to add these and still use GUI or does it need to be included as code.

**Comment by AndrewLJackson** [comment]
Hi

 The GUI will not allow you to arbitrarily alter summary statistics. You could write them down or input them elsewhere and add anything you like to them but then there is no reproducible trail for the numbers. If would be better by far to do this using a script; but I am still in easy about the logic behind it.

Best wishes
Andrew



––––––––––––

Dr Andrew Jackson, PhD, FTCD
Associate Professor
School of Natural Sciences, Department of Zoology
Trinity College Dublin, the University of Dublin
Dublin 2, Ireland.

+353 1 896 2728 | a.jackson@tcd.ie<mailto:a.jackson@tcd.ie>

Twitter: @yodacomplex<https://twitter.com/yodacomplex>
http://www.tcd.ie/Zoology/research/research/theoretical/AndrewJackson.php

Trinity College Dublin, the University of Dublin is ranked 1st in Ireland
and in the top 100 world universities by the QS World University Rankings.


On 29 Jun 2018, at 16:04, MDelongWSU <notifications@github.com<mailto:notifications@github.com>> wrote:


I would like to add 1% and 99% to the summary statistics. Is there a way to add these and still use GUI or does it need to be included as code.

**Comment by brianstock** [comment]
If you want to modify a version of `output_stats` to do this, you can add `.01` and `.99` to [line 114](https://github.com/brianstock/MixSIAR/blob/master/R/output_stats.R#L114). No way to use the GUI.
