### ISSUE TITLE
obtaining alpha values for priors

### ISSUE THREAD

**Issue by VirginiaMorera** [brianstock/MixSIAR#15]
Version: 2.1.2
Issue: I've been trying to find, inside MixSIAR code, a way to obtain alpha parameters. I didn't succeed, so I adapted this bit of code from the `siarelicit()` function in SIAR, to use the vector it produces as alpha.priors in the MixSIAR models. Can anyone confirm that it is correct to use the values obtained in MixSIAR models? 

```R
meanprops <- c(0.5, 0.2, 0.2, 0.1) #mean proportions based on prior info
propsum <- sum(meanprops) #must add to 1
    
sdans <- 1 #which source are we giving the SD of? (nº of position in meanprops vector)
sourcesd <- 0.05
    
Q <- (meanprops[sdans] * (1 - meanprops[sdans])/sourcesd^2) - 1
alphapars <- meanprops * Q
alpha <- paste(as.numeric(alphapars), collapse=", ")
print(alpha)

(meanprops[sdans] * (1 - meanprops[sdans])/sourcesd^2)  #cannot be <1
```

Thank you very much.

Virginia

**Comment by brianstock** [comment]
We're working on a MixSIAR paper, but for now...

You could use the `siarelicit()` function from SIAR, but the code you've pasted above will give you a strongly informative prior of alpha = "49.5, 19.8, 19.8, 9.9". The sum of the alphas determines the weight of your prior (higher = more weight, tighter distribution).  In the figure below, the "uninformative" alpha = (1,1,1,1) distributions are in grey on left.  Using the alpha generated above gives you the prior distributions in blue in the center.  Using alpha scaled to the number of sources (alpha sum to 4, in the proportions given by `meanprops`) gives you prior distributions in red on right.

![priors](https://cloud.githubusercontent.com/assets/5124211/6342616/82ae1032-bb90-11e4-8067-cadd3daac3fa.png)

The weight you give your informative prior may depend on a number of factors: sample size of stomach contents, time scale of stomach contents vs. isotopes, and number of tracers/isotopes in the model. As a default or starting point, we'd recommend the prior in red, scaled so the sum of alphas = number of sources. Simply:

```
n.sources <- length(meanprops)
scaled.alpha <- meanprops*n.sources
```

Whatever alpha parameters you choose, it would be wise to plot them to see if they make sense. I'll write a `get_alpha` function to add to MixSIAR that generates informative priors and plots them.  Until then, you can use the following code to plot your priors:

```
library(compositions)
p = rDirichlet.rcomp(10000, alpha = scaled.alpha)
p1 = c(p[,1], seq(0,1,0.01))
p2 = c(p[,2], seq(0,1,0.01))
p4 = c(p[,4], seq(0,1,0.01))
hist(p1)
hist(p2)
hist(p4)
```
