### ISSUE TITLE
Get posterior chains into one tidy data frame

### ISSUE THREAD

**Issue by valybionda** [brianstock/MixSIAR#152]
Hi,
I was trying to get all the posterior chains in one data frame to use to plot MixSIAR results in a "SIBER" way. Something like siberdensityplot. 
As it was already posted, I was trying to use this piece of code:

```
# Get posterior chains into one tidy data frame
attach.jags(jags.1)
post.grass <- data.frame(habitat = "Seagrass",aw = p.fac1[,1,1], bs = p.fac1[,1,2], clam = p.fac1[,1,3], crab = p.fac1[,1,4], fish = p.fac1[,1,5], snail = p.fac1[,1,6])
post.coral <- data.frame(habitat = "Coral",aw = p.fac1[,2,1], bs = p.fac1[,2,2], clam = p.fac1[,2,3], crab = p.fac1[,2,4], fish = p.fac1[,2,5], snail = p.fac1[,2,6])
grass <- post.grass %>% gather(source,value,2:7)
coral <- post.coral %>% gather(source,value,2:7)
all <- rbind(grass,coral)
```

Since I have two fixed factors (3 levels for the first one and 9 for the second), my sims.matrix has ilr.fac1 and ilr.fac2, etc. But I don't know how to extract the posterior distribution for each source (I have 3 sources).
Does "ilr.fac[,1,1]" correspond to the data for the first level of the Factor 1 for the first source?

Waiting for some suggestions
Thank you
Valentina

**Comment by brianstock** [comment]
Hi Valentina,

Sorry for the long wait... hopefully you found the answer elsewhere in the documentation. `ilr.fac1[,f1,k]` will have the posterior chains for the `f1`th level of factor 1 and the `k`th source. In the above code from the mantis shrimp example, factor 1 = habitat, with 2 levels (seagrass = 1, coral = 2).
