### ISSUE TITLE
GUI install problems

### ISSUE THREAD

**Issue by naalipalo** [brianstock/MixSIAR#154]
This might not be the correct forum but thought I would ask since the instructions say to install RGtk2.  In R version 3.5.1 (2018-07-02) Platform: i386-w64-mingw32/i386 (32-bit), RStudio version 1.1.456, I am having major difficulties figuring out why RGtk2 will not install.  Since I can't get this to install, I am unable to do any other step to get the GUI running.  I understand the script is still there, but for me to walk through the examples and poke at the formatting of the data (especially the alligator data), I thought the GUI would help make that part easier/faster. 

` install.packages("RGtk2", dependencies = TRUE)`

> Installing package into ‘C:/Users/myname/Documents/R/win-library/3.5’ (as ‘lib’ is unspecified)
> trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/RGtk2_2.20.35.zip'
> Content type 'application/zip' length 16250952 bytes (15.5 MB)
> downloaded 15.5 MB
> package ‘RGtk2’ successfully unpacked and MD5 sums checked
> The downloaded binary packages are in
> 	C:\Users\myname\AppData\Local\Temp\RtmponDKXU\downloaded_packages

`library(RGtk2)`

A window pops up with a system error which says 

> "The program can't start because libatk-1.0-0.dll is missing from your computer. Try reinstalling the program to fix this problem"

I click OK and the next screen immediately to pop up is "

> Need GTK+?

I get 2 options: 

> Install GTK+ or Do not install GTK+.

 I click install and OK and every time I get this:

> Loading required package: RGtk2
> Error in inDL(x, as.logical(local), as.logical(now), ...) :
> unable to load shared object 'C:/Users/myname/Documents/R/win-library/3.5/RGtk2/libs/i386/RGtk2.dll':
> LoadLibrary failure: The specified module could not be found.
> 
> trying URL 'http://ftp.gnome.org/pub/gnome/binaries/win32/gtk+/2.22/gtk+-bundle_2.22.1-20101227_win32.zip'
> Error: package or namespace load failed for ‘RGtk2’:
> .onLoad failed in loadNamespace() for 'RGtk2', details:
> call: download.file(dep_url, path, mode = "wb")
> error: cannot open URL 'http://ftp.gnome.org/pub/gnome/binaries/win32/gtk+/2.22/gtk+-bundle_2.22.1-20101227_win32.zip'
> Error: package ‘RGtk2’ could not be loaded
> In addition: Warning messages:
> 1: Failed to load RGtk2 dynamic library, attempting to install it.
> 2: In download.file(dep_url, path, mode = "wb") :
> InternetOpenUrl failed: 'The operation timed out'

**Comment by matthewcrogers** [comment]
I am having the exact same problem.  Did you find a way to get it installed?

**Comment by brianstock** [comment]
Hello, just wanted to apologize for this... it's been a pain over the years and I don't have any guidance beyond what I've put in the manual. My suggestion is that if you envision using MixSIAR for a publication (not just for a course or preliminary analysis), your time is better spent figuring out the script version versus getting the GUI to install.

I've just confirmed that the GUI installs smoothly on my machine (Ubuntu 18.04). If you really want the GUI, you could try another machine, especially if it's Linux or Mac.

**Comment by naalipalo** [comment]
> 
> 
> I am having the exact same problem. Did you find a way to get it installed?

Nope, I gave up. Id still appreciate a solution though because this isnt the only GUI or package that ive come across needing the library

**Comment by AndrewLJackson** [comment]
Hi brain and all

My own two cents is to give up on gui entirely both as a user and as developers. I feel that R is as friendly as it gets already for reasonably advanced data analysis and this gui mess can just make it worse not better.

Beta wishes
Andrew



––––––––––––

Dr Andrew Jackson, PhD, FTCD
Associate Professor
School of Natural Sciences, Department of Zoology
Trinity College Dublin, the University of Dublin
Dublin 2, Ireland.

+353 1 896 2728 | a.jackson@tcd.ie<mailto:a.jackson@tcd.ie>

Twitter: @yodacomplex<https://twitter.com/yodacomplex>
http://www.tcd.ie/Zoology/research/research/theoretical/AndrewJackson.php

Trinity College Dublin, the University of Dublin is ranked 1st in Ireland
and in the top 100 world universities by the QS World University Rankings.


On 18 Apr 2019, at 17:32, naalipalo <notifications@github.com<mailto:notifications@github.com>> wrote:


I am having the exact same problem. Did you find a way to get it installed?

Nope, I gave up. Id still appreciate a solution though because this isnt the only GUI or package that ive come across needing the library

**Comment by matthewcrogers** [comment]
Hi Brian -

Thanks for your and Andrew's replies to this thread.  I have been using
SIAR and now MixSIAR for a long time and I really appreciate all of the
work you have put into it.  I use the script version almost exclusively for
my actual data analysis.  I wouldn't be sad if the GUI went away.  That
being said, I do find it useful for doing quick test runs and plotting the
data preliminarily.

Which brings up my main problem - on a couple of my machines, I can get the
script-based version to work but not the GUI.  On the machines where the
script version works, but not the GUI, I cannot get a plot to visualize my
sources and my mixes.  So is there some common thread that might be causing
this?  I have one windows machine where the GUI works and I can visualize
the isotope plots (by way of the GUI).  I have a windows and a mac where
the GUI doesn't work AND I can't get the souce/mix plots to work even
through  the script commands.  Does this make sense and do you have any
idea where m problems might be happening?

Ultimately I am close to making the same source/mix plots on my own but it
is really nice to just quickly produce them when i have all my data already
in MixSIAR.

Thanks again and all the best,

Matt Rogers

Matthew Rogers

Nutritional Ecology and Stable Isotope Biogeochemistry
Recruitment Energetics and Coastal Assessment Program

NOAA Alaska Fisheries Science Center
Auke Bay Laboratories
17109 Pt. Lena Loop, Juneau, Alaska 99801
907.789.6016
matthew.rogers@noaa.gov

**Comment by AndrewLJackson** [comment]
hi matt

Im pretty sure all the figures that can be created via GUI can be created with script commands but you seem to have a problem with the figures all together in some instances. Ive started seeing some Cairo plot errors, and wonder if some libraries in the OS have changed. I haven’t worked on a windows machine in a long time, but Mac osx needs things like xquartz and command line tools installed at a minimum. You might also need to manually install (or reinstall) Cairo per http://macappstore.org/cairo/

I tend to remember to install lots of these things myself and forget that not everyone might, but then the errors thrown from various R and python scripts tend to be rather idiosyncratic and difficult to debug or fix.

Another big problem for some users that ive seen recently (at a recent workshop I taught on too) is using company owed machines that have write access to important things like paths and root directories.

Not sure if any of these issues might be related to your pobrlems.. but its a pretty frustraigng guessing game.

Best wishes

Andrew

--

Dr Andrew Jackson, PhD, FTCD
Associate Professor
Irish Research Council Laureate
School of Natural Sciences, Department of Zoology
Trinity College Dublin, the University of Dublin
Dublin 2, Ireland.

+353 1 896 2728 | a.jackson@tcd.ie<mailto:a.jackson@tcd.ie>
Twitter: @yodacomplex<https://twitter.com/yodacomplex>
http://www.tcd.ie/Zoology/research/<http://www.tcd.ie/Zoology/research/groups/jackson/>groups/jackson/





On 27 Jun 2019, at 20:18, matthewcrogers <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Brian -

Thanks for your and Andrew's replies to this thread. I have been using
SIAR and now MixSIAR for a long time and I really appreciate all of the
work you have put into it. I use the script version almost exclusively for
my actual data analysis. I wouldn't be sad if the GUI went away. That
being said, I do find it useful for doing quick test runs and plotting the
data preliminarily.

Which brings up my main problem - on a couple of my machines, I can get the
script-based version to work but not the GUI. On the machines where the
script version works, but not the GUI, I cannot get a plot to visualize my
sources and my mixes. So is there some common thread that might be causing
this? I have one windows machine where the GUI works and I can visualize
the isotope plots (by way of the GUI). I have a windows and a mac where
the GUI doesn't work AND I can't get the souce/mix plots to work even
through the script commands. Does this make sense and do you have any
idea where m problems might be happening?

Ultimately I am close to making the same source/mix plots on my own but it
is really nice to just quickly produce them when i have all my data already
in MixSIAR.

Thanks again and all the best,

Matt Rogers

Matthew Rogers

Nutritional Ecology and Stable Isotope Biogeochemistry
Recruitment Energetics and Coastal Assessment Program

NOAA Alaska Fisheries Science Center
Auke Bay Laboratories
17109 Pt. Lena Loop, Juneau, Alaska 99801
907.789.6016
matthew.rogers@noaa.gov<mailto:matthew.rogers@noaa.gov>

**Comment by brianstock** [comment]
Thanks Andrew for chiming in.

Sorry Matt... cross-platform graphics are prone to problems. Have you tried saving as PNG vs PDF vs plotting to the screen? In R Studio vs the R console? I've had problems with graphics in R Studio that didn't show up with the console.

I don't know why the plots to screen wouldn't work - they're just saving a ggplot2 object as `g` and then calling `print(g)` (see [plot_data_two_iso.R](https://github.com/brianstock/MixSIAR/blob/master/R/plot_data_two_iso.R)). The save as PDF functionality uses `cairo_pdf`.

**Comment by matthewcrogers** [comment]
Thanks for all of the ideas - I will try some of these out and see if they
help.  Cheers!

Matthew Rogers

Nutritional Ecology and Stable Isotope Biogeochemistry
Recruitment Energetics and Coastal Assessment Program

NOAA Alaska Fisheries Science Center
Auke Bay Laboratories
17109 Pt. Lena Loop, Juneau, Alaska 99801
907.789.6016
matthew.rogers@noaa.gov
