### ISSUE TITLE
Having a problem plotting the isotope mixing space 

### ISSUE THREAD

**Issue by matthewcrogers** [brianstock/MixSIAR#157]
Hello!  Thanks so much for developing this package.  I have used SIAR for a while and I'm getting used to MixSIAR.  I have successfully run the program using the GUI and the script.  But, I cannot get the package to plot my mixing space with sources and mixes.  I am getting the following error:

Error in if (!is.na(source$by_factor)) { : argument is of length zero
In addition: Warning message:
In is.na(source$by_factor) :
  is.na() applied to non-(list or vector) of type 'NULL'

I have not included source factors, so I have NULL in that line.  I do have factors in my mix inputs though. 

Is this common?  Any ideas on quick fixes?  If you need more information please let me know.  

Thanks very much!

-Matt Rogers
NOAA Fisheries
Alaska Fisheries Science Center
Juneau, Alaska

**Comment by brianstock** [comment]
Hi Matt,

Sorry for the slow reply. Hard to diagnose without your files - if you haven't figured it out or given up, I'll take a look if you post them or email me.

Checking - you're reading in your source data with something like:
```
source <- load_source_data(filename=source.filename,
  source_factors=NULL,
  conc_dep=TRUE,
  data_type="means",
  mix)
```
Looking at `load_source_data`, `source$by_factor` gets set to `0` if `length(source_factors)==0`, which will happen if `source_factors` is `NULL`.

**Comment by matthewcrogers** [comment]
Hi Brian -

That is how I am loading my source data.  Maybe I will play around with the
factors settings.

The weird thing is that using all of the same files and data for my
consumers, sources, and TEFs, I can get the plots to print if I use the
GUI.  But it is not working in the script version.

So I can generate the plots and I don't want to worry about this too much.
I was just curious if there was an easy fix.

Thanks so much for your reply and for continuing to develop this package.
It's amazing and I love it :)

Matt

Matthew Rogers

Nutritional Ecology and Stable Isotope Biogeochemistry
Recruitment Energetics and Coastal Assessment Program

NOAA Alaska Fisheries Science Center
Auke Bay Laboratories - Ted Stevens Marine Research Institute
17109 Pt. Lena Loop, Juneau, Alaska 99801
907.789.6016




<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
