### ISSUE TITLE
The legend covers up my plot

### ISSUE THREAD

**Issue by goldsoundz80** [brianstock/MixSIAR#158]
Hello,
I've created a plot with my data using the script version of MixSIAR, it looks great, but the problem is the legend covers maybe 1/8th of my plot and completely obscures one of my sources.

Is there any way to change it? It would be better if the legend was outside of the plot.

I saw a previous post called "Modifying figures" but I'm afraid I didn't really understand your response as I'm new to R...

Thanks! :)

Rob Harbour
Heriot-Watt University

<a href="https://imgur.com/By1A3do"><img src="https://i.imgur.com/By1A3do.png" title="source: imgur.com" /></a>
https://i.imgur.com/By1A3do.png

**Comment by goldsoundz80** [comment]
If anyone else comes across this, I fixed it by modifying line 141 of `plot_data_two_iso.r` to read:
`ggplot2::theme(legend.position="left"`

I ran this script manually first by cutting and pasting it into R Studio, then ran my MixSIAR script again... there's probably an easier way to do this, so I'm open to suggestions! 

![screenshot 2019-02-08 at 11 32 53](https://user-images.githubusercontent.com/23124163/52476136-a7644a80-2b95-11e9-8eec-19038edab6ce.png)

**Comment by brianstock** [comment]
Great, glad you figured it out!

It's impossible for me to make perfect figures without knowing what the data will look like... The best solution to this would be for me to allow arguments to be passed through  `plot_data_two_iso` to the ggplot functions it calls.

**Comment by jrfrun** [comment]
Brian
your suggestion for allowing that argument to be passed to the ggplot, is that something you have modified or something you will do in the future?

regards
