### ISSUE TITLE
Error extracting summary stats from a posteriori combine_sources

### ISSUE THREAD

**Issue by TeenaSkinner** [brianstock/MixSIAR#160]
Hi Brian,

I'm running a model with six sources, which I then want to combine a posteriori in to two groups of three. The combine_sources function works fine but I then get an error when I try to extract the summary_stats for the combined sources.

Below is what I ran:

#This works fine
combined <- combine_sources(jags.1, mix, source, alpha.prior=1, groups=list(plankton=c("Nocturnal plankton","Diurnal plankton", "DVM plankton"), reef=c("Benthic algae","Coral", "Detritus")))
 
#This works fine
apply(combined$post, 2, median)
 
#When I run this line, I get an error. See below. 
summary_stat(combined, meanSD=FALSE, quantiles=c(.025,.5,.975), savetxt=TRUE)
 
_Error in dimnames(x) <- dn : length of 'dimnames' [1] not equal to array extent_

I’ve checked “combined” and it has two dimnames (plankton and reef) so I’m not sure why here it seems to say it’s not equal to array extent. Do you have any idea what this means or how to fix it? I would really like the means for these final two groups.

Thanks!

Tina

**Comment by HendrikSchultz** [comment]
Hi Teena, I am receiving the same error - did you find a solution in the end? Thank you! Hendrik
