### ISSUE TITLE
Is it possible to plot diet contributions for each individual predator?

### ISSUE THREAD

**Issue by AylenM** [brianstock/MixSIAR#164]
Hi!
I really want to know if it is possible in MixSiar to plot contributions/proportions of diets for each individual/predator.
Thanks in advance!

**Comment by brianstock** [comment]
Hi Aylen,

Yes that should be pretty easy with the built-in functions, just specify
individual/predator as a covariate (fixed or random effect as you think is
appropriate). There are a few examples of this in the manual and papers
(alligator ex in PeerJ).

Best,
Brian

**Comment by AylenM** [comment]
¡Thank you very much for your help! I really appreciate it since I'm new to R and MixSiar.
Regards!
