### ISSUE TITLE
Error plotting combined_sources

### ISSUE THREAD

**Issue by Jordan-a-Iles** [brianstock/MixSIAR#179]
Hi Brian, 

I am getting an error when running combined_sources() for some (but not all) jags models. 

`combined <- combine_sources(jags.1, mix, source, alpha.prior = 1, groups = grp)`
Error in plot.new() : figure margins too large

This stops the function from creating the 'combined' object

**Comment by brianstock** [comment]
Hi Jordan,

Are you using RStudio? That's the only time I've seen that error message. If so, try running MixSIAR from the console. If not, we'll need more information... You can also step through the [`combine_sources`](https://github.com/brianstock/MixSIAR/blob/master/R/combine_sources.R) function line-by-line to see where the error occurs:
