### ISSUE TITLE
Intra-individual variability in diet

### ISSUE THREAD

**Issue by PaulaPerrig** [brianstock/MixSIAR#18]
For some of my consumers I have 1 isotopic value and for some of them I have 2 (representing two sampling moments). I am interested on knowing (1) if there is variation in the diet of individuals, and (2) diet of the population. How can I model this information with MixSIAR? Thank you very much for your help.

**Comment by eric-ward** [comment]
I guess I don't quite understand the data. Do you mean you have 2 measurements, or 2 isotopes? How many sources? I think for answering the variability in individuals versus population, getting your data in a setup similar to the wolf example in MixSIAR would be a good start . But if you only have 1 isotope, you could probably abandon mixing models and just analyze the isotope data with a hierarchical mixed effects model.
