### ISSUE TITLE
Fatal error when loading MixSIAR GUI on Mac OS X

### ISSUE THREAD

**Issue by samleggs22** [brianstock/MixSIAR#183]
I've tried all of the different downloading, reinstalling etc. suggestions in the manuals and here on Github but as soon as I run mixsiar_gui() I get a R session fatal error. Not sure which part of the various packages etc. I've possibly installed incorrectly etc. to cause this. I've updated all the software and packages, made sure I have the latest version of JAGS etc. and it still keeps crashing. Help please!
![Screenshot 2019-09-26 14 31 06](https://user-images.githubusercontent.com/54674524/65693225-dcada200-e06b-11e9-9384-db9fe6efae56.png)

**Comment by AndrewLJackson** [comment]
Hi sam

To be honest I would personally recommend you ditch the GUI And stick with an R script or notebook to run mixsiar. The GUI is dependent on lots of packages and non-R bits of code. It will be worth any additional short term pain to learn to use the scripts in the medium and long term I promise!

Best wishes

Andrew

--

Dr Andrew Jackson, PhD, FTCD
Associate Professor
Irish Research Council Laureate
School of Natural Sciences, Department of Zoology
Trinity College Dublin, the University of Dublin
Dublin 2, Ireland.

+353 1 896 2728 | a.jackson@tcd.ie<mailto:a.jackson@tcd.ie>
Twitter: @yodacomplex<https://twitter.com/yodacomplex>
http://www.tcd.ie/Zoology/research/<http://www.tcd.ie/Zoology/research/groups/jackson/>groups/jackson/





On 26 Sep 2019, at 14:42, Sam Leggett <notifications@github.com<mailto:notifications@github.com>> wrote:


I've tried all of the different downloading, reinstalling etc. suggestions in the manuals and here on Github but as soon as I run mixsiar_gui() I get a R session fatal error. Not sure which part of the various packages etc. I've possibly installed incorrectly etc. to cause this. I've updated all the software and packages, made sure I have the latest version of JAGS etc. and it still keeps crashing. Help please!
[Screenshot 2019-09-26 14 31 06]<https://user-images.githubusercontent.com/54674524/65693225-dcada200-e06b-11e9-9384-db9fe6efae56.png>

**Comment by brianstock** [comment]
Sam,

Sorry about the problem. I agree with Andrew, the script version is the way
to go. If the GUI installs easily then it can be nice to start with, but
it's not worth more than 30-60 min troubleshooting - you can be up and
running with the scripts in that time.

I don't have access to a Mac for testing. Last I checked, the GUI still
runs without any install issue on Linux (Ubuntu) if you have access to a
machine with that OS.

**Comment by samleggs22** [comment]
Thank you both. The script version works for me but we're doing a SIMMs journal club/group and trying out various script vs GUIs so I just wanted to see what the differences were to report back. 
I'll give it a skip for this meeting and see if I can access LINUX to try it out later.

Cheers!
