### ISSUE TITLE
How to revise the title and other information of automatically generated  figure

### ISSUE THREAD

**Issue by HAN-2** [brianstock/MixSIAR#185]
Hello, I am a phD student in soil science and a beginner of MixSIAR. During the operate process, I found I cannot change the  axis's title and other relative information of figure which generated automatically by MixSIAR. 
By the way, how to understand the meaning of "scaled posterior density"
Thank you for your attention.
Han
haf033@usask.ca

**Comment by brianstock** [comment]
Hi Han,

On modifying figures, see https://github.com/brianstock/MixSIAR/issues/30, https://github.com/brianstock/MixSIAR/issues/121, https://github.com/brianstock/MixSIAR/issues/55, and https://github.com/brianstock/MixSIAR/issues/90. Because it's difficult to make default plots look good for publication in every case, I assume users will need to modify the code to create publication-ready figures for their situation (e.g. change legend position, etc.). But I am curious... why do you want to modify the axes labels? I wouldn't think they'd need to be modified.

On the meaning of "scaled posterior density", see https://github.com/brianstock/MixSIAR/issues/21 and https://github.com/brianstock/MixSIAR/issues/24.

**Comment by HAN-2** [comment]
> Hi Han,
> 
> On modifying figures, see #30, #121, #55, and #90. Because it's difficult to make default plots look good for publication in every case, I assume users will need to modify the code to create publication-ready figures for their situation (e.g. change legend position, etc.). But I am curious... why do you want to modify the axes labels? I wouldn't think they'd need to be modified.
> 
> On the meaning of "scaled posterior density", see #21 and #24.

Hello Brain,
Thank you for your response.
 I failed to change the figure although I try many times to find the file as you said in the questions you listed during my spare time in this week. I am thinking if it is possible to output the data for the overall figure, then I can plot the figure by myself.
My research topic is about water uptake by trees using isotope method. Thus, it is the title "proportion of diet" is unsuitable, maybe "contribution" is better for me in this figure.
Anyway, thank you for your effort in MixSIAR and the response.
Best wishes.
Han

**Comment by HAN-2** [comment]
> Hi Han,
> 
> On modifying figures, see #30, #121, #55, and #90. Because it's difficult to make default plots look good for publication in every case, I assume users will need to modify the code to create publication-ready figures for their situation (e.g. change legend position, etc.). But I am curious... why do you want to modify the axes labels? I wouldn't think they'd need to be modified.
> 
> On the meaning of "scaled posterior density", see #21 and #24.

Hello Brian,
Thank you for your response.
I failed to change the figure although I try many times to find the file as you said in the questions you listed during my spare time in this week. I am thinking if it is possible to output the data for the overall figure, then I can plot the figure by myself.
My research topic is about water uptake by trees using isotope method. Thus, it is the title "proportion of diet" is unsuitable, maybe "contribution" is better for me in this figure.
Anyway, thank you for your effort in MixSIAR and the response.
Best wishes.
Han

**Comment by MaartenWynants** [comment]
Here's some simple code to 1) get the output data from Jags and 2) plot it into a boxplot using ggplot. Note that I use the names of my sources so you'd have to change those. 

#RAW data for make your own graps
p.global<- jags.1$BUGSoutput$sims.list$p.global
write.csv(p.global, file = "pglobal.csv", row.names = FALSE)
p.fac1<-jags.1$BUGSoutput$sims.list$p.fac1
write.csv(p.fac1, file = "pfac.csv", row.names = FALSE)
fulldata<-jags.1$BUGSoutput$sims.list
write.csv(fulldata, file = "fulldata.csv", row.names = FALSE)
stats <- jags.1$BUGSoutput$summary
write.csv(stats, file = "stats.csv")
sims<- jags.1$BUGSoutput$sims.array
write.csv(sims, file = "sims.csv")

# Get posterior chains into one tidy data frame

post.mix_site1 <- as.data.frame(jags.1$BUGSoutput$sims.list$p.global[,1])
post.mix_site2 <- as.data.frame(jags.1$BUGSoutput$sims.list$p.global[,2])
post.mix_site3 <- as.data.frame(jags.1$BUGSoutput$sims.list$p.global[,3])
post.mix_site4 <- as.data.frame(jags.1$BUGSoutput$sims.list$p.global[,4])
post.mix_site5 <- as.data.frame(jags.1$BUGSoutput$sims.list$p.global[,5])
post.mix_site6 <- as.data.frame(jags.1$BUGSoutput$sims.list$p.global[,6])



colnames(post.mix_site1) <- source$source_names[1]
#Source1<-cbind(Site="Endabash", post.mix_site1)
#head(Source1)

colnames(post.mix_site2) <- source$source_names[2]
#Source2<-cbind(Site="Kirurumo", post.mix_site2)

colnames(post.mix_site3) <- source$source_names[3]
#Source3<-cbind(Site="Magara", post.mix_site3)

colnames(post.mix_site4) <- source$source_names[4]
#Source4<-cbind(Site="Makuyuni", post.mix_site4)

colnames(post.mix_site5) <- source$source_names[5]
#Source5<-cbind(Site="Maole", post.mix_site5)

colnames(post.mix_site6) <- source$source_names[6]
#Source6<-cbind(Site="MtoWaMbu", post.mix_site6)



###combine all file into one 
site_comp<-cbind(post.mix_site1,post.mix_site2,post.mix_site3,post.mix_site4,post.mix_site5,post.mix_site6)
head(site_comp)
write.csv(site_comp,file = "site_comp.csv")
boxprop_site <- site_comp %>% gather(source,value,1:6)

###boxplot

ggplot(aes(y = value, x = source, fill = source), data = boxprop_site) +
  geom_boxplot(outlier.colour = NA) +
  coord_cartesian(ylim = c(0,1)) +
  theme_classic() +
  xlab("Source") +
  ylab("Proportion of sediment") + ggtitle("Sediment contribution") + theme(plot.title = element_text(hjust = 0.5)) + 
  scale_x_discrete(limits=c("DUD","END","MAK","MWM","NGO","TAR"))

**Comment by HAN-2** [comment]
> Here's some simple code to 1) get the output data from Jags and 2) plot it into a boxplot using ggplot. Note that I use the names of my sources so you'd have to change those.
> 
> #RAW data for make your own graps
> p.global<- jags.1$BUGSoutput$sims.list$p.global
> write.csv(p.global, file = "pglobal.csv", row.names = FALSE)
> p.fac1<-jags.1$BUGSoutput$sims.list$p.fac1
> write.csv(p.fac1, file = "pfac.csv", row.names = FALSE)
> fulldata<-jags.1$BUGSoutput$sims.list
> write.csv(fulldata, file = "fulldata.csv", row.names = FALSE)
> stats <- jags.1$BUGSoutput$summary
> write.csv(stats, file = "stats.csv")
> sims<- jags.1$BUGSoutput$sims.array
> write.csv(sims, file = "sims.csv")
> 
> # Get posterior chains into one tidy data frame
> post.mix_site1 <- as.data.frame(jags.1$BUGSoutput$sims.list$p.global[,1])
> post.mix_site2 <- as.data.frame(jags.1$BUGSoutput$sims.list$p.global[,2])
> post.mix_site3 <- as.data.frame(jags.1$BUGSoutput$sims.list$p.global[,3])
> post.mix_site4 <- as.data.frame(jags.1$BUGSoutput$sims.list$p.global[,4])
> post.mix_site5 <- as.data.frame(jags.1$BUGSoutput$sims.list$p.global[,5])
> post.mix_site6 <- as.data.frame(jags.1$BUGSoutput$sims.list$p.global[,6])
> 
> colnames(post.mix_site1) <- source$source_names[1]
> #Source1<-cbind(Site="Endabash", post.mix_site1)
> #head(Source1)
> 
> colnames(post.mix_site2) <- source$source_names[2]
> #Source2<-cbind(Site="Kirurumo", post.mix_site2)
> 
> colnames(post.mix_site3) <- source$source_names[3]
> #Source3<-cbind(Site="Magara", post.mix_site3)
> 
> colnames(post.mix_site4) <- source$source_names[4]
> #Source4<-cbind(Site="Makuyuni", post.mix_site4)
> 
> colnames(post.mix_site5) <- source$source_names[5]
> #Source5<-cbind(Site="Maole", post.mix_site5)
> 
> colnames(post.mix_site6) <- source$source_names[6]
> #Source6<-cbind(Site="MtoWaMbu", post.mix_site6)
> 
> ###combine all file into one
> site_comp<-cbind(post.mix_site1,post.mix_site2,post.mix_site3,post.mix_site4,post.mix_site5,post.mix_site6)
> head(site_comp)
> write.csv(site_comp,file = "site_comp.csv")
> boxprop_site <- site_comp %>% gather(source,value,1:6)
> 
> ###boxplot
> 
> ggplot(aes(y = value, x = source, fill = source), data = boxprop_site) +
> geom_boxplot(outlier.colour = NA) +
> coord_cartesian(ylim = c(0,1)) +
> theme_classic() +
> xlab("Source") +
> ylab("Proportion of sediment") + ggtitle("Sediment contribution") + theme(plot.title = element_text(hjust = 0.5)) +
> scale_x_discrete(limits=c("DUD","END","MAK","MWM","NGO","TAR"))

Hello MaartenWynants,
Thank you for your detailed response. In fact, it is still a little hard for me to understand the code. R always report an error when I run the code. However, I find a relative easy way to output the data by Matlab. I share the code here for someone like me hard to understand complicated codes.
>> i=imread('XXX.jpg'); 
>>  imshow(i);
>> [x0,y0]= ginput;
>> [x1,y1]= ginput;
>> x1= (x1-min(x0))*120/(max(x0)-min(x0)); y1=(y1-max(y1))*250/(min(y0)-max(y0)); plot(x1,y1);axis([0,120,0,250]);
>> [x1,y1]= ginput;
First thing is to save the plot as .JPG and 'XXX' is the route and the name of the figure.
Then click on the figure to ensure the coordinate origin and the maximum value of X axis and Y axis respectively.
Finally, click on the figure to extract value of the line. More points, more accurate the result is.
The last step is save the data in excel, and draw the figure as your own requirement. (The style, the legend position et al.)
I attach the result here.
![image](https://user-images.githubusercontent.com/55921470/67174291-c222cc00-f37e-11e9-948c-0a6c0aae6b94.png)

Han
haf033@usask.ca

**Comment by HAN-2** [comment]
> Here's some simple code to 1) get the output data from Jags and 2) plot it into a boxplot using ggplot. Note that I use the names of my sources so you'd have to change those.
> 
> #RAW data for make your own graps
> p.global<- jags.1$BUGSoutput$sims.list$p.global
> write.csv(p.global, file = "pglobal.csv", row.names = FALSE)
> p.fac1<-jags.1$BUGSoutput$sims.list$p.fac1
> write.csv(p.fac1, file = "pfac.csv", row.names = FALSE)
> fulldata<-jags.1$BUGSoutput$sims.list
> write.csv(fulldata, file = "fulldata.csv", row.names = FALSE)
> stats <- jags.1$BUGSoutput$summary
> write.csv(stats, file = "stats.csv")
> sims<- jags.1$BUGSoutput$sims.array
> write.csv(sims, file = "sims.csv")
> 
> # Get posterior chains into one tidy data frame
> post.mix_site1 <- as.data.frame(jags.1$BUGSoutput$sims.list$p.global[,1])
> post.mix_site2 <- as.data.frame(jags.1$BUGSoutput$sims.list$p.global[,2])
> post.mix_site3 <- as.data.frame(jags.1$BUGSoutput$sims.list$p.global[,3])
> post.mix_site4 <- as.data.frame(jags.1$BUGSoutput$sims.list$p.global[,4])
> post.mix_site5 <- as.data.frame(jags.1$BUGSoutput$sims.list$p.global[,5])
> post.mix_site6 <- as.data.frame(jags.1$BUGSoutput$sims.list$p.global[,6])
> 
> colnames(post.mix_site1) <- source$source_names[1]
> #Source1<-cbind(Site="Endabash", post.mix_site1)
> #head(Source1)
> 
> colnames(post.mix_site2) <- source$source_names[2]
> #Source2<-cbind(Site="Kirurumo", post.mix_site2)
> 
> colnames(post.mix_site3) <- source$source_names[3]
> #Source3<-cbind(Site="Magara", post.mix_site3)
> 
> colnames(post.mix_site4) <- source$source_names[4]
> #Source4<-cbind(Site="Makuyuni", post.mix_site4)
> 
> colnames(post.mix_site5) <- source$source_names[5]
> #Source5<-cbind(Site="Maole", post.mix_site5)
> 
> colnames(post.mix_site6) <- source$source_names[6]
> #Source6<-cbind(Site="MtoWaMbu", post.mix_site6)
> 
> ###combine all file into one
> site_comp<-cbind(post.mix_site1,post.mix_site2,post.mix_site3,post.mix_site4,post.mix_site5,post.mix_site6)
> head(site_comp)
> write.csv(site_comp,file = "site_comp.csv")
> boxprop_site <- site_comp %>% gather(source,value,1:6)
> 
> ###boxplot
> 
> ggplot(aes(y = value, x = source, fill = source), data = boxprop_site) +
> geom_boxplot(outlier.colour = NA) +
> coord_cartesian(ylim = c(0,1)) +
> theme_classic() +
> xlab("Source") +
> ylab("Proportion of sediment") + ggtitle("Sediment contribution") + theme(plot.title = element_text(hjust = 0.5)) +
> scale_x_discrete(limits=c("DUD","END","MAK","MWM","NGO","TAR"))

Hello MaartenWynants,
Thank you for your detailed response. In fact, it is still a little hard for me to understand the code. R always report an error when I run the code. However, I find a relative easy way to output the data by Matlab. I share the code here for someone like me hard to understand complicated codes.
>> i=imread('XXX.jpg'); 
>>  imshow(i);
>> [x0,y0]= ginput;
>> [x1,y1]= ginput;
>> x1= (x1-min(x0))*120/(max(x0)-min(x0)); y1=(y1-max(y1))*250/(min(y0)-max(y0)); plot(x1,y1);axis([0,120,0,250]);
>> [x1,y1]= ginput;
First thing is to save the plot as .JPG and 'XXX' is the route and the name of the figure.
Then click on the figure to ensure the coordinate origin and the maximum value of X axis and Y axis respectively.
Finally, click on the figure to extract value of the line. More points, more accurate the result is.
The last step is save the data in excel, and draw the figure as your own requirement. (The style, the legend position et al.)
I attach the result here.
![image](https://user-images.githubusercontent.com/55921470/67174291-c222cc00-f37e-11e9-948c-0a6c0aae6b94.png)
Han
haf0333@usask.ca
