### ISSUE TITLE
r-eff argument and pareto-k-diagnostic warning

### ISSUE THREAD

**Issue by JoanGimenez** [brianstock/MixSIAR#187]
When runing "compare_models" function it apperars the following warning message:

Warning messages:
1: Relative effective sample sizes ('r_eff' argument) not specified.
For models fit with MCMC, the reported PSIS effective sample sizes and
MCSE estimates will be over-optimistic.
2: Relative effective sample sizes ('r_eff' argument) not specified.
For models fit with MCMC, the reported PSIS effective sample sizes and
MCSE estimates will be over-optimistic.
3: Some Pareto k diagnostic values are slightly high. See help('pareto-k-diagnostic') for details.

Can someone provide me with some help about this warning (r_eff and pareto-k-diagnostic)?

Thank you.

**Comment by MehdiMoslemi** [comment]
I have the same problem (as below) when using "compare_models" function to compare models

Warning messages:
1: Relative effective sample sizes ('r_eff' argument) not specified.
For models fit with MCMC, the reported PSIS effective sample sizes and 
MCSE estimates will be over-optimistic. 
2: Some Pareto k diagnostic values are slightly high. See help('pareto-k-diagnostic') for details.
 
3: Relative effective sample sizes ('r_eff' argument) not specified.
For models fit with MCMC, the reported PSIS effective sample sizes and 
MCSE estimates will be over-optimistic. 
4: Some Pareto k diagnostic values are slightly high. See help('pareto-k-diagnostic') for details.
 
5: Relative effective sample sizes ('r_eff' argument) not specified.
For models fit with MCMC, the reported PSIS effective sample sizes and 
MCSE estimates will be over-optimistic. 
6: Some Pareto k diagnostic values are too high. See help('pareto-k-diagnostic') for details.

How should I deal with this issue? How I can extract  Pareto k diagnostic values (and 'r_eff' values) to see which ones higher? Please help. Thank you so much.

**Comment by SejerMeyhoff** [comment]
I get the same error when trying to compare my models. However, I think that I might be making inappropriate comparisons. I am trying to compare models that use the same consumer and discrimination data, but different source grouping methods. For example, comparing a model where food items are grouped into 3 separate sources with one that attempts to further split one of those sources resulting in 4 separate sources. 

My compare_models results consistently give all the weight to one model, and 0 to the others. It seems to simply favor models with more sources and models with sources farther apart in the mixing space.

Does it make sense to use the compare_models function in this way?

**Comment by ericward-noaa** [comment]
A couple points:

1. The warnings you're getting aren't a MixSIAR thing, but related to the loo package. See this line:
https://github.com/brianstock/MixSIAR/blob/2b1b2545638fcfaacbcaaa695e2bec436a91806f/R/compare_models.R#L110

2. Aki has a couple guidelines on interpreting these, e.g.
https://discourse.mc-stan.org/t/a-quick-note-what-i-infer-from-p-loo-and-pareto-k-values/3446
