### ISSUE TITLE
Possible bug while plotting data as .png

### ISSUE THREAD

**Issue by VirginiaMorera** [brianstock/MixSIAR#19]
Version: 2.1.2
Using RStudio
Issue: I've been trying to output my data plots as .png, seeing that plotting them as .pdf seems to pull the image from the graphic device, and it makes for a very "crammed" plot. However, while in .pdf the isotopes in the plot are in the correct order, in .png the function confuses the order of the isotopes. Thus, isosapce_plot_1_2.png shows isotpoes 1 and 3 like this: 
![michahellis_isospace_plot_1_2](https://cloud.githubusercontent.com/assets/11058769/6399220/50fcf392-bdf1-11e4-92b9-5f102e60650a.png)

isospace_plot_1_3.png plots isotopes 2 and 3 like this
![michahellis_isospace_plot_1_3](https://cloud.githubusercontent.com/assets/11058769/6399257/86930262-bdf1-11e4-9bce-a86a69f308cb.png)

and isospace_plot_2_3.png plots nothing, just produces a blank square... 

I have tried adding `noRStudioGD = TRUE` in all the `dev.new()`instances in the plot_data.r function, but it doesn't work either. 

Besides, I require svereal `dev.off()`to be able to open my .png files. I am not sure if these are problems with Rstudio or with the code, but as I am using the script version of mixsiar, using RStudio really makes my life easier... 

UPDATE: I have also tried adding `windows()`before every `dev.new()`to force it to open the plots in an independent window, but the problem persists.

**Comment by brianstock** [comment]
Hmm, that is troubling.  Does the same happen if you don't use RStudio?  As I was writing the GUI, RStudio gave me some problems and I recommended to not use it.

Could not be RStudio too, but let's check that first.

**Comment by VirginiaMorera** [comment]
Well, it's RStudio! The plots are fine if plotted directly from the R GUI. Which is... not great to work with the script version, but will do for now! Thank you!
