### ISSUE TITLE
Error in dev.copy2pdf(file = mypath): can only print from a screen device

### ISSUE THREAD

**Issue by AndyLuckert** [brianstock/MixSIAR#194]
When I'm running the example script "mixsiar_script_wolves.R" within the folder
"/usr/local/lib/R/site-library/MixSIAR/example_scripts/" on my Linux Lubuntu 18.04 system,
I get the following error message when reaching the final line of the code where the function "output_JAGS()" is called:

```
dev.new(): using pdf(file="Rplots12.pdf")
Error in dev.copy2pdf(file = mypath) : 
  can only print from a screen device
Calls: output_JAGS -> dev.copy2pdf
Execution halted
```

Googling the error lead me to the following 3 discussions:
https://stackoverflow.com/questions/44816266/r-output-to-screen-error
https://r.789695.n4.nabble.com/how-to-plot-and-save-plots-in-batch-mode-td875505.html
https://stackoverflow.com/questions/21334573/copying-plot-with-type-n-in-r-to-pdf-doesnt-copy-plot-points-only-its-lines-a

The problem with those approaches is though, that I'd have to modifiy the package-module "output_JAGS.R" itself, where the function dev.copy2pdf() is actually called:
https://github.com/brianstock/MixSIAR/blob/master/R/output_JAGS.R

After having searched on my entire system via "find / -type f -iname "output_JAGS.R", I found that this module IS NOT on my system (unlike it'd be the case with Python modules for example, where you can simply open the module-code and implement manual changes). I'm not familiar to R, but it seems like in the case of this package MixSIAR the modules are not downloaded on my harddisk, but rather compiled via gcc+ in some binary format?

However the case might be, I cannot seem to find a way to solve the problem, and I'd appreciate any help.
Thanks in advance!

**My version of R:**
R version 3.6.2 (2019-12-12) -- "Dark and Stormy Night"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

**My system:**
Operating System: Ubuntu 18.04.3 LTS
Kernel: Linux 5.0.0-37-generic
Architecture: x86-64

**Comment by brianstock** [comment]
Hi Andy,

Sorry to hear... I'm surprised you're having issues because I don't get an error using the same versions of R and Ubuntu. Not sure what I can do since I can't replicate the problem.

Idea 1: Modify the script to save plots as png, remove any calls to make pdf files.

Idea 2: Try installing from Github. What version of MixSIAR are you running? Did you install from CRAN or Github?
```
# CRAN
install.packages("MixSIAR", dependencies=TRUE)
# Github
devtools::install_github("brianstock/MixSIAR", build_vignettes = TRUE)
```

Idea 3: Create your own personal version of `output_JAGS.R` on your system. When R installs packages it doesn't copy the raw .R files, it makes a binary like you see. If you want to modify `output_JAGS.R` (or any other MixSIAR function), you can fork MixSIAR on Github, clone a copy to your computer, modify any of the .R scripts, and install/use that version of MixSIAR.

Idea 4: Troubleshoot why it works for me on Ubuntu 18.04.3 but not for you. No ideas here... something with the default pdf device you're using... maybe look up some additional libraries you may need?

**Comment by AndyLuckert** [comment]
Hey Brian,

thanks for your ideas, I've tried out the example script "mixsiar_script_wolves.R", which is shipped with installing the package, in my case under the directory "/usr/local/lib/R/site-library/MixSIAR/example_scripts/".

To answer your questions mentioned in your 2nd idea:

- _How did I install mixSIAR?_ Via the instructions on https://github.com/brianstock/MixSIAR#linux , so it was via CRAN
- _What version of MixSIAR are you running?_ It must be MixSIAR_3.1.10 according to the following procedure: When I start an R-session in my bash-console on Linux Lubuntu 18.04, import the package via library(MixSIAR), the sessionInfo() - function output is:

```
> sessionInfo()
R version 3.6.2 (2019-12-12)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.3 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=de_DE.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=de_DE.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=de_DE.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] MixSIAR_3.1.10

loaded via a namespace (and not attached):
[1] compiler_3.6.2
```

Indeed, the workaround of your 1st idea worked, the initial error mentioned in [my question](https://github.com/brianstock/MixSIAR/issues/194#issue-539782745) doesn't appear anymore.
All I had to do was changing the PDF-plotting-kwargs to FALSE, and the PNG-plot-kwargs to TRUE, just like so:

```
################################################################################
# Process JAGS output

# Choose output options (see ?output_options for details)
output_options <- list(summary_save = TRUE,
                       summary_name = "summary_statistics",
                       sup_post = FALSE,
                       plot_post_save_pdf = FALSE,
                       plot_post_name = "posterior_density",
                       sup_pairs = FALSE,
                       plot_pairs_save_pdf = FALSE,
                       plot_pairs_name = "pairs_plot",
                       sup_xy = TRUE,
                       plot_xy_save_pdf = FALSE,
                       plot_xy_name = "xy_plot",
                       gelman = TRUE,
                       heidel = FALSE,
                       geweke = TRUE,
                       diag_save = TRUE,
                       diag_name = "diagnostics",
                       indiv_effect = FALSE,
                       plot_post_save_png = TRUE,
                       plot_pairs_save_png = TRUE,
                       plot_xy_save_png = FALSE)
```


While this is great, **a new error appeared** later when plotting the Geweke Diagnostic, it seems.
The console output while executing the above-mentioned template-script "mixsiar_script_wolves.R" is:
```
...
Plotting Geweke Diagnostic
Joining, by = c("Parameter", "Chain", "part")
Error in unite(., st.part, part, statistic, sep = ".") : 
  could not find function "unite"
Calls: output_JAGS ... withVisible -> eval -> eval -> _fseq -> freduce -> <Anonymous>
Execution halted
```
I wonder what I can do about this issue.
If you want me to open a new thread apart from this, I'd be no problem.

Thanks in advance for your answer.

**Comment by AndyLuckert** [comment]
I will pose a **new issue on the new error concerning the Geweke Diagnostic** in order to get a better ordering of the problems.
Nonetheless, if you have any further comments on the rest I've written, I'd be glad to hear them.
