### ISSUE TITLE
p.ind and extracting continuous variable output

### ISSUE THREAD

**Issue by ashleystanek** [brianstock/MixSIAR#195]
Hello Dr. Stock and MixSIAR world,
I have been working through MixSIAR with some fish data this fall, however have finally become hung up on a few questions I'd like to resolve before I move forward.  Any advice or references you can suggest would be extremely helpful.

I've attached a figure with examples from two species (of our 10+ total).
Our aim is to estimate the proportion of river suspended pom for each species using covariates of region (2 regions, fixed factor) and length as a continuous factor; I'm running each species separately.  I compared seven models for each species (a null model to various combinations of region, length, and individual).  For these two species, the most informative model only included length.  These models are from a short run and did converge. 

From the BUGSoutput summary, I extracted all of the p.ind[#, 1] rows assuming they reflect the estimated proportion of source 1 (in this case river POM) for each individual.  I then assigned those credible intervals to each fish so I could plot the proportion values outside of MixSIAR.   The scatter plots on the top are those extracted p.ind median by length (with the 2.5 and 97.5 ci as the grey error bars), while the smoothed curves are from output_JAGS.  We were not surprised when in species 2 the points followed the line in the smoothed plot and assumed they are the predicted values given the length of the fish.  However species 1 is super variable around the smoothed line. 

To me, the Species 1 example looks analogous to the alligator example in figure 6 (Stock et al 2018), but perhaps it shouldn't, as it doesn't include individual. 

Is extracting the p.ind reasonable or do we need to stick with the smoothed line?  If the latter, how do I extract those values so I can plot it elsewhere? I've tried to search for examples of this but haven't had much luck. 

Thank you,
Ashley

![Slide1](https://user-images.githubusercontent.com/59071610/71219344-3a1f4c80-2271-11ea-8b8f-43c05281bbf2.JPG)

**Comment by AndrewLJackson** [comment]
hi Ashley

those look about right to me, and I think its ok to plot p.ind like you have done. The fits in the panels on the bottom row seem to match what's above. I would guess that the p.global for species 1 would be more variable than for species 2, and also if you fitted with the residual error term, that it too would be larger for species 1 than species 2 which would reflect this additional uncertainty. The uncertainly shown is for the effect of the linear covariate on the p.ind only.

**Comment by brianstock** [comment]
Yes, you're right. If your model is named `model`, then `model$BUGSoutput$sims.list$p.ind` is indexed as `MCMCdraw` x `individual` x `source` and `model$BUGSoutput$sims.list$p.ind[,i,1]` gives all the MCMC draws for individual `i` for source `1`. This should be accessible whether or not you've included Individual in the model. However, I am surprised by the top left plot - for a model without an effect of Individual, the mean `p.ind` proportions should line on a smooth curve as in the top right. For my sanity, can you please confirm that that plot isn't from a model with Individual as a fixed/random effect? What version of MixSIAR are you using, and what error structure? Old versions had a checkbox to "Include individual as random effect" and then we removed it.

In `plot_continuous_var.R`, we get a smooth curve by 
  1. generate a vector Length
  2. calculate `p(Length) = inverse.ILR(ilr.global + ilr.cont1*Length)` for each MCMC draw, then 
  3. plot the median (line), and 2.5% + 97.5% (shading) of `p` for each Length.
And in the JAGS model, `p.ind[i] = inverse.ILR(ilr.global + ilr.cont1*Length[i])`. So if you plot the 95% CI of the `p.ind`s in a model with only Length, they should match the CI width in the continuous effect plot (looks right for Species 2).

Thanks,
Brian

**Comment by ashleystanek** [comment]
Thank you very much for help in trying to sort this out!  Upon trying to answer your questions, I realized that none of the issues had to do with MixSIAR - the problem turned out to be that when I was assigning the ID to each row of the output, the IDs were in a different order than went into the mixture.  I've now figured out how to pull the IDs from the mixture, and when they are assigned correctly there is no scatter around the curves and everything looks like Species 2. 

I think everything is set up and running correctly, but in response to your questions:
-The sd for p.global was similar for both species (.05 and .06).
-Error: I set residual to true for models that don't include individual, and false for models that do include individuals.  I thought I read somewhere that it needed to be false for individuals, but can't seem to find it again. Is that correct and is it okay to compare models that have different error structure?  Process is true for everything. 
-I'm running the script version of MixSIAR, package is version 3.1.10. 

Ashley

**Comment by brianstock** [comment]
Great! Glad I'm not losing it...

Yes, you can compare models with different error structures using LOO/WAIC/DIC. And yes, if you're including diet p deviations for each data point, it is probably best to not also include the additional/residual error term.
