### ISSUE TITLE
Error in unite(., st.part, part, statistic, sep = ".") : could not find function "unite" (while plotting Geweke Diagnostic)

### ISSUE THREAD

**Issue by AndyLuckert** [brianstock/MixSIAR#197]
During the process described in [the other issue](https://github.com/brianstock/MixSIAR/issues/194#issuecomment-572156825), while executing the mentioned template-script "mixsiar_script_wolves.R", the console output, when plotting the Geweke Diagnostic, throws the following error:
```
...
Plotting Geweke Diagnostic
Joining, by = c("Parameter", "Chain", "part")
Error in unite(., st.part, part, statistic, sep = ".") : 
  could not find function "unite"
Calls: output_JAGS ... withVisible -> eval -> eval -> _fseq -> freduce -> <Anonymous>
Execution halted
```

So far, I have no idea where to start in order to solve this.
Thanks in advance for your comments.

**Comment by HsinHuiWang** [comment]
You need to install package "tidyr"

**Comment by AndyLuckert** [comment]
Alright HsinHuiWang, thanks for your help!
