### ISSUE TITLE
Error in combined function (incorrectly combines posterior densities)

### ISSUE THREAD

**Issue by lutch006** [brianstock/MixSIAR#199]
I am new to mixSIAR and R so forgive me if this is an error on my part but I am trying to combine sources after running my mixing model. While there is no error in actually obtaining the data when running the combine_sources function, one specific organism for  one models gets erroneous results returned (ie. the means do not even add up to 1). Oddly it is the only organism with this error for this model and the other organisms do not have this issue. If any one could help me out or point me in the right direction that would be greatly appreciated as I have been stumped for a while! I also attached the Isoplot for reference.

The weird data from each model and an organism from the same model in which the sources were combined successfully:

Model 1
error organism original
p.Baetidae.Coontail         0.156 0.026 0.105 0.113 0.139 0.156 0.172 0.199 0.208
p.Baetidae.CPOM             0.207 0.050 0.112 0.127 0.172 0.205 0.240 0.291 0.309
p.Baetidae.Duckweed         0.045 0.035 0.002 0.004 0.018 0.037 0.063 0.114 0.132
p.Baetidae.Fil algae        0.593 0.054 0.482 0.502 0.559 0.595 0.630 0.679 0.694

error organism combined (Autochthonous: Coontial+Duckweed+Fil algae)
p.Autochthonous.Baetidae        0.513 0.092 0.347 0.446 0.511 0.576 0.699
p.CPOM.Baetidae                 0.140 0.029 0.086 0.120 0.139 0.158 0.199

Original 
p.Calopterygidae.Coontail   0.033 0.019 0.006 0.008 0.018 0.030 0.044 0.068 0.077
p.Calopterygidae.CPOM       0.094 0.058 0.010 0.015 0.047 0.084 0.131 0.201 0.224
p.Calopterygidae.Duckweed   0.039 0.047 0.000 0.001 0.006 0.020 0.055 0.141 0.171
p.Calopterygidae.Fil algae  0.835 0.073 0.672 0.704 0.787 0.841 0.890 0.943 0.957

combined
p.Autochthonous.Calopterygidae  0.906 0.058 0.776 0.869 0.916 0.953 0.990
p.CPOM.Calopterygidae           0.094 0.058 0.010 0.047 0.084 0.131 0.224

![NIOLC5_Isoplot_Fil_algae](https://user-images.githubusercontent.com/59971307/72546527-85b51e00-3850-11ea-9239-d65b102ffafb.png)

**Comment by brianstock** [comment]
Hmm, sorry, not sure how we can help without going through your data and code. That `combine_sources` works for all but one of your consumer groups makes me suspect an error on your part somewhere in the post-processing... sorry that is really not helpful!

You're right, the means should add to 1 before aggregating and after aggregating. See https://github.com/brianstock/MixSIAR/issues/181.

**Comment by lutch006** [comment]
Here is the post processing code:

output_JAGS(jags.1, mix, source, output_options)
save.image(file = "NIOLC5_extreme_hylella.RData")
combined <- combine_sources(jags.1, mix, source, alpha.prior=1,
                             groups=list(Autochthonous=c("Coontail","Duckweed","Fil algae"),
                                           CPOM=c("CPOM")))

original <- combine_sources(jags.1, mix, source, alpha.prior=1,
                            groups=list(Coontail="Coontail",CPOM="CPOM", Duckweed="Duckweed",Filalgae="Fil algae"))

Everything turns out fine up until this point. Even when I call summary_stat (original) the data for that organism gets changed:

                            Mean    SD  2.5%   25%   50%   75% 97.5%
p.CPOM.Baetidae            0.043 0.030 0.006 0.020 0.035 0.057 0.122
p.Duckweed.Baetidae        0.134 0.028 0.081 0.115 0.133 0.151 0.194
p.Coontail.Baetidae        0.151 0.024 0.102 0.134 0.151 0.167 0.200
p.Filalgae.Baetidae        0.212 0.048 0.120 0.179 0.211 0.244 0.307

I am not sure if I can manually combine the posterior distributions to get the same summary data for that one consumer but I cant seem to find any error with my code!

Thanks for the previously quick reply!

**Comment by ericward-noaa** [comment]
Sorry - I don't think this is a reproducible example. Can you attach all the data files or model output that the file includes? Or can you create an example with @brianstock 's mantis script, which calls that file?

**Comment by lutch006** [comment]
Here are the data! 




[mixSIAR_NIOLC5_Consumers_example.xlsx](https://github.com/brianstock/MixSIAR/files/4100148/mixSIAR_NIOLC5_Consumers_example.xlsx)
[mixSIAR_NIOLC5_Sources_example.xlsx](https://github.com/brianstock/MixSIAR/files/4100153/mixSIAR_NIOLC5_Sources_example.xlsx)
[mixSIAR_NIOLC5_TEF_example.xlsx](https://github.com/brianstock/MixSIAR/files/4100154/mixSIAR_NIOLC5_TEF_example.xlsx)

**Comment by brianstock** [comment]
Can you please post a script that uses those data files and produces the error? You can use the `test` MCMC run length, no need to worry about convergence.

**Comment by lutch006** [comment]
Here is the script! Sorry I should have included that with the data that I posted. I just put all of the script that I used on here and I hope that I didnt include unecessary script. Thank you for taking a look at it! 

library(MixSIAR)
library("plotly")
library(RColorBrewer)
mix.filename <- system.file("NIOLC5", "mixSIAR_NIOLC5_Consumers.csv", package = "MixSIAR")
mix <- load_mix_data(filename=mix.filename, 
                     iso_names=c("d13C","d15N"), 
                     factors=c("family"), 
                     fac_random=c(FALSE), 
                     fac_nested=c(FALSE), 
                     cont_effects=NULL)
source.filename <- system.file("NIOLC5", "mixSIAR_NIOLC5_Sources.csv", package = "MixSIAR")
source <- load_source_data(filename=source.filename, source_factors=NULL, 
                           conc_dep=F, data_type="raw", mix)
discr.filename <- system.file("NIOLC5", "mixSIAR_NIOLC5_TEF.csv", package = "MixSIAR")
discr <- load_discr_data(filename=discr.filename, mix)
plot_data(filename="isospace_plot_NIOLC5", 
          plot_save_pdf=TRUE,
          plot_save_png=FALSE,
          mix,source,discr)
if(mix$n.iso==2) calc_area(source=source,mix=mix,discr=discr)
plot_prior(alpha.prior=1,source)
model_filename <- "MixSIAR_model_NIOLC5.txt"
resid_err <- TRUE
process_err <- FALSE
write_JAGS_model(model_filename, resid_err, process_err, mix, source)
jags.1 <- run_model(run="test", mix, source, discr, model_filename, 
                    alpha.prior = 1, resid_err, process_err)
output_options <- list(summary_save = TRUE,                 
                       summary_name = "summary_statistics", 
                       sup_post = FALSE,                    
                       plot_post_save_pdf = TRUE,           
                       plot_post_name = "posterior_density",
                       sup_pairs = FALSE,             
                       plot_pairs_save_pdf = TRUE,    
                       plot_pairs_name = "pairs_plot",
                       sup_xy = FALSE,           
                       plot_xy_save_pdf = TRUE,
                       plot_xy_name = "xy_plot",
                       gelman = TRUE,
                       heidel = FALSE,  
                       geweke = TRUE,
                       diag_save = TRUE,
                       diag_name = "diagnostics",
                       indiv_effect = FALSE,       
                       plot_post_save_png = FALSE, 
                       plot_pairs_save_png = FALSE,
                       plot_xy_save_png = FALSE)

# Create diagnostics, summary statistics, and posterior plots
output_JAGS(jags.1, mix, source, output_options)
save.image(file = "NIOLC5_extreme_hylella.RData")
combined <- combine_sources(jags.1, mix, source, alpha.prior=1,
                             groups=list(Autochthonous=c("Coontail","Duckweed","Fil algae"),
                                           CPOM=c("CPOM")))
original <- combine_sources(jags.1, mix, source, alpha.prior=1,
                            groups=list(Coontail="Coontail",CPOM="CPOM", Duckweed="Duckweed",Filalgae="Fil algae"))
summary_stat(original)
summary_stat(combined)

**Comment by ericward-noaa** [comment]
The names of the data files you attached don't match the names in the script

**Comment by lutch006** [comment]
Thanks for pointing that out... I updated it, and sorry for making this super difficult...

**Comment by ericward-noaa** [comment]
@lutch006 maybe I'm missing something, but I don't see updates. For example, the line 

mix.filename <- system.file("NIOLC5", "mixSIAR_NIOLC5_Consumers_example.csv", package = "MixSIAR")

has a .csv file, but you gave us xlsx files with different names. There's several other instances throughout

**Comment by lutch006** [comment]
@ericward-noaa I did upload excel files because I was not able to upload csv files, the file type is not supported. I think the names should match the xlsx files, however if you are not able to convert the files to csv I can try to figure out a way to convert them to a supported file type and try to upload that and update the script. Once again sorry for all of the confusion!

**Comment by ericward-noaa** [comment]
@lutch006 , I can't replicate that there's actually any problem here. I just added a bit of code at the beginning of your script to read the xlsx files. But the tables for the function combine_sources all seem to work ok.

In your initial note- I also saw that the estimates are listed as p.Baetidae.CPOM, rather than how they're labeled in your later messages (p.CPOM.Baetidate). Maybe that's the source of the error? 

#######################################################################

library(MixSIAR)
library(RColorBrewer)
  
  write.table(readxl::read_xlsx("mixSIAR_NIOLC5_Consumers_example.xlsx"),
    file="mixSIAR_NIOLC5_Consumers_example.csv",row.names = FALSE,sep=",")
  write.table(readxl::read_xlsx("mixSIAR_NIOLC5_Sources_example.xlsx"),
    file="mixSIAR_NIOLC5_Sources_example.csv",row.names = FALSE,sep=",")
  write.table(readxl::read_xlsx("mixSIAR_NIOLC5_TEF_example.xlsx"),
    file="mixSIAR_NIOLC5_TEF_example.csv",row.names = FALSE,sep=",")
  
  mix.filename <-
    system.file("NIOLC5", "mixSIAR_NIOLC5_Consumers_example.csv", package = "MixSIAR")
  mix <-
    load_mix_data(
      "mixSIAR_NIOLC5_Consumers_example.csv",
      iso_names = c("d13C", "d15N"),
      factors = c("family"),
      fac_random = c(FALSE),
      fac_nested = c(FALSE),
      cont_effects = NULL
    )
  source.filename <-
    system.file("NIOLC5", "mixSIAR_NIOLC5_Sources_example.csv", package = "MixSIAR")
  source <-
    load_source_data(
      "mixSIAR_NIOLC5_Sources_example.csv",
      source_factors = NULL,
      conc_dep = F,
      data_type = "raw",
      mix
    )
  
  discr.filename <-
    system.file("NIOLC5", "mixSIAR_NIOLC5_TEF_example.csv", package = "MixSIAR")
  discr <- load_discr_data("mixSIAR_NIOLC5_TEF_example.csv", mix)
  
  plot_data(
    filename = "isospace_plot_NIOLC5",
    plot_save_pdf = TRUE,
    plot_save_png = FALSE,
    mix,
    source,
    discr
  )
  if (mix$n.iso == 2)
    calc_area(source = source,
      mix = mix,
      discr = discr)
  plot_prior(alpha.prior = 1, source)
  model_filename = "MixSIAR_model_NIOLC5.txt"
  resid_err <-TRUE
  process_err <-FALSE
  write_JAGS_model(model_filename, resid_err, process_err, mix, source)
  jags.1 <-
    run_model(
      run = "test",
      mix,
      source,
      discr,
      model_filename,
      alpha.prior = 1,
      resid_err,
      process_err
    )
  output_options <- list(
    summary_save = TRUE,
    summary_name = "summary_statistics",
    sup_post = FALSE,
    plot_post_save_pdf = TRUE,
    plot_post_name = "posterior_density",
    sup_pairs = FALSE,
    plot_pairs_save_pdf = TRUE,
    plot_pairs_name = "pairs_plot",
    sup_xy = FALSE,
    plot_xy_save_pdf = TRUE,
    plot_xy_name = "xy_plot",
    gelman = TRUE,
    heidel = FALSE,
    geweke = TRUE,
    diag_save = TRUE,
    diag_name = "diagnostics",
    indiv_effect = FALSE,
    plot_post_save_png = FALSE,
    plot_pairs_save_png = FALSE,
    plot_xy_save_png = FALSE
  )
  
  output_JAGS(jags.1, mix, source, output_options)
  save.image(file = "NIOLC5_extreme_hylella.RData")
  
  combined <- combine_sources(
    jags.1,
    mix,
    source,
    alpha.prior = 1,
    groups = list(
      Autochthonous = c("Coontail", "Duckweed", "Fil algae"),
      CPOM = c("CPOM")
    )
  )
  original <- combine_sources(
    jags.1,
    mix,
    source,
    alpha.prior = 1,
    groups = list(
      Coontail = "Coontail",
      CPOM = "CPOM",
      Duckweed = "Duckweed",
      Filalgae = "Fil algae"
    )
  )
  
  summary_stat(original)
  summary_stat(combined)

**Comment by lutch006** [comment]
Intresting. Well I am glad that you were finally able to run the code to check for me. I will go back through my code to see what went wrong on my end. Thanks for taking the time to look at it for me!

**Comment by lutch006** [comment]
@ericward-noaa Just to be clear the Baetidae data when combined came out correctly for you? I did try again and I had the same error.

**Comment by ericward-noaa** [comment]
@lutch006 I thought it had, but when looking this am, saw it wasn't still combining Baetidae correctly. I dug into the combine_sources script, and think the issue's fixed now after testing it with your data. Try reinstalling MixSIAR from Github and give it another shot.

**Comment by lutch006** [comment]
@ericward-noaa  I copied the new combined_sources script into my work space and then ran the function and it WORKED! Thank you so much for taking the time out to help me with this issue. I really appreciate it and I can stop pulling my hair out now.
