### ISSUE TITLE
changing order of sources

### ISSUE THREAD

**Issue by VirginiaMorera** [brianstock/MixSIAR#20]
Version: 2.1.2
This issue is related to #15 

Issue: I've come to realise that in the `source` list that MixSIAR creates, the sources are ordered alphabetically, regardless of what order they where in the original data. Does that mean that, when using alpha parameters as priors, I have to enter the proportions of the sources in the alphabetical order, or in the order the original data was (were?)?  

To clarify: my sources.csv had the sources ordered like this: 1Marine, 2Freshwater, 3Terrestrial, 4Refuse, but `source$sourcenames[1]` returns `Freshwater`, `source$sourcenames[2]` returns `Marine`, and so on. 

My question is, how do I order the alpha parameters in the model 
`run_model(... ..., alpha.prior = alpha.parameters)`?

Thank you!

**Comment by VirginiaMorera** [comment]
Hi again! I've sort of figured something out. When using MixSIAR's normal output (posterior denisty plots and summary .txt file) the source names match the correct posterior distributions (phew!). But I extracted the posteriors with
```R 
attach.jags(jags.1)
rpd.global <- p.global
rpd.global <- as.data.frame(rpd.global)
```

and it produced a data frame with as many rows as draws my model retained (as expected) and four columns, for the four sources  included in my model. 

When comparing these four columns with the results from the summary .txt file, turns out that the values in the first column, (named V1 automatically by R as it comes from an array without row names) do not correspond with the values of my first source as I entered them in the Sources file (Marine, if you check the previous message), but to the first source _alphabetically!_ (Freshwater).

This might be clear-cut from the model to more R-savvy people than me, but I thought it was worth clarifying in case someone else got confused. 

All this leaves me with more doubts still about what to do with the priors. Do I enter them in alphabetical order, or in the same order as my sources?

Even though this has a very obvious solution, i.e. sorting the sources in the source file alphabetically, I think it's worth having a look at!

**Comment by brianstock** [comment]
Yes, MixSIAR sorts the sources alphabetically to create the `source` list. Then that is passed to JAGS in the `run_model` function, so the sources are sorted in all output.

Yes, you should order the source alpha parameters alphabetically.

Thanks for the questions with clear examples.  I don't remember if I sorted the sources for a specific reason or not... sorry for the confusion!  Will add a note to the manual when I revise it.

**Comment by VirginiaMorera** [comment]
That's ok, it's easy enough to avoid. Thanks for the response!
