### ISSUE TITLE
Should I choose fixed effect or random effect?

### ISSUE THREAD

**Issue by tumojiyi** [brianstock/MixSIAR#203]
Hello, I used the two isotopic tracers: 15N and 18O to study the source of nitrate in surface water. At present, I have identified four typical sources and collected 16 consumers (i.e. surface water samples)in a river. When using the mixsiar GUI, I solve the contribution of different sources relative to each consumer sample, that is, each consumer in the consumer.csv file as a separate group, a total of 16 groups. The following problems exist:
1. If there are only three groups and each group has six consumers,They come from the same river. Should I choose fixed effect or random effect? If there are 16 groups and each group has only one consumer, how to choose?

2. Because there are 16 groups, what are the problems caused by too many groups?

**Comment by brianstock** [comment]
Hello,

This isn't specific to MixSIAR, it's a more general modeling decision. The main question is whether you want your mix/consumer proportion estimates to share information, and what level your research question is at. Are you primarily interested in the proportions 1) at each site? 2) for each river? 3) just the mean across all sites? Should the proportions for each river be related or independent?

The natural models for 1-3 would be: 1) fixed effect of site/ID, 2) fixed or random effect of river, 3) no effects (just overall mean). If you want the river proportions to be independent, choose a fixed effect. Random effects shrink the estimates toward the mean.

No problem with 16 groups.

Lots of smart people have written about this decision:
https://bbolker.github.io/mixedmodels-misc/glmmFAQ.html#should-i-treat-factor-xxx-as-fixed-or-random
https://stats.stackexchange.com/questions/4700/what-is-the-difference-between-fixed-effect-random-effect-and-mixed-effect-mode
https://www.meta-analysis.com/downloads/Meta-analysis%20Fixed-effect%20vs%20Random-effects%20models.pdf
https://dynamicecology.wordpress.com/2015/11/04/is-it-a-fixed-or-random-effect/
