### ISSUE TITLE
Failure to calculate log density

### ISSUE THREAD

**Issue by KristenBeattie** [brianstock/MixSIAR#206]
Hi all, 

I am getting the following error message when I am running models with a fixed and continuous effects , I was wondering if anyone else came across this error and how they fixed it. Thank you. 

Error in update.jags(object, n.iter, ...) : Error in node X_iso[28,1:2]
Failure to calculate log density

**Comment by LiamGREGOIRE** [comment]
Hi Kristen, I know this was a long time ago but do you remember how you fixed this error ?
