### ISSUE TITLE
New (to me) MixSIAR error disrupts loop

### ISSUE THREAD

**Issue by bkhobart** [brianstock/MixSIAR#207]
Hi Brian,

MixSIAR is throwing an error (pasted below) when I run a loop adapted from the alligator example. I've run variants of this loop dozens of times for several different datasets, and have never encountered the current error. In fact, the present analysis is identical to a previous one, but the data in the 'consumer' input have just been subsetted (from 41 to 24 observations) for a revision. 

Consistently, the error code is *not* thrown for the first model in the loop -- a null model (no factors or continuous effects) -- but is thrown for the second model, which incorporates a continuous effect. The error appears to occur in the post-run processing, and to me looks like it has to do with the "df" object that contains the back-transformed Pr-scale data. Past that, I've been unable to diagnose what's causing the error (I've run on different machines; run the model outside of the loop -- it still throws the code; tested older code to make sure it runs -- it does; etc.).

Happy to send code & data via email (data are somewhat sensitive and so not public yet).

**Error**: 

`Error in df$x[seq(1 + n.draws * (src - 1), src * n.draws)] <- as.matrix(p.ind[,  : 
  replacement has length zero`
`In addition: Warning messages:`
`1: In df$x[seq(1 + n.draws * (src - 1), src * n.draws)] <- as.matrix(p.ind[,  :
  number of items to replace is not a multiple of replacement length`
`2: In df$x[seq(1 + n.draws * (src - 1), src * n.draws)] <- as.matrix(p.ind[,  :
  number of items to replace is not a multiple of replacement length`
`3: In max(sort(cont[which(cont < median(cont))])) :
  no non-missing arguments to max; returning -Inf`

Many thanks Brian, any help will be enormously helpful in getting an ms out the door!

Cheers, Brendan

**Comment by brianstock** [comment]
Perhaps too simple - looking at the first warning, can you confirm there are no missing values for the continuous effect variable?

Sorry about the error... Yeah, probably fastest to send me the code and data via email: bstock09@gmail.com.

**Comment by bkhobart** [comment]
Just checked and the continuous effect variable is complete (still, a simple start is usually best).

I'll send the code & data your way! Thanks a ton, and no worries about the error. Minor inconvenience at worst, learning opportunity at best.

**Comment by brianstock** [comment]
Hi Brandon,

This bug should be fixed now. I won't push to CRAN for minor things like this, so install the GitHub version:
```
devtools::install_github("brianstock/MixSIAR",
                         dependencies = TRUE, 
                         build_vignettes = TRUE) # FALSE if no pandoc and pandoc-citeproc
```

Weird bug. The problem was that your continuous variable had both an even # of values AND so many repeated values that the median was equal to the min. So when `plot_continuous_var` tried to find the individual just lower than the median, there was no such individual. This explains why you didn't have any issue when n = 41 (since it's easy to pick out the median individual with an odd #), but did when n = 24.
