### ISSUE TITLE
plot_prior() not reading in prior vector?

### ISSUE THREAD

**Issue by atchin** [brianstock/MixSIAR#208]
Hi Brian,

I'm running through your Palmyra script as a reference for my own research, and I ran into a problem with the plot_prior() command:

```
> prior.vec <- rep((1/3), 3)
> plot_prior(alpha.prior=prior.vec,source)
Error in rbind(info, getNamespaceInfo(env, "S3methods")) :
  number of columns of matrices must match (see arg 2)
```

I haven't modified anything from the source csv that was in the extdata folder. Any advice? Do the columns need to be named? Thanks for any help.

Best,
Andrew

**Comment by brianstock** [comment]
Hi Andrew,

Not sure what your problem is... when I change the prior in the Palmyra example using your code above, there's no error:

![palmyra_ex_change_alpha](https://user-images.githubusercontent.com/5124211/75071619-b9283f80-54c3-11ea-9277-9072e4be6d82.png)

**Comment by atchin** [comment]
Hi Brian,

I tried re-installing MixSIAR and updating all my packages and running it through again..I'm still getting the same error. Is there a package that runs the prior that I might be missing? I'm updating all my packages and I'm still unsure.

**Comment by atchin** [comment]
Hi Brian,

I resolved the issue. Turns out I just needed the new version of R. Thanks for your help!
