### ISSUE TITLE
Large dataset - model convergence criteria?

### ISSUE THREAD

**Issue by amulcan** [brianstock/MixSIAR#210]
Hello, 

I have been running MixSIAR to assess potential Pb sources in my study area sediments. I have 3 tracers, 6 sources, 59+ samples/mixtures, and no discrimination factors (trophic discrimination factors are not applicable for this study). I ran the model with the "extreme" MCMC run length, and it takes about 24-48 hours. I think my model has converged but I'm not 100% sure. The Gelman-Rubin diagnostic looks great, however the number of variables that fall outside +/- 1.96 for each chain is relatively high (see attached). The file says that for Geweke diagnostic "we'd expect 5% (of variables) to be outside +/- 1.96". 
In my case, the diagnostic file says I have 716 variables. With this in mind Chain 1 has 33 variables outside of +/- 1.96 which is ~5%, Chain 2 has 12 variables outside of +/- 1.96 which is ~2%, and Chain 3 has 16 variables outside of +/- 1.96 which is ~2%. All chains are at or below 5% outside +/- 1.96. Does this mean that my model is converged?

I appreciate any help! Thanks in advance!
Mandy

<img width="388" alt="Gelman-Rubin" src="https://user-images.githubusercontent.com/62476295/77230733-4c58a180-6b64-11ea-8e33-f5467a810f3d.png">
<img width="415" alt="Geweke" src="https://user-images.githubusercontent.com/62476295/77230734-4e226500-6b64-11ea-9644-6b1d028ac3f3.png">

**Comment by brianstock** [comment]
Yes, your model is very converged. All Gelman-Rubin Rhats are below 1.01, and less than 5% of the Geweke diagnostics are outside +/-1.96. You can probably run shorter MCMC chains.
