### ISSUE TITLE
Error loading data-Error in read.table(file=file...

### ISSUE THREAD

**Issue by GMowat** [brianstock/MixSIAR#211]
Hello,
I am trying to get this simple data to load into MixSIAR but I keep getting this error:

Error in read.table(file=file, header = header...
In file(file, "rt") : file only supports open = 'w+' and open = "w+b": using the former

Perhaps most informative is when I run the first line of code to assign the new file it creates an object in my R environment window but the description is just "" but when I run one of the scripts that comes with the package there is always a folder address pointed to in that window.

I have pasted the code and data below. Could someone try to run them for me to see if it is something with my computer? I am pretty sure I have the format correct. I can email the data and code too.
Thanks  Garth

##Load mixture data into MixSIAR
mix.filename <- system.file("extdata", "2Cations_6predators.csv", package = "MixSIAR")
mix <- load_mix_data(filename=mix.filename,
                     iso_names=c("Sr87.Sr86","Cs133.Ca"),
                     factors="Species",
                     fac_random=FALSE,
                     fac_nested=FALSE,
                     cont_effects=NULL)

Species,Sr87.Sr86,Cs133.Ca
Wolf1,2.61,2.44
Wolf2,4.04,2.2
Wolf3,4.41,1.61
Wolf4,1.56,13.39
Cougar1,10.62,10.29
Cougar2,8.49,4.12

**Comment by icer182** [comment]
I am getting the same error when trying to run my own data.  Have you been able to figure out the solution to this problem yet? I even placed my .csv files inside of the extdata file to see if that would fix things. It hasn't yet.

**Comment by icer182** [comment]
Hi @GMowat! You can fix this error by editing the mix.filename line to read mix.filename <- "2Cations_6predators.csv"

**Comment by GMowat** [comment]
Thanks, I did figure this out but was not able to remove my posting.

cheers

[https://gww.nrs.gov.bc.ca/flnrord/files/flnrord/media/internal_communications/new_logo_sig_block_1.png]

Garth Mowat PhD, PAg
Provincial Large Carnivore Specialist
Wildlife & Habitat Branch | Ministry of Forests, Lands, Natural Resource Operations & Rural Development

Office: 250-354-6142
Email: garth.mowat@gov.bc.ca<mailto:garth.mowat@gov.bc.ca>
[Image result for british columbia logo]<https://www2.gov.bc.ca/gov/content/environment/research-monitoring-reporting/research>   [cid:image003.jpg@01D62238.D97A9250] <https://www.researchgate.net/profile/Garth_Mowat>    [cid:image004.jpg@01D62238.D97A9250] <https://scholar.google.ca/citations?user=k4SXghUAAAAJ&hl=en>
