### ISSUE TITLE
MixSiar_continuous_effect

### ISSUE THREAD

**Issue by LloretElena** [brianstock/MixSIAR#212]
Hello,

We are running a model with a continuous effect (length in centimeters) with the process error set as FALSE, as recommended for this type of models. 
Credible intervals seem not to be well placed in the plot when we are using the output_JAGS function, neither when we use an adapted version of the alligator code example to plot the continuous effect. 
It seems that the problem is when transforming from ILR-space to p-space, as credible intervals in the summary statistics are correct. 
Also we are not sure if it could be due to the following warning that we have when running the model:
![warning message](https://user-images.githubusercontent.com/62697234/77925044-b11ea500-72a4-11ea-8d26-55cbd232c7da.jpeg)

 
We attached here the isoplot and posterior diet proportion graph (for the model run in “extreme”) as well as, the part of the code for plotting.

![isospace_cluster5_](https://user-images.githubusercontent.com/62697234/77925979-d52eb600-72a5-11ea-853b-b3ec0438b874.PNG)

 
![model_length_extreme](https://user-images.githubusercontent.com/62697234/77925560-491c8e80-72a5-11ea-8534-0f26740ac291.png)

Thank you very much for you time and help!
Elena

We also attach here the part of the code used for plotting:
**Plot proportions vs. length** 
R2jags::attach.jags(jags.1)
ce=1
label <- mix$cont_effects[ce]
cont <- mix$CE[[ce]]
n.sources <- source$n.sources
source_names <- source$source_names
get_high <- function(x){return(quantile(x,.975))}
get_low <- function(x){return(quantile(x,.025))}
n.plot = 200
chain.len = dim(p.global)[1]

Cont1.plot <- seq(from=round(min(cont),1), to=round(max(cont),1), length.out=n.plot)
ilr.plot <- array(NA,dim=c(n.plot, n.sources-1, chain.len))
ilr.median <- array(NA,dim=c(n.plot, n.sources-1))
ilr.low <- array(NA,dim=c(n.plot, n.sources-1))
ilr.high <- array(NA,dim=c(n.plot, n.sources-1))
for(src in 1:n.sources-1){
  for(i in 1:n.plot){
    ilr.plot[i,src,] <- ilr.global[,src] + ilr.cont1[,src]*Cont1.plot[i]
    ilr.low[i,src] <- get_low(ilr.plot[i,src,])
    ilr.median[i,src] <- median(ilr.plot[i,src,])
    ilr.high[i,src] <- get_high(ilr.plot[i,src,])
  }
}

**Transform regression lines from ILR-space to p-space**
e <- matrix(rep(0,n.sources*(n.sources-1)),nrow=n.sources,ncol=(n.sources-1))
for(i in 1:(n.sources-1)){
  e[,i] <- exp(c(rep(sqrt(1/(i*(i+1))),i),-sqrt(i/(i+1)),rep(0,n.sources-i-1)))
  e[,i] <- e[,i]/sum(e[,i])
}
cross.med <- array(data=NA,dim=c(n.plot, n.sources, n.sources-1))  
tmp.p.med <- array(data=NA,dim=c(n.plot, n.sources))              
p.median <- array(data=NA,dim=c(n.plot, n.sources))
cross.low <- array(data=NA,dim=c(n.plot, n.sources, n.sources-1))

tmp.p.low <- array(data=NA,dim=c(n.plot, n.sources))            
p.low <- array(data=NA,dim=c(n.plot, n.sources))
cross.high <- array(data=NA,dim=c(n.plot, n.sources, n.sources-1))  
tmp.p.high <- array(data=NA,dim=c(n.plot, n.sources))            
p.high <- array(data=NA,dim=c(n.plot, n.sources))
eps.low <- rep(NA, n.plot)
eps.med <- rep(NA, n.plot)
eps.high <- rep(NA, n.plot)    
for(i in 1:n.plot){
  for(j in 1:(n.sources-1)){
    cross.med[i,,j] <- (e[,j]^ilr.median[i,j])/sum(e[,j]^ilr.median[i,j]);
    cross.low[i,,j] <- (e[,j]^ilr.low[i,j])/sum(e[,j]^ilr.low[i,j]);
    cross.high[i,,j] <- (e[,j]^ilr.high[i,j])/sum(e[,j]^ilr.high[i,j]);
  }
  for(src in 1:n.sources){
    tmp.p.med[i,src] <- prod(cross.med[i,src,]);
    tmp.p.low[i,src] <- prod(cross.low[i,src,]);
    tmp.p.high[i,src] <- prod(cross.high[i,src,]);
  }
  for(src in 1:n.sources){
    p.median[i,src] <- tmp.p.med[i,src]/sum(tmp.p.med[i,]);
    p.low[i,src] <- tmp.p.low[i,src]/sum(tmp.p.low[i,]);
    p.high[i,src] <- tmp.p.high[i,src]/sum(tmp.p.high[i,]);
  }
 }
colnames(p.median) <- source_names
source_names<-as.factor(source_names)

Cont1.plot <- Cont1.plot*mix$CE_scale + mix$CE_center 
df <- data.frame(reshape2::melt(p.median)[,2:3], rep(Cont1.plot,n.sources), reshape2::melt(p.low)[,3], reshape2::melt(p.high)[,3])

colnames(df) <- c("source","median","x","low","high")
df$source<-as.factor(df$source)

 **Plot of Diet vs. Cont effect**
png("model_length_long_", height=7, width=7, units='in', res=500)
print(ggplot2::ggplot(data=df,ggplot2::aes(x=x,y=median)) +
        ggplot2::geom_line(ggplot2::aes(x=x, y=median,group=source,colour=source),size=1.5) +
        ggplot2::geom_ribbon(ggplot2::aes(ymin=high, ymax=low, group=source, fill=source), alpha=0.35) +
        ggplot2::ylab("Diet proportion") +
        ggplot2::xlab("Total length (cm)") +
        ggplot2::scale_y_continuous(expand = c(0, 0), limits=c(0,1)) +
        ggplot2::theme_bw() +
        ggplot2::theme(panel.border = ggplot2::element_blank(), panel.grid.major = ggplot2::element_blank(), 
                       panel.grid.minor = ggplot2::element_blank(), panel.background = ggplot2::element_blank(), 
                       axis.line = ggplot2::element_line(colour = "black"), axis.title=ggplot2::element_text(size=16), 
                       axis.text=ggplot2::element_text(size=14), legend.text=ggplot2::element_text(size=14), legend.position="top", #c(.02,1)
                       legend.justification=c(0,1), legend.title=ggplot2::element_blank()))
dev.off()

**Comment by brianstock** [comment]
Sorry, you are correct... This is a bug in the continuous effect plot. Instead of calculating the quantiles in ILR-space and transforming to p-space, I need to transform all of the ILR-space MCMC draws to p-space and then calculate quantiles. Same as https://github.com/brianstock/MixSIAR/issues/198.

**Comment by LloretElena** [comment]
Hello, 
Thank you for very much your reply! I am not that advance on R-coding but I will give it shot. Would it be okay to send you an email to get some help on how to modify the code for transforming ILR-space before calculating the quantiles?
Thanks!

**Comment by gbsmith06** [comment]
Hi, @brianstock has this been looked into further?  I am seeing the same phenomenon with some of my continuous effect results, wondering how I should proceed.  Is this a workaround I could write into the code (being somewhat novice)?  Should graphical output be trusted until this is worked in?

**Comment by brianstock** [comment]
These bugs should be taken care of now. I also added new options for these plots:
  - `alphaCI` lets you set the credible interval width (default = 0.05, gives 95% CI)
  - `exclude_sources_below` will not plot sources with median proportion below this level for the entire range of continuous variable (default = 0.10)
