### ISSUE TITLE
I want to know the contribution of different sources to each sample in each group

### ISSUE THREAD

**Issue by tumojiyi** [brianstock/MixSIAR#214]
Hi~
     I have 15 consumers, and they are divided into three groups(5 samples in each group),the calculated results of mixsiar model are mean, SD and so forth of three groups.
     
**1.**Is the Mean and SD of the first group in MixSIAR results derived from the 5 samples in this group, or is the Mean and SD independent of these samples?I want to know what process obtained Mean and SD.
    
 **2.**On this basis of result ,I want to know the contribution of different sources to each sample in each group. How can I do it？
     
**3.**In addition, how do I decide to divide some samples in consumers into a group?Are samples with similar isotope values divided into a group?If the sample is divided into groups according to the small difference in isotope values, is it necessary to require significant inter-group differences (e.g., the isotope values of the first sample are significantly different from those of the second)?
    
     I sincerely hope you can help me to solve my doubts. Thank you very much.

**Comment by brianstock** [comment]
1. It depends on the model you specified. I suggest you read the papers describing the model options you are using. See bottom of [README](https://github.com/brianstock/MixSIAR).

2. Include ID as a column in the mix data file and choose this as a factor, as in the [Cladocera ex](https://github.com/brianstock/MixSIAR/blob/master/inst/example_scripts/mixsiar_script_cladocera.R). You may want to choose ID as a random effect nested within Group.

3. This should be based on your biological system and the questions you are interested in answering. For example, in the Wolves dataset, the groups are different regions, and the wolves' diet may be expected to vary by region.
