### ISSUE TITLE
Problems to run MixSIAR on Mac

### ISSUE THREAD

**Issue by Ana1790** [brianstock/MixSIAR#215]
I am trying to install the program on a MacOs High Sierra 10.13.6, I did the installation as indicated in the manual but at the end it does not display the window, just open the xQuartz application without showing anything.

**Comment by AndrewLJackson** [comment]
Can you check What version of R you are running please?



––––––––––––

Dr Andrew Jackson, PhD, FTCD
Associate Professor
School of Natural Sciences, Department of Zoology
Trinity College Dublin, the University of Dublin
Dublin 2, Ireland.

+353 1 896 2728 | a.jackson@tcd.ie<mailto:a.jackson@tcd.ie>

Twitter: @yodacomplex<https://twitter.com/yodacomplex>
http://www.tcd.ie/Zoology/research/research/theoretical/AndrewJackson.php

Trinity College Dublin, the University of Dublin is ranked 1st in Ireland
and in the top 100 world universities by the QS World University Rankings.


On 7 Apr 2020, at 21:40, Ana1790 <notifications@github.com> wrote:

﻿

I am trying to install the program on a MacOs High Sierra 10.13.6, I did the installation as indicated in the manual but at the end it does not display the window, just open the xQuartz application without showing anything.

**Comment by Ana1790** [comment]
I´m using R 3.6.3 GUI 1.70 El Capitan

**Comment by AndrewLJackson** [comment]
I seem to remember some pretty big quartz changes around El Capitan And onwards. Does the package work through scripts and writing figures to file? To be honest I would advise against the gui in almost all situations.



––––––––––––

Dr Andrew Jackson, PhD, FTCD
Associate Professor
School of Natural Sciences, Department of Zoology
Trinity College Dublin, the University of Dublin
Dublin 2, Ireland.

+353 1 896 2728 | a.jackson@tcd.ie<mailto:a.jackson@tcd.ie>

Twitter: @yodacomplex<https://twitter.com/yodacomplex>
http://www.tcd.ie/Zoology/research/research/theoretical/AndrewJackson.php

Trinity College Dublin, the University of Dublin is ranked 1st in Ireland
and in the top 100 world universities by the QS World University Rankings.


On 7 Apr 2020, at 21:53, Ana1790 <notifications@github.com> wrote:

﻿

I´m using R 3.6.3 GUI 1.70 El Capitan

**Comment by brianstock** [comment]
Looks like this site is active and people are eventually succeeding at getting `RGtk2` on Mac. Scroll to bottom: https://gist.github.com/sebkopf/9405675

**Comment by brianstock** [comment]
Update: the `mixsiar_gui()` function has been removed from `MixSIAR` for it to remain on CRAN. If interested in the GUI, see https://github.com/brianstock/MixSIARgui.
