### ISSUE TITLE
Problems running MixSIAR 

### ISSUE THREAD

**Issue by flaviacanastra** [brianstock/MixSIAR#217]
Hello!

I am trying to use MixSIAR with GUI (in macbook) and as I load my data I get this error with the discrimination data:
Error in DISCR[, discr_sig_cols] * DISCR[, discr_sig_cols] : 
  non-numeric argument to binary operator

And I don't understand why. 
And then when I try to run the test I can not do it and I get this error:

Error in rep(1, mixsiar$source$n.sources) : invalid 'times' argument

I wonder if someone can help me!
Thank you very much.

**Comment by brianstock** [comment]
My first 2 guesses are 1) an issue with your file structure, or 2) a mismatch between the files and options you've specified in the loading functions. In order to help, you'll need to post more information:
  - `sessionInfo()` (operating system, versions of R and packages)
  - code you're running
  - top few lines of your data files (include header row)

**Comment by flaviacanastra** [comment]
Hi Brian! Thank you so much for your help!

1. Session info: 

 setting  value                       
 version  R version 3.6.3 (2020-02-29)
 os       macOS Mojave 10.14.6        
 system   x86_64, darwin15.6.0        
 ui       RStudio                     
 language (EN)                        
 collate  pt_PT.UTF-8                 
 ctype    pt_PT.UTF-8                 
 tz       Europe/Lisbon               
 date     2020-04-20                  

─ Packages ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 package       * version  date       lib source        
 assertthat      0.2.1    2019-03-21 [1] CRAN (R 3.6.0)
 backports       1.1.6    2020-04-05 [1] CRAN (R 3.6.2)
 cairoDevice   * 2.27     2019-08-02 [1] CRAN (R 3.6.0)
 callr           3.4.3    2020-03-28 [1] CRAN (R 3.6.2)
 cli             2.0.2    2020-02-28 [1] CRAN (R 3.6.0)
 crayon          1.3.4    2017-09-16 [1] CRAN (R 3.6.0)
 desc            1.2.0    2018-05-01 [1] CRAN (R 3.6.0)
 devtools      * 2.3.0    2020-04-10 [1] CRAN (R 3.6.3)
 digest          0.6.25   2020-02-23 [1] CRAN (R 3.6.0)
 ellipsis        0.3.0    2019-09-20 [1] CRAN (R 3.6.0)
 fansi           0.4.1    2020-01-08 [1] CRAN (R 3.6.0)
 fs              1.4.1    2020-04-04 [1] CRAN (R 3.6.2)
 glue            1.4.0    2020-04-03 [1] CRAN (R 3.6.2)
 gWidgets      * 0.0-54.1 2019-01-27 [1] CRAN (R 3.6.0)
 gWidgetsRGtk2 * 0.0-86   2018-03-01 [1] CRAN (R 3.6.0)
 magrittr        1.5      2014-11-22 [1] CRAN (R 3.6.0)
 memoise         1.1.0    2017-04-21 [1] CRAN (R 3.6.0)
 MixSIAR       * 3.1.10   2018-04-13 [1] CRAN (R 3.6.0)
 pkgbuild        1.0.6    2019-10-09 [1] CRAN (R 3.6.0)
 pkgload         1.0.2    2018-10-29 [1] CRAN (R 3.6.0)
 prettyunits     1.1.1    2020-01-24 [1] CRAN (R 3.6.0)
 processx        3.4.2    2020-02-09 [1] CRAN (R 3.6.0)
 ps              1.3.2    2020-02-13 [1] CRAN (R 3.6.0)
 R6              2.4.1    2019-11-12 [1] CRAN (R 3.6.0)
 remotes         2.1.1    2020-02-15 [1] CRAN (R 3.6.0)
 RGtk2         * 2.20.36  2019-03-08 [1] CRAN (R 3.6.0)
 rlang           0.4.5    2020-03-01 [1] CRAN (R 3.6.0)
 rprojroot       1.3-2    2018-01-03 [1] CRAN (R 3.6.0)
 rstudioapi      0.11     2020-02-07 [1] CRAN (R 3.6.0)
 sessioninfo     1.1.1    2018-11-05 [1] CRAN (R 3.6.0)
 testthat        2.3.2    2020-03-02 [1] CRAN (R 3.6.0)
 usethis       * 1.6.0    2020-04-09 [1] CRAN (R 3.6.3)
 withr           2.1.2    2018-03-15 [1] CRAN (R 3.6.0)
 yaml            2.2.1    2020-02-01 [1] CRAN (R 3.6.0)

2. I am using the interface  with xquartz, that opens after the mixsiar_gui()
3. The top lines: 
for the consumers:

d13C | d15N | Location | Code
-26,4 | 3,7 | Frexulfe | X07
-27,1 | 4,7 | Frexulfe | X07
-27,2 | 4,6 | Frexulfe | X07
-27,2 | 4,3 | Frexulfe | X07

For the sources (it's the raw data):


Source | d13C | d15N
Calluna vulgaris | -29,8014780 | -3,9284057
Erica mackayana | -27,3326160 | -3,0285199
Erica cinerea | -29,8671930 | -2,8401251

And the discrimination: 


Source | Meand13C | SDd13C | Meand15N | SDd15N
Calluna vulgaris | -0,5 | 0,4 | 2,6 | 0
Erica mackayana | -0,5 | 0,4 | 2,6 | 0
Erica cinerea | -0,5 | 0,4 | 2,6 | 0

I think the problem is maybe between the source file and the discrimination file, but I can not understand what it is.
Once again, thank you so much for your help!

**Comment by brianstock** [comment]
A couple possibilities, not sure if they're the problem:

What is your sample size for each source? You can't input raw source data with n=1 because there's no SD... If this is the case, then convert to mean+SD+n format with arbitrary large n (1000 will work). And then use "residual only" error, so the source SDs (which you'd have to input arbitrary numbers for, say 0.01) don't affect the mixture likelihood.

I coded MixSIAR assuming US/UK-style decimal separators, points instead of commas like you have. You could try replacing your `,` with `.` in the data files.
