### ISSUE TITLE
Supress diagnostic plots in pdf

### ISSUE THREAD

**Issue by VirginiaMorera** [brianstock/MixSIAR#219]
Hello, 

Is there a way to suppress the plotting of all diagnostic plots in pdf? It generates a >30.000km pdf that takes ages to create, and there's no option to suppress it apparently. Diag_save refers only to the .txt file. 

Thanks!

**Comment by brianstock** [comment]
Sorry about this - no, short of forking your own copy of MixSIAR and commenting out line 786 of `output_JAGS.R`. I need to separate the GUI from MixSIAR and push a new version to CRAN this week, and will make this small change.

**Comment by brianstock** [comment]
Hi Virginia,

You can now set `output_options$diag_save_ggmcmc = FALSE` as input to `output_JAGS()`. Install the version I just pushed:

```
devtools::install_github("brianstock/MixSIAR", dependencies=T)
```

And then see

```
?output_JAGS
```
