### ISSUE TITLE
Error when including fixed effects

### ISSUE THREAD

**Issue by AdamDuBour** [brianstock/MixSIAR#22]
I am having difficulty running models with mixed effects. My most basic model for examining the variation in diet of ducklings includes the covariate "Lake" as a random effect. I'd like to add the covariate "Age Class", a factor with 4 levels, as a fixed effect. When loading my mixture file with both covariates included I get the following error message: 
(Error in `[.data.frame`(X, , fixed_effects[i]) : 
  undefined columns selected).
I do not get this error message if I include both covariates as either random or fixed effects.
Has anyone else experienced the same? Any suggestions?
Thanks

**Comment by JasonMHill** [comment]
You can get around this by unchecking the box for "Include 'individual' as a random effect." I just tested this out with a mixed effects model (one random and one fixed covariate). Not quite sure why, but when I look at the output "individual" appears to have been treated as a random effect even though the "Include 'individual' as a random effect" box was unchecked.

**Comment by brianstock** [comment]
Hi Adam,

Sorry for the long wait, but this issue should now be resolved in v3.0 I just released.  Check it out and let me know how it works.

In the new manual I don't have an example with mixed effects, but you can see that it works now by changing  `fac_random` in the Wolves Example at line 51 (`load_mix_data`).

Original model (Region and Pack both random effects):
```
fac_random=c(TRUE,TRUE)
```
Mixed effect model (Region = fixed effect, Pack = random effect):
```
fac_random=c(FALSE,TRUE)
```
