### ISSUE TITLE
modifying location legends of isoplot

### ISSUE THREAD

**Issue by jrfrun** [brianstock/MixSIAR#220]
is there a way to modify the location where the legends get place in the iso-plot?  Right now they cover up the data points and would like to be able to place them in a more appropriate location

**Comment by ericward-noaa** [comment]
Yes - I recently added a 'return_obj' argument to the plot_data function. If you update installation via Github, and set return_obj=TRUE, it'll return a ggplot object that you can modify as you wish

**Comment by jrfrun** [comment]
Eric
I did what you mentioned (or what I interpreted you mentioned) but when I did that I got an error

Skipping install of 'MixSIAR' from a github remote, the SHA1 (d8cf9ad1) has not changed since last install.
  Use `force = TRUE` to force installation
Warning message:
1 components of `...` were not used.

We detected these problematic arguments:
* `return_obj`

**Comment by ericward-noaa** [comment]
Hmmm, I don't know what exactly is going on. I tested this last week with @atchin's help, and think we got it working. Here's the test script below -- basically the killer whale script example from the manual, with 2 ways to make the plot (with and without saving it as a ggplot object). @atchin ran into an issue where he needed to set plot_save_pdf = FALSE (defaults to TRUE). 

Code:
devtools::install_github("brianstock/MixSIAR",
  dependencies = TRUE, 
  build_vignettes = FALSE)

library(MixSIAR)
mixsiar.dir <- find.package("MixSIAR")
paste0(mixsiar.dir,"/example_scripts")

mix.filename <- system.file("extdata", "killerwhale_consumer.csv", package = "MixSIAR")

mix <- MixSIAR::load_mix_data(filename=mix.filename,
  iso_names=c("d13C","d15N"),
  factors=NULL,
  fac_random=NULL,
  fac_nested=NULL,
  cont_effects=NULL)

#### Replace the system.file call with the path to your file
source.filename <- system.file("extdata", "killerwhale_sources.csv", package = "MixSIAR")

source <- load_source_data(filename=source.filename,
  source_factors=NULL,
  conc_dep=FALSE,
  data_type="means",
  mix)

#### Replace the system.file call with the path to your file
discr.filename <- system.file("extdata", "killerwhale_discrimination.csv", package = "MixSIAR")

discr <- load_discr_data(filename=discr.filename, mix)

#### make original plot
plot_data(filename="isospace_plot", plot_save_pdf=TRUE, plot_save_png=FALSE, mix,source,discr, return_obj=FALSE)

#### make new plot that returns ggplot object
g = plot_data(filename="isospace_plot", plot_save_pdf=TRUE, plot_save_png=FALSE, mix,source,discr, return_obj=TRUE)
g

**Comment by brianstock** [comment]
For an example of modifying `g` and saving the new plot, see #222.
