### ISSUE TITLE
MixSIAR must be modified to remain on CRAN

### ISSUE THREAD

**Issue by brianstock** [brianstock/MixSIAR#224]
@ericward-noaa @AndrewLJackson 

I received a polite notice that MixSIAR must be modified by May 14 in order to remain on CRAN. Apparently 2013 was a bad year to decide to write an R-based GUI, just before shiny took off and gWidgets was abandoned/orphaned!

Unless someone has the time and desire to re-write a shiny version of the GUI, I propose that we cut the GUI off into its own package on github (MixSIARgui or some such). GUI-less MixSIAR can then remain on CRAN. Given that the GTK install is such a pain on Mac, perhaps this is a blessing in disguise? It may still be useful for people on Windows and Linux.

Are there other small changes to make before submitting a new version to CRAN? E.g. #219

**Comment by ericward-noaa** [comment]
Totally agree -- I like the idea of keeping the GUI archived on Github as its own repo.

For additional changes, I think we could add a flag for suppressing diagnostic plots it that's helpful. The fixes I made to return ggplot objects really only work for the isospace plots -- we could do similar with other functions in MixSIAR, but some use base plots -- and I don't know whether it's worth trying to do that
