### ISSUE TITLE
issues with output 

### ISSUE THREAD

**Issue by jrfrun** [brianstock/MixSIAR#225]

**Comment by jrfrun** [comment]
I ran the wolves script and it ran fine all the way through
I then used my own data on the same wolves script with modifications for my input files and it ran fine until the output where it tells me

Error in device(...) : 
  cannot open file 'E:/working_files/misc/Isotopes/Test/posterior_density_diet_p_A_<200.pdf'
I adjusted the output options so that instead of the pdf TRUE values I set them to off and changed the png options to TRUE but still get the error 

> output_JAGS(jags.1, mix, source, output_options)
Error in device(...) : unable to start png() device
In addition: Warning messages:
1: In device(...) :
  unable to open file 'E:/working_files/misc/Isotopes/Test/posterior_density_diet_p_A_<200.png' for writing
2: In device(...) : opening device failed

in both cases I two plots on the screen (the pairs plot and one (what should be several) posterior plots, and also no expected output on the screen on estimates.

not sure why

**Comment by brianstock** [comment]
I'm guessing the path you're specifying is invalid: `E:/working_files/misc/Isotopes/Test/posterior_density_diet_p_A_<200.pdf`

> Use any character in the current code page for a name, including Unicode characters and characters in the extended character set (128–255), except for the following:
    The following reserved characters:
        < (less than)
        > (greater than)
        : (colon)
        " (double quote)
        / (forward slash)
        \ (backslash)
        | (vertical bar or pipe)
        ? (question mark)
        * (asterisk)

https://www.google.com/search?q=windows+valid+file+names

**Comment by jrfrun** [comment]
Brian

thank you so much. That is the reason for that error.  I had group levels labeled with "<" and ">"
that gets me to continue.  Now I just need to understand the proper choice of options to run the model and understand what I am getting :)

on another issue and it maybe be related to something unrelated to mixsiar but I cannot get ouput on pdf form, that choice gives errors, but if I stick with png there is no problem

regards
