### ISSUE TITLE
Error in position_jitter

### ISSUE THREAD

**Issue by stgeorgj** [brianstock/MixSIAR#226]
Hello,

I am new to using MixSIAR and I was using the GUI for a bit but then for some reason it stopped working because I couldn't get the GTK+ to install correctly anymore. 
Due to that I decided to type out all of the code but right at the beginning when I try to plot my isospace plot I get an error and it will not plot. Everything else runs correctly and plots, just not the isospace plot. I am typing in the code the same as it is in the MixSIAR manual for ploting an isospace.

The error I get is:
"Error in position_jitter(width = 0.2, height = 0.1) : 
  could not find function "position_jitter""
I have been trying to find a way on how to fix it but when I try to set everything to NULL I get another error that the program can't read it. 
"Error in plot_data(filename = "isospace_plot", plot_save_pdf = FALSE,  : 
  unused argument (position = position_jitter(width = NULL, height = NULL))"

Please let me know if there is other packages/code I need to add in or if my data may have something incorrect in it.
Also please let me know if you need any more information.

Thanks, 
Jillian

**Comment by AndrewLJackson** [comment]
Dear Jillian

I haven’t actually looked into this, but the standard approach to debugging these things are to assume that the function position_jitter() is expected but missing and that most likely the package that it is from is either not loaded or out of date. If you google position_jitter() you find that it is part of the package ggplot2. Most likely, this package hasn’t loaded for some reason when running your script.

library(ggplot2)

or

# tidyverse loads ggplot2 and a bunch of other packages that
# commonly work well together. My personal preference
# I would use this approach.
library(tidyverse)

at the start of your script will hopefully fix it.

Of course you might need to install these packages if you don’t have them via

install.packages(“tidyverse”)

and finally, its always worthwhile periodically checking for updates to packages

update.packages(ask = FALSE)

if all that still fails, there is likely another problem. To be honest, the GUI is beset with problems these days as operating systems start to lock down on many of the underlying packages that allow GUIs to run. Keeping up with these developments is often more hassle than its worth, and we would recommend using scripts - my personal advice would be to use Rstudio Rnotebook formats as per the MixSIAR vignettes – to implement these models.

best wishes

Andrew


--

Dr Andrew Jackson, PhD, FTCD
Associate Professor
Irish Research Council Laureate
School of Natural Sciences, Department of Zoology
Trinity College Dublin, the University of Dublin
Dublin 2, Ireland.

+353 1 896 2728 | a.jackson@tcd.ie<mailto:a.jackson@tcd.ie>
Twitter: @yodacomplex<https://twitter.com/yodacomplex>
http://www.tcd.ie/Zoology/research/<http://www.tcd.ie/Zoology/research/groups/jackson/>groups/jackson/

**Comment by stgeorgj** [comment]
Hi Andrew,

Thank you so much! I made sure I loaded tidyverse before and it seems like the issue was solved.
I was loading that package before and for some reason I stopped, so that is probably why I started to get that error.

Thank you,
Jillian
