### ISSUE TITLE
Pairs_plot of each factor level

### ISSUE THREAD

**Issue by lauriyeso** [brianstock/MixSIAR#227]
Hello, I would like to have an output of the model including a pairs plot for each level factor, not only of the overall population. Is it posible to have these outputs? Thanks

**Comment by brianstock** [comment]
Yes, but you'll have to modify some code yourself. The pairs plot is created by [lines 187-232 of output_JAGS.R](https://github.com/brianstock/MixSIAR/blob/master/R/output_JAGS.R#L187). On line 221, `pairs()` is called on `jags.1$BUGSoutput$sims.list$p.global`. You can copy this code and modify to call on `jags.1$BUGSoutput$sims.list$p.fac1`.

Note that `p.fac1` is indexed by `[draws, f1 level, source]`. So to get the pairs plot for the 3rd level of factor 1, use `jags.1$BUGSoutput$sims.list$p.fac1[,3,]`.
