### ISSUE TITLE
Can I compare random and fixed effect contribution

### ISSUE THREAD

**Issue by Melirax** [brianstock/MixSIAR#228]
Hi, 
I have a model that includes a random (site) and fixed factor (vegetation type). I would like to compare their overall contribution. I know that I compare the sd values for 2 random factors. 
How would it work for a fixed and a random factor?

Thank you very much
Best regards

**Comment by AndrewLJackson** [comment]
Hi

You could include both as random if you want to make that direct comparison

Best wishes
Andrew

--

Dr Andrew Jackson, PhD, FTCD
Associate Professor
Irish Research Council Laureate
School of Natural Sciences, Department of Zoology
Trinity College Dublin, the University of Dublin
Dublin 2, Ireland.

+353 1 896 2728 | a.jackson@tcd.ie<mailto:a.jackson@tcd.ie>
Twitter: @yodacomplex<https://twitter.com/yodacomplex>
http://www.tcd.ie/Zoology/research/<http://www.tcd.ie/Zoology/research/groups/jackson/>groups/jackson/

**Comment by Melirax** [comment]
Hi 
Thank you. That's what I've done, but I was not sure it was the right way to do it.

Best wishes
