### ISSUE TITLE
More information about MCMC

### ISSUE THREAD

**Issue by mikeyWyoming** [brianstock/MixSIAR#23]
Hi,
I'm using MixSIAR v. 2.1.2, and I am wondering what the values are for specific parameters when you choose an MCMC run length. For example, if I choose MCMC run length of "normal," what does this mean with respect to the number of chains, number of iterations, and burnin period? 
I could not find this information in summary statistics or in diagnostics. Does anyone know where to find this information?
Thank you,
Mikey

**Comment by jjvenky** [comment]
See @brianstock's answer here: https://github.com/brianstock/MixSIAR/issues/17#issuecomment-75852397

**Comment by mikeyWyoming** [comment]
Thank you, this is exactly what I was looking for.
