### ISSUE TITLE
mixsiar output why does it give posteriors for all combinations of factors

### ISSUE THREAD

**Issue by jrfrun** [brianstock/MixSIAR#230]
I ran a mixsiar analysis with 1 site factor (ran it both as fixed and random) and another factor size with 5 size classes (always as fixed factor).  Also, site and size class factors are chosen to be independent.  After I run my model regardless if site is run fixed or random along with independent of size class, the output provides posteriors for all combinations of site and size class.   This is not clear to me.  I would expect the posteriors for site, and for size class (when both are fixed) and posterior for size class with a distribution of sigma for site(when site is random).  But regardless of how i make the selections, I always get posteriors for the combination of site and size class (a ton of plots), why?

**Comment by brianstock** [comment]
When you have a fixed effect (like "size class"), there is no overall/global intercept to use to plot the levels of another factor ("site"). In other words, there is no way to get estimates by "site" without first choosing a "size class". All of the estimates are specific to a level of "size class".

**Comment by jrfrun** [comment]
Brian

thanks, I'll have to get my head around this
