### ISSUE TITLE
sending output to a specific folder

### ISSUE THREAD

**Issue by jrfrun** [brianstock/MixSIAR#231]
right now one sets the working directory where the data exists and when mixsiar is run, plots and output go to that working directory.

is it possible to have data in one location, set the working directory for that , run the mixsiar and have the plots and output go to a different folder?

**Comment by brianstock** [comment]
When you load the data you specify the path to your file. For example, in the [wolves example script](https://github.com/brianstock/MixSIAR/blob/master/inst/example_scripts/mixsiar_script_wolves.R):
```
# Load mixture data
mix <- load_mix_data(filename="path/to/your/file/thefilename.csv", 
                     iso_names=c("d13C","d15N"), 
                     factors=c("Region","Pack"), 
                     fac_random=c(TRUE,TRUE), 
                     fac_nested=c(FALSE,TRUE), 
                     cont_effects=NULL)
```

There is no argument to `output_JAGS()` to specify where to save the output, so you'd have to change the working directory:
```
setwd("where/you/want/to/save/plots")
output_JAGS(jags.1, mix, source, output_options)
```

**Comment by jrfrun** [comment]
thanks Brian
I did realize you could send the path along with the file name for loading the data files. That helps as I can dictate where the data files reside, and then I can set up the working directory to where output goes

thanks again
