### ISSUE TITLE
Diagnostics.pdf

### ISSUE THREAD

**Issue by joshpi** [brianstock/MixSIAR#233]
Hello,

How can I open the diagnostics.pdf output as specified on pg 17 of the MixSIAR Manual? I'm hoping to access posterior density plots by chain, as not all 3 chains are not converging in accordance with the Geweke diagnostic. Let me know if I can be more specific. 

Thanks! 

Josh Pi

**Comment by joshpi** [comment]
For more detail, here is the list of outputs I have chosen: 

# Choose output options (see ?output_options for details)
output_options <- list(summary_save = TRUE,                 
                       summary_name = "summary_statistics", 
                       sup_post = FALSE,                    
                       plot_post_save_pdf = TRUE,           
                       plot_post_name = "posterior_density",
                       sup_pairs = FALSE,             
                       plot_pairs_save_pdf = TRUE,    
                       plot_pairs_name = "pairs_plot",
                       sup_xy = TRUE,           
                       plot_xy_save_pdf = FALSE,
                       plot_xy_name = "xy_plot",
                       gelman = TRUE,
                       heidel = FALSE,  
                       geweke = TRUE,   
                       diag_save = TRUE,
                       diag_name = "diagnostics",
                       indiv_effect = FALSE,       
                       plot_post_save_png = FALSE, 
                       plot_pairs_save_png = FALSE,
                       plot_xy_save_png = FALSE,
                       diag_save_ggmcmc = FALSE)

**Comment by brianstock** [comment]
If you change `diag_save_ggmcmc` to `TRUE` you'll get the ggmcmc diagnostics as a big PDF file, with diagnostics by chain. Sorry for the confusion - the ability to turn this output off is a new addition since the manual was last edited.

**Comment by joshpi** [comment]
Thanks for the quick response, Brian. I was under the assumption that by examining individual chains I could get individual posterior density plots, but I'm not sure where to find that in the diagnostic.pdf output. Could be that I'm not familiar with the parameter names (p.fac, irl.fac) or what they mean. Is there a good resource that explains how to interpret these?

**Comment by brianstock-NOAA** [comment]
The diagnostics output from the `ggmcmc` package plots the posteriors by chain. Set `diag_save_ggmcmc = TRUE` in `output_JAGS`. Although... I just tried this and got an error. Looks like the `ggmcmc` package needs to be updated. https://cran.r-project.org/web/packages/ggmcmc/vignettes/using_ggmcmc.html

Not to worry, the posterior density plots by chain still work using `ggmcmc::ggs()`:
```
library(MixSIAR)
mixsiar.dir <- find.package("MixSIAR")
source(file.path(mixsiar.dir,"example_scripts","mixsiar_script_wolves.R"))
jags1.mcmc <- coda::as.mcmc(jags.1)
ggmcmc::ggmcmc(ggmcmc::ggs(jags1.mcmc), plot="density")
```
![diag](https://user-images.githubusercontent.com/61591802/84956425-2b520f00-b0c7-11ea-97ad-68415d146725.png)


Re: parameter names, see pages 22-23 of the manual, https://github.com/brianstock/MixSIAR/issues/190 (also has screenshot of the `ggmcmc` posterior plots by chain), https://github.com/brianstock/MixSIAR/issues/80, https://github.com/brianstock/MixSIAR/issues/30. FYI, I found these by searching the Issues for "ilr.fac" and "p.fac". This is useful. For example, to see all of the issues posts that mention "geweke": https://github.com/brianstock/MixSIAR/issues?q=is%3Aissue+geweke

**Comment by joshpi** [comment]
That was all very useful. Thank you so much!
