### ISSUE TITLE
output_JAGS suggestions

### ISSUE THREAD

**Issue by AndrewLJackson** [brianstock/MixSIAR#235]
Suggest split `output_jags` into multiple functions, especially for the figures, and output the produced `ggplot` objects for subsequent editing. Perhaps output as a list of objects for ones which are many in order to keep output tidy.

Suggest remove `dev.new()` calls to prevent massive figure counts spawning.

Suggest `ggsave()` to output files and not the Cairo or other pdf writing functions.

**Comment by brianstock** [comment]
Good suggestions. Done!

See new vignette [Modifying output](http://brianstock.github.io/MixSIAR/articles/modify_output.html).

**Comment by AKuepfer123** [comment]
Just what I was looking for! Is the 3. 1. 13 version available yet? Somehow I cannot locate it anywhere.

**Comment by brianstock** [comment]
Have you tried installing from GitHub as in the vignette linked above? The
changes are definitely on GitHub, may not be on CRAN because I don't submit
updates there very often.

**Comment by AKuepfer123** [comment]
Thank you. It gives me the following warning, even though I do not have MixSIAR loaded anywhere. 

Warning: package ‘MixSIAR’ is in use and will not be installed
There were 12 warnings (use warnings() to see them)
> packageVersion("MixSIAR")
[1] ‘3.1.12’

I then deleted the package, but it makes no difference:
> library("MixSIAR")
> path.package("MixSIAR")
[1] "C:/Users/akuepfer/Documents/R/win-library/4.0/MixSIAR"
> packageVersion("MixSIAR")
Error in packageVersion("MixSIAR") : there is no package called ‘MixSIAR’

**Comment by brianstock** [comment]
Hmm, that's strange and not sure I can help. I always install packages in a
fresh terminal/console session (ie close R, open R and not rstudio, then
the devtools::install_github command). You could try that.

**Comment by AKuepfer123** [comment]
I will try that. In any case, I was able to successfully use the following code to make the isospace plot a ggplot object.

g <- plot_data(filename="isospace_plot", plot_save_pdf=FALSE, plot_save_png=FALSE, mix,source,discr, return_obj=TRUE)

I then tried to use this code to convert the posterior density plot to a ggplot object using:

p <- plot_data(filename="posterior_density", plot_save_pdf=FALSE, plot_save_png=FALSE, mix,source,discr, return_obj=TRUE)

But this just returns the isospace plots, regardless of the filename. Why is this?

Thanks

**Comment by brianstock** [comment]
You have plot save pdf and png set to FALSE, return obj TRUE, and are
storing the result as p. That looks like you want to return the isospace
plots as p... What are you trying to do?

**Comment by AKuepfer123** [comment]
What I want to do is have the posterior density_plot returned as an object so i can modify it in ggplot. I can do this for the isospace plot by using your code provided on this platform. However, I cannot get this to work for any of the output_JAGS plots. I gather it is not as simple as just changing the filename from "isospace_plot" to "posterior"density". 

This is what I run for the isospace plot
```g <- plot_data(filename="isospace_plot", plot_save_pdf=FALSE, plot_save_png=FALSE, mix,source,discr, return_obj=TRUE)```

Then, once I have the model, I run this:
```
output_JAGS(jags.1, mix, source, output_options = list(summary_save = TRUE, 
                                                       summary_name = "summary_statistics",
                                                       sup_post = FALSE, 
                                                       plot_post_save_pdf = TRUE, 
                                                       plot_post_name = "posterior_density",
                                                       sup_pairs = FALSE, 
                                                       plot_pairs_save_pdf = TRUE, 
                                                       plot_pairs_name = "pairs_plot", 
                                                       sup_xy = TRUE,
                                                       plot_xy_save_pdf = FALSE, 
                                                       plot_xy_name = "xy_plot", 
                                                       gelman = TRUE, 
                                                       heidel = FALSE, 
                                                       geweke = TRUE, 
                                                       diag_save = TRUE, 
                                                       diag_name = "diagnostics", 
                                                       indiv_effect = FALSE, 
                                                       plot_post_save_png = FALSE,
                                                       plot_pairs_save_png = FALSE, 
                                                       plot_xy_save_png = FALSE, 
                                                       diag_save_ggmcmc = TRUE))
```

and then I run the following code, in the hope of having the density plot returned as an object - but it just returns the isospace plot, regardless of which filename I use.

```p <- plot_data(filename="posterior_density", plot_save_pdf=FALSE, plot_save_png=FALSE, mix,source,discr, return_obj=TRUE)```

**Comment by brianstock** [comment]
That's because the function name is output_posteriors. plot_data makes the
isospace plot.

**Comment by AKuepfer123** [comment]
Aaah.. Now I am with you. And the output_posteriors function is only available in the 3.1.13 version.

**Comment by AKuepfer123** [comment]
Hi Brian, 

Sorry - me again. I still cannot seem to install the 3.1.13 version. Do you know if this is a common issue?
I removed the original MixSIAR package, then installed from github, but it just installs the 3.1.12 version again (see output below). Is there anything else I could try, or is there any code available to assist with this when using version 3.1.12?
Very many thanks,
Amanda

> #install.packages("devtools")
> remotes::install_github("brianstock/MixSIAR", dependencies=T, force = TRUE)
Downloading GitHub repo brianstock/MixSIAR@HEAD
√  checking for file 'C:\Users\akuepfer\AppData\Local\Temp\RtmpC0D316\remotesf0021ad1f2a\brianstock-MixSIAR-037978f/DESCRIPTION' ...
-  preparing 'MixSIAR': (563ms)
√  checking DESCRIPTION meta-information ... OK
   Warning in as.POSIXlt.POSIXct(x, tz) :
     unable to identify current timezone 'F':
   please set environment variable 'TZ'
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'MixSIAR_3.1.12.tar.gz'
   
Installing package into ‘C:/Users/akuepfer/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
Warning in strptime(xx, f, tz = tz) :
  unable to identify current timezone 'F':
please set environment variable 'TZ'
* installing *source* package 'MixSIAR' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'MixSIAR'
    finding HTML links ... done
    calc_area                               html  
    combine_sources                         html  
    compare_models                          html  
    load_discr_data                         html  
    load_mix_data                           html  
    load_source_data                        html  
    mixsiar_env                             html  
    output_JAGS                             html  
    output_diagnostics                      html  
    output_pairs                            html  
    output_posteriors                       html  
    output_stats                            html  
    output_xy                               html  
    plot_continuous_var                     html  
    plot_data                               html  
    plot_data_one_iso                       html  
    plot_data_two_iso                       html  
    plot_intervals                          html  
    plot_prior                              html  
    run_model                               html  
    summary_stat                            html  
    write_JAGS_model                        html  
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
*** arch - i386
*** arch - x64
** testing if installed package can be loaded from final location
*** arch - i386
*** arch - x64
** testing if installed package keeps a record of temporary installation path
* DONE (MixSIAR)
Warning messages:
1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
> packageVersion("MixSIAR")
[1] ‘3.1.12’

**Comment by brianstock** [comment]
Hi Amanda,

Sorry for the confusion if you are looking for 3.1.13 because the vignette
linked in this thread says it exists. It does not, I wrote that assuming I
would tag the changes I made for the vignette as a new version but I never
did. If you install from GitHub like you have, that's the latest code and
you should be able to follow the vignette. Is that not the case?

**Comment by AKuepfer123** [comment]
Aahhh...... silly me. Yes, the vignette does work in the .12 version. I got
hung up on trying to install the .13 version, duh..

Thanks - these functions are super useful!

**Comment by ncttrinh** [comment]
Hi Brian and Amanda,

How did you install 3.1.13? I seem to have the same purpose with Amanda, and was trying to install from R, not Rstudio, but eventually it still show 3.1.12 version. I did exactly the same with what Amanda did on 8 Mar. Thanks.

**Comment by brianstock** [comment]
As above, there is no 3.1.13. Installing from github will give you the
latest code.

**Comment by ncttrinh** [comment]
Thanks Brian for a super quick response :) 
All good now :) thanks so much!
Btw, I assume that I can use any of the several examples that the package provided, and modified the "mix, source, discrimination" excel files by replacing their data with my own data, as long as my data fits the context of that example, am I right? 
Thanks Brian!
