### ISSUE TITLE
Error in load_mix_data

### ISSUE THREAD

**Issue by GKKDU** [brianstock/MixSIAR#239]
Hello, 
I am working with a two tracer model. However, after loading the consumer file, the mix <- load_mix_data function is not working. I used the same function successfully earlier but now its not working.
I tried with the wolves example script and data without any modification and having same problem. I checked the file type.

mix.filename <- system.file("extdata", "wolves_consumer.csv", package = "MixSIAR")
upto this point its working. but error occurs on the next step:

mix <- load_mix_data(filename=mix.filename, 
+                      iso_names=c("d13C","d15N"), 
+                      factors=c("Region","Pack"), 
+                      fac_random=c(TRUE,TRUE), 
+                      fac_nested=c(FALSE,TRUE), 
+                      cont_effects=NULL)
Error in load_mix_data(filename = mix.filename, iso_names = c("d13C",  : 
  could not find function "load_mix_data"

**Comment by ericward-noaa** [comment]
I don't think you have MixSIAR loaded or installed. Make sure you load it with library("MixSIAR") first. If that throws an error that says  'there is no package called MixSIAR', you need to install it first with install.packages("MixSIAR")
