### ISSUE TITLE
alligator example calc_eps

### ISSUE THREAD

**Issue by jrfrun** [brianstock/MixSIAR#240]
I have tried running the alligator example, but it generates an error

+   eps.med[i] <- calc_eps(p.median[i,])
+   eps.low[i] <- calc_eps(p.low[i,])
+   eps.high[i] <- calc_eps(p.high[i,])
+ }
Error in calc_eps(p.median[i, ]) : could not find function "calc_eps"

looking at the code from beginning to this point, it appears that calc_eps has not been defined in the code anywhere, how do I fix this

regards

**Comment by brianstock-NOAA** [comment]
There is a search feature in Github - please use it before posting new issues. A search for "calc_eps" shows this was reported and fixed on Github in 2018 (https://github.com/brianstock/MixSIAR/issues/149), and was included in the latest CRAN update ([NEWS.md](https://github.com/brianstock/MixSIAR/blob/f23f21acbc40612799a66985977f34d566a6217e/NEWS.md)). Updating MixSIAR to the latest version should resolve your issue.
