### ISSUE TITLE
Error in read.table

### ISSUE THREAD

**Issue by EllenMcKee** [brianstock/MixSIAR#241]
When running this code (where csvfiles is a folder on my c drive: C:\csvfiles) to import my consumer data file:
mix.filename <- system.file("csvfiles","Vulture_MixSIAR.csv", package = "MixSIAR")
mix <- load_mix_data(filename= data,
                     iso_names=c("13C","15N"),
                     factors=c("Species"),
                     fac_random=c(FALSE),
                     fac_nested=c(NULL),
                     cont_effects=NULL)

I have received the error:
Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  'file' must be a character string or connection

The file Vulture_MixSIAR.csv is a csv file so I am unsure of what is going wrong. 

Also when trying to alternatively run the GUI and running the code line of:

devtools::install_github("brianstock/MixSIARgui", dependencies=T) # installs MixSIAR as dependency

I recieve this error:

Error: Failed to install 'MixSIARgui' from GitHub:
  (converted from warning) installation of package ‘C:/Users/ellen/AppData/Local/Temp/RtmpaeKP0v/file3d202d35cec/MixSIARgui_1.0.0.tar.gz’ had non-zero exit status

Any help would be much appreciated!

**Comment by brianstock** [comment]
You need to give the file name to read_mix_data: `filename=mix.filename`

I'm not sure why the GUI isn't installing, sorry. Please submit an issue on that repository, and post more information on OS, versions of R and installed packages (output of `sessionInfo()`).

**Comment by EllenMcKee** [comment]
Sorry I did mean to put mix.filename. Instead I have received a different errror. 

mix.filename <- system.file("csvfiles","Vulture_MixSIAR.csv", package = "MixSIAR")

#Load the mixture/consumer data
#You need to give the file name to read_mix_data: 
#filename=mix.filename

mix <- load_mix_data(filename= mix.filename,
                     iso_names=c("13C","15N"),
                     factors=c("Species"),
                     fac_random=c(FALSE),
                     fac_nested=c(NULL),
                     cont_effects=NULL)

Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  no lines available in input
In addition: Warning message:
In file(file, "rt") :
  file("") only supports open = "w+" and open = "w+b": using the former

**Comment by brianstock** [comment]
I'm not sure, it could be an issue with your csv file instead of the path.
`load_mix_data` uses the function `read.csv`, so I'd make sure you can read
in your csv file to R using `read.csv`.

**Comment by flaviacanastra** [comment]
I have the same problem and the same error as Ellen. 
Does anyone know how to solve it?
thnak you.

**Comment by CamillaLienart** [comment]
Hi evryone,

I have used the exat same script and data files as before (it was working on my previous computer a few months ago) now I have a new computer and downlad all packages (was a bit of trouble regarding MixSIAR since it is not available anymore on CRAN but to be downloaded in the archive files) and ... frome the exact same script and files it give me the same message error as Ellen and Flavia:
Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  no lines available in input
In addition: Warning message:
In file(file, "rt") :
  file("") only supports open = "w+" and open = "w+b": using the former

Can you help us with that please ? 
I tried different files types and the .csv I used before is well red by a classical read.csv() ... so  ... the problem might come from the load_mix_data() actually...

Thank you for your help. 

Camilla

**Comment by brianstock** [comment]
Hi Camilla, I can take a look if you post a [minimal reproducible example](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example) (csv files and R code you're running). I wonder if it's related to R 4.0 changes? MixSIAR runs 9 tests that make sure each of the examples works, including reading in all the csv files distributed with the package. All of these succeed on my local machine (Linux Ubuntu 18.04, R 4.0.3), as well as in several test environments (Windows R 4.0.3, Windows R-devel, Linux R-devel, etc.).

MixSIAR should be back on CRAN soon, I resubmitted it today. In the meantime, I'd recommend installing from Github instead of a CRAN archive:
```
remotes::install_github("brianstock/MixSIAR", dependencies=T)
```

**Comment by CamillaLienart** [comment]
Hi Brian, 
Thank you for your reply. Yes sorry... I forgot details... 
Here are the data (.csv) and I tried with different formatting but this exact file was working before ... (June 2020).


d13C,d15N,Species
-16.0054159332399,5.62610840337233,Cerastoderma
-20.8714361921046,5.7059904010501,Cerastoderma
-20.5563083280589,5.70259544211202,Cerastoderma
-17.3789383545253,6.16547197677758,Limecola
-17.9636265043795,6.43118927117218,Limecola
-17.0392616905298,5.90242574917534,Limecola
-16.929136331308,6.82361272894425,Limecola
(... this is only the first 8 rows)

So basically, first I set a working directory, load the needed packages and then run the following lines:
# Load mixt data
mix.filename <- system.file("Pollendata", "conso_FW1.csv", package = "MixSIAR")
mix <- load_mix_data(filename=mix.filename, 
                     iso_names=c("d13C","d15N"), 
                     factors=c("Species"),
                     fac_random=c(FALSE), 
                     fac_nested=c(FALSE), 
                     cont_effects=NULL)

And at this stage it gives me the following error message:
Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  no lines available in input
In addition: Warning message:
In file(file, "rt") :
  file("") only supports open = "w+" and open = "w+b": using the former

I tried with different types of files formatting ... and nothing works, even though all can be red parfercty with the 
mix <- read.csv("conso_FW1.csv",h=TRUE,sep=",",dec=".")

My R version 3.6.3 (2020-02-29) with MixSIAR 3.1.11 (on MacOS 10.13.6)
I also tried R version 3.3.2 (2016-10-31) with MixSIAR 3.1.7 (on Windows 10 version 1909)

Hopefully this helps ... 
Thanks.
Camilla

**Comment by brianstock** [comment]
Your first line, `mix.filename <- system.file("Pollendata", "conso_FW1.csv", package = "MixSIAR")`, is telling MixSIAR to look for your mix file in the directory where MixSIAR is installed. That's probably wrong. Your `read.csv` call works because you're giving the correct path to the file. You probably want

```
mix <- load_mix_data(filename="conso_FW1.csv",
iso_names=c("d13C","d15N"),
factors=c("Species"),
fac_random=c(FALSE),
fac_nested=c(FALSE),
cont_effects=NULL)
```

This assumes the file is in your working directory. Confirm with `list.files()`.

**Comment by CamillaLienart** [comment]
Hi Brian, 
Oooops ... Indeed, sorry ... 
I don't know how it came up being mixed in my scripts (I sometimes work from the directory where MixSIAR is installed to come back to data examples). Probably the change from Windows to Mac with me not being used to Mac, plus a mess to reinstall all packages and cie. 
Thank you for your help and sorry for bothering with such details ! 
Camilla

**Comment by CaroCD1** [comment]
Hello Brian,

I am using the alligator example to apply the analysis with  my samples, but I have the same problem as camilla. 
I already changed the command 
mix.filename <- system.file("extdata", "mysamples.csv", package = "MixSIAR")
by read.csv, but I keep getting the same error. 

 setwd("/Users/carolina/Desktop/Anchovetas 1")
 mix.filename <- read.csv("Consumers.csv", sep = ",")
 mix <- load_mix_data(filename=mix.filename,
                      iso_names=c(d13C, d15N),
                      factors=NULL,
                      fac_random=NULL,
                      fac_nested=NULL,
                      cont_effects=NULL)

Error in load_mix_data(filename = mix.filename, iso_names = c(d13C, d15N),  : 
  could not find function "load_mix_data"


thank you very much for your help!!

**Comment by CaroCD1** [comment]
and same error with and without ""

> mix <- load_mix_data(filename=mix.filename,
+                      iso_names=c("d13C", "d15N"),
+                      factors=NULL,
+                      fac_random=NULL,
+                      fac_nested=NULL,
+                      cont_effects=NULL)
Error in load_mix_data(filename = mix.filename, iso_names = c("d13C",  : 
  could not find function "load_mix_data"

**Comment by cmmertz** [comment]
Hello,

This is my first time using MIXSIAR and am having some trouble reading in my csv's. 
When I try to run the load_mix_data or load_source_data code I get this error-

Error in read.table(file = file, header = header, sep = sep, quote = quote, :
'file' must be a character string or connection

**Here are the lines of code resulting in the error:**

#read in my data
mix.filename <-read.csv("/Users/connermertz/Documents/Conner Documents/UNM biology/Chapter 1 E1 vs E2/Methods/SIA/E1_E2_d13C Data/Microbial_Contribution_MixingModel/muscle_consumer.csv", header = TRUE, stringsAsFactors = FALSE) 

# Load the mixture/consumer data
mix <- load_mix_data(filename=mix.filename, 
                     iso_names=c("d13CVal",	"d13CLeu", "d13CIle", "d13CPhe", "d13CLys", "d13CThr","d13CTyr"), 
                     factors=c("Experiment","Percent_Protein"), 
                     fac_random=c(TRUE,TRUE), 
                     fac_nested=c(FALSE,TRUE), 
                     cont_effects=NULL) 

#AND
#read my data
source.filename <-read.csv("/Users/connermertz/Documents/Conner Documents/UNM biology/Chapter 1 E1 vs E2/Methods/SIA/E1_E2_d13C Data/Microbial_Contribution_MixingModel/muscle_sources.csv", header = TRUE, stringsAsFactors = FALSE)
# Load the source data
source <- load_source_data(filename=source.filename,
                           source_factors="Experiment", 
                           conc_dep=FALSE, 
                           data_type="means", 
                           mix) 


**Here are the csv's I am trying to use:**

[muscle_consumer.csv](https://github.com/brianstock/MixSIAR/files/11607948/muscle_consumer.csv)
[muscle_sources.csv](https://github.com/brianstock/MixSIAR/files/11607952/muscle_sources.csv)

Any thoughts or suggestions would be greatly appreciated!
Best,
Conner

(R version: 4.3.0)
