### ISSUE TITLE
Convergence not met

### ISSUE THREAD

**Issue by stgeorgj** [brianstock/MixSIAR#245]
Hi there,

I am running a model with 8 fish species and one isotope (d34S) to estimate the proportions of freshwater and marine-derived nutrients in the diets of the different fish species. I am running one model with their muscle values and another one with their liver values and seeing if I have similar results from the different tissues. I have used freshwater and marine as my sources and I have no discrimination factor (I copied how the alligator example was set up somewhat).

The problem I am having is I can't seem to reach convergence with the Geweke diagnostic (unless I am interpreting it wrong, please let me know). The Gelman diagnostic has met convergence. I have run all the way to the extreme run and I still haven't met convergence based on the Geweke diagnostic so I am unsure what to do.

My results are as follows:

################################################################################
# Gelman-Rubin Diagnostic
################################################################################

Generally the Gelman diagnostic should be < 1.05

Out of 414 variables: 0 > 1.01

                      
0 > 1.05

                      
0 > 1.1

################################################################################
# Geweke Diagnostic
################################################################################

The Geweke diagnostic is a standard z-score, so we'd expect 5% to be outside +/-1.96
Number of variables outside +/-1.96 in each chain (out of 
414
):

       Chain 1 Chain 2 Chain 3
Geweke       0      77      10

Thanks,
Jillian

**Comment by brianstock** [comment]
I think you can say your model is converged. Gelman-Rubin Rhat < 1.01 for 414/414 variables is good. 87/(414*3) = 0.07, so you're not far off the expected 5% for the Geweke. And I wouldn't worry about the Geweke as much.
