### ISSUE TITLE
Error in MixSIAR::load_source_data(mixsiar$source_filename, source_random_effects

### ISSUE THREAD

**Issue by Consuelo1212** [brianstock/MixSIAR#247]
Hi Brian, when I load the data in source I get the following error, although I do get a green ticket in the source window, could you please help me understand this?
“Error in MixSIAR::load_source_data(mixsiar$source_filename, source_random_effects, :
Source mean column names mislabeled.
Should be 'Mean' + iso_names from mix data file, e.g. 'Meand13C' if
mix$iso_names = 'd13C'. Please ensure headings in source data file match
this format and try again. Alternatively, if you have raw source data,
you should set data_type='raw'.

“Sources | Meand13C | SDd13C | Meand15N | SDd15N | Concd13C | Concd15N | N”

thanks

**Comment by brianstock-NOAA** [comment]
Can you post the column header from your mix and source CSV files, as well as output from 
```
mix$iso_names
mix$MU_names
mix$SIG_names
```

If you search for that error message in `load_source_data()`, you can see what the function is expecting: https://github.com/brianstock/MixSIAR/blob/master/R/load_source_data.R#L214.

**Comment by Consuelo1212** [comment]
Source data:
Sources,Meand13C,SDd13C,Meand15N,SDd15N,Concd13C,Concd15N,n


consumer data:
d13C,d15N,sex,size,size_class

thanks!

**Comment by brianstock-NOAA** [comment]
Those look correct... Can you please post the output of mix$iso_names, mix$MU_names, and mix$SIG_names after loading the mix data? Also post output from:
```
srcdata <- read.csv(***your source data file.csv***)
colnames(srcdata)
```

**Comment by Consuelo1212** [comment]
Dear Brian, I am grateful of your help. This is the first time I am using MixsiarGUI and apparently my mistake was with the format of the CSV file, now it is working right.

**Comment by brianstock-NOAA** [comment]
Great - glad it's working now! I'm also glad you're able to get the GUI to work, since many people have problems installing it.

**Comment by melanievenet** [comment]
> Dear Brian, I am grateful of your help. This is the first time I am using MixsiarGUI and apparently my mistake was with the format of the CSV file, now it is working right.

Hi, I am trying to load in my source data and am running into the same mistake you were, how did you fix the format of the CSV file? I am just using MixSIAR not GUI I'm not sure if that makes a difference it is my first time using this package!

**Comment by edgar45328** [comment]
Error in load_discr_data(mixsiar$discr_filename, mixsiar$mix) : 
  *** Error: Discrimination mean column names mislabeled.
    Should be 'Mean' + iso_names from mix data file, e.g. 'Meand13C' if
    mix$iso_names = 'd13C'. Please ensure headings in discr data file match
    this format and try again.

**Comment by edgar45328** [comment]
can someone tell me what the problem is?

**Comment by ncttrinh** [comment]
I got the issue with loading the source data and I realised that my csv file named "sediment sources.csv " while my script calls out the name "sediment_sources.csv". So all troubles begin with the underscore _, or more specific, it is the file name difference. 
just sharing....
