### ISSUE TITLE
obtaining SD posterior distributions. 

### ISSUE THREAD

**Issue by VirginiaMorera** [brianstock/MixSIAR#25]
Hi, 
I'm trying to extract the posterior distributions for the SD across the 2 levels of my data. I assumed that they where in 
```
attach.jags(jags.1
ind.sd <- ind.sig
year.sd <- fac1.sig
``` 
but since I've realised there is actually an object inside `jags.1$BUGSoutput` called sd with a bunch of numerical objects inside... None of them are actually a posterior, but they got me thinking. What are they? Am I using the right posteriors for the SD? 

Any ideas will be much appreciated!

Virginia.

**Comment by brianstock** [comment]
Yes, `ind.sig`, `fac1.sig`, and `fac2.sig` are the SDs in the hierarchical structure you want.

`jags.1$BUGSoutput$sd` gives the SD of all the JAGS variables (also printed in the summary statistics).  As an example, these are equivalent ways of getting the SD of the overall diet proportion of source 1:

```
> sd(p.global[,1])
[1] 0.1319602
> jags.1$BUGSoutput$sd$p.global[1]
[1] 0.1319602
```

**Comment by VirginiaMorera** [comment]
Perfect, thank you for the clarifications!
