### ISSUE TITLE
creating an interaction model

### ISSUE THREAD

**Issue by jrfrun** [brianstock/MixSIAR#251]
Brian 
in your alligator example, you create a set of models to test via LOO.  One of the models is an interaction model between sex and sclass which you use a new variable created by concatenating the variable sex with sclass.  I think you were trying to compare that model to some other authors example.  But I was wondering why, since it appears this mode fails in the marginallity principle of including the marginal factors.   Would it make sense to have include sex, sclass and sex_sclass as factors?

Just wondering

regards

**Comment by brianstock** [comment]
Correct, I only ran model 8 as a closest approximation to running separate mixing models in SIAR for each sex_sclass combination, as in the original study (for context see comments in [alligator script](https://github.com/brianstock/MixSIAR/blob/master/inst/example_scripts/mixsiar_script_alligator.R#L49.). There is no interaction term, each combination is run separately. Model 6 is the one that includes sex and size class as independent factors. And no, the model comparison did not support including sex in addition to size class or length: [Table 1 in paper](https://peerj.com/articles/5096/#table-1).
