### ISSUE TITLE
I cant install MixSIAR

### ISSUE THREAD

**Issue by edna1988** [brianstock/MixSIAR#252]
I am having problem with the installing of MixSIAR

I followed the steps:
1. Update R
2. Install Jags
3. install MixSIAR

```{r}
library(installr)
```
 
```{r}
updateR()
```
 
```{r}
install.packages("MixSIAR", dependencies=TRUE)
library(MixSIAR)
```
Warning in install.packages :
  package ‘MixSIAR’ is not available (for R version 4.0.2)

**Comment by brianstock** [comment]
Sorry, MixSIAR has been taken off CRAN. I will work to get it back up. For now, you can either install an archived version or github:

```
devtools::install_github("brianstock/MixSIAR", dependencies = T, build_vignettes = F)
library(MixSIAR)
```

**Comment by edna1988** [comment]
I tried to install it but I couldn't
Is there another way to install it?

devtools::install_github("brianstock/MixSIAR", dependencies = T, build_vignettes = F)
library(MixSIAR) 

Error: Failed to install 'MixSIAR' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘ps’
In addition: Warning messages:
1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers

**Comment by brianstock** [comment]
Hmm, strange. I'm not sure what the issue with the `ps` package is here, I've never seen that. I'd make sure your R and all other packages are up to date and try again. The list of packages that MixSIAR depends on is in the [DESCRIPTION file](https://github.com/brianstock/MixSIAR/blob/master/DESCRIPTION), and you can make sure they're all installed with version #s at least as recent as the numbers listed. Is that so in your case?

**Comment by brianstock** [comment]
First check that you can install and load `devtools`:
```
install.packages("devtools")
library(devtools)
install_github("brianstock/MixSIAR", dependencies = T, build_vignettes = F)
```
If not, see https://github.com/r-lib/devtools.

I have resubmitted MixSIAR to CRAN and expect it will be up soon.

**Comment by brianstock** [comment]
MixSIAR is back up on CRAN: https://cran.r-project.org/web/packages/MixSIAR/index.html.
