### ISSUE TITLE
interval plots

### ISSUE THREAD

**Issue by jrfrun** [brianstock/MixSIAR#254]
HI Brian

I dont have an issue running the interval plot, but I would like to automate some code i have created that calls on your plot_intervals command

to explain, i'll use the alligator example
to run the plot_interval command, something like the following works without a problem

original = combine_sources(jags.1, mix, source, myprior, groups=list('Frsh'='Freshwater','Marn'='Marine')) 
plot_intervals(original,toplot="fac1",savepdf=TRUE,filename='intervals')

I am trying to automatically create the above but not sure how to create the stuff in the groups:  'Frsh'='Freshwater','Marn'='Marine'

When I run something like
x=abbreviate(source$source_names) 
y=paste(x,source$source_names,sep='=',collapse=", ")
it yields for y:  "Frsh=Freshwater, Marn=Marine"

which whe used in the above command
original = combine_sources(jags.1, mix, source, myprior, groups=list(y)) 
obviously it does not work

I know its a not an issue, but do you have suggestions as to how i can "automate" what goes into the group=list (?) that would work, cause my paste method does not?

regards

**Comment by brianstock** [comment]
I'd follow the syntax in the `?combine_sources` example:
```
groups=list(hard=c("clam","crab","snail"), soft=c("alphworm","brittlestar","fish")
```
`hard` and `soft` will be the new sources names (no quotes), and the original source names for each are given as a character vector (with quotes). So whatever you do needs to match that syntax. 

Compare the `groups` list from the alligator example:
```
> list(Freshwater="Freshwater",Marine="Marine")
$Freshwater
[1] "Freshwater"

$Marine
[1] "Marine"
```

Here's what you're doing:
```
> x=abbreviate(source$source_names)
> y=paste(x,source$source_names,sep='=',collapse=", ")
> list(y)
[[1]]
[1] "Frsh=Freshwater, Marn=Marine"
```

Try:
```
> y = as.list(source$source_names)
> y
[[1]]
[1] "Freshwater"

[[2]]
[1] "Marine"

> names(y) = source$source_names # or whatever you want
> y
$Freshwater
[1] "Freshwater"

$Marine
[1] "Marine"
```

**Comment by jrfrun** [comment]
Brian 

Thanks for your response but either I dont understand what you tell me or it does not work
I am trying to "automate" my code without having to manually change things.  So when I run the alligator model i can use the following code and it works
original = combine_sources(jags.1, mix, source, myprior,
            groups=list(Fresh="Freshwater",Marine="Marine")) 
plot_intervals(original,toplot="fac1",savepdf=TRUE,filename='intervals')  


but this requires me to manually change the code part groups=list(Fresh="Freshwater",Marine="Marine")

i would like to modify my code so that it automatically plots the intervals so not sure how to modify 
 groups=list(Fresh="Freshwater",Marine="Marine")
i dont know how to interpret your suggestion, when i try 

y = as.list(source$source_names)
original = combine_sources(jags.1, mix, source, myprior,
            groups=list(y)) 
plot_intervals(original,toplot="fac1",savepdf=TRUE,filename='intervals')  

as i think you are telling me, it does not work
how could i changegroups=list(Fresh="Freshwater",Marine="Marine")so that i get interval plots without my need to change this line of code in my code not related to alligator project?
regards

    On Saturday, October 17, 2020, 9:49:38 AM PDT, Brian Stock <notifications@github.com> wrote:  
 
 


Closed #254.

**Comment by jrfrun** [comment]
Brian
just to clarify, I am trying to automate the code to run a model and with the other graphs, that the interval plot be one of those graphs created automatically.  

I use the alligator example since that is the one you created.  But my need is for automating the code on a separate project not related to the alligator one.  


yes I could manually modify the code line  groups=list(Fresh="Freshwater",Marine="Marine")for my specific project, but would like to put information inside the list part of the code line to handle that interval plot automatically
hope this is clearer
regrds
Joe 

    On Monday, October 19, 2020, 7:31:30 AM PDT, joe ferreira <jrfrun@yahoo.com> wrote:  
 
  Brian 

Thanks for your response but either I dont understand what you tell me or it does not work
I am trying to "automate" my code without having to manually change things.  So when I run the alligator model i can use the following code and it works
original = combine_sources(jags.1, mix, source, myprior,
            groups=list(Fresh="Freshwater",Marine="Marine")) 
plot_intervals(original,toplot="fac1",savepdf=TRUE,filename='intervals')  


but this requires me to manually change the code part groups=list(Fresh="Freshwater",Marine="Marine")

i would like to modify my code so that it automatically plots the intervals so not sure how to modify 
 groups=list(Fresh="Freshwater",Marine="Marine")
i dont know how to interpret your suggestion, when i try 

y = as.list(source$source_names)
original = combine_sources(jags.1, mix, source, myprior,
            groups=list(y)) 
plot_intervals(original,toplot="fac1",savepdf=TRUE,filename='intervals')  

as i think you are telling me, it does not work
how could i changegroups=list(Fresh="Freshwater",Marine="Marine")so that i get interval plots without my need to change this line of code in my code not related to alligator project?
regards

    On Saturday, October 17, 2020, 9:49:38 AM PDT, Brian Stock <notifications@github.com> wrote:  
 
 


Closed #254.

**Comment by brianstock** [comment]
What you've typed does not match what I said to try... I was showing you the intermediate steps so you could understand what is happening.

```
y = as.list(source$source_names)
names(y) = source$source_names # or whatever names you want
original = combine_sources(jags.1, mix, source, myprior, groups=y)
```

**Comment by jrfrun** [comment]
Brian
Sorry for not understanding your original response.  

Thank you very much for your help
regards

    On Monday, October 19, 2020, 9:21:10 PM PDT, Brian Stock <notifications@github.com> wrote:  
 
 


What you've typed does not match what I said to try... I was showing you the intermediate steps so you could understand what is happening.
y = as.list(source$source_names)
names(y) = source$source_names # or whatever names you want
original = combine_sources(jags.1, mix, source, myprior, groups=y)
