### ISSUE TITLE
could not find function "mixsiar_gui"

### ISSUE THREAD

**Issue by sohel-ecohy** [brianstock/MixSIAR#255]
I am trying to install MixSIAR but getting the following errorr text: 
> library(MixSIAR)
> mixsiar_gui()
Error in mixsiar_gui() : could not find function "mixsiar_gui"

Can you please help?
thankks

**Comment by AndrewLJackson** [comment]
Hi

The cause of this error and work around is posted on the landing page README document for this repository under “installation “

Best wishes
Andrew



––––––––––––

Dr Andrew Jackson, PhD, FTCD
Associate Professor
School of Natural Sciences, Department of Zoology
Trinity College Dublin, the University of Dublin
Dublin 2, Ireland.

+353 1 896 2728 | a.jackson@tcd.ie<mailto:a.jackson@tcd.ie>

Twitter: @yodacomplex<https://twitter.com/yodacomplex>
http://www.tcd.ie/Zoology/research/research/theoretical/AndrewJackson.php

Trinity College Dublin, the University of Dublin is ranked 1st in Ireland
and in the top 100 world universities by the QS World University Rankings.


On 26 Oct 2020, at 08:28, sohel-ecohy <notifications@github.com> wrote:

﻿

I am trying to install MixSIAR but getting the following errorr text:

library(MixSIAR)
mixsiar_gui()
Error in mixsiar_gui() : could not find function "mixsiar_gui"

Can you please help?
thankks
