### ISSUE TITLE
Output truncation issue

### ISSUE THREAD

**Issue by mwcmiller1** [brianstock/MixSIAR#259]
After running the JAGS model, the output produces a limited number of results (one per factor and source). In my case, it truncates at 119 outputs, deleting ~500 more. I am trying to assess sources of individual mixtures, so it is important to calculate values for each mixture, rather than simply assess the overall mean input. 

It seems as though this is an option within the JAGS model output parameters, but I can't find out how to get the output to either A) print all outputs without truncating, or B) saving the entire results section as an external file (TXT or CSV, ideally). 

This seems to be an error in how the results are exported, not necessarily in the model structure. I am running a model of 8 potential sources for ~800 individual mixtures. I get the issue even in subsets of ~50 mixtures, so the total sample number is not the issue, it would seem. 

Any suggestions on where to start? Thanks!

**Comment by brianstock** [comment]
More information is needed about your data and model setup. Please post your R code, as well as the first couple rows of your mix, source, and discr data files.

By individual, do you mean individual data points? Or do you have multiple data points per individual? Are you sure that individual is in the model?

I am skeptical it is an issue with how the results are exported. An example with diet proportions for 160 individuals: https://github.com/brianstock/MixSIAR/issues/209.

You can always extract the proportion estimates from the R objects directly. See http://brianstock.github.io/MixSIAR/articles/modify_output.html.

**Comment by mwcmiller1** [comment]
Thanks for the suggestions, Brian. As it turns out, my issue wasn't a problem in MixSIAR, but in R itself. I had to add a line of code to ensure that the printed output was long enough to fit the amount of data in the results: 

options(max.print=99999999)

It might be beneficial for users to add this option to ensure this issues doesn't show up for anyone else. Could it be implemented into the package?

**Comment by brianstock** [comment]
Glad to hear you sorted it out!

I don't think so - it's generally frowned upon for a package to modify options like that. But thanks for reporting it. Now someone else who runs into the problem can find the answer here.
