### ISSUE TITLE
Warnings from isospace plot (per mille symbol)

### ISSUE THREAD

**Issue by brianstock** [brianstock/MixSIAR#26]
Since jjvenky modified isospace plot to print per mille character (https://github.com/brianstock/MixSIAR/pull/12), the plot will appear nicely in the R graphics device, but the version saved as PDF has (...) instead of per mille.

Also, warnings are produced for each line with the \u2030 character.

**Comment by jjvenky** [comment]
Oh, that's interesting.

I used \u2030 to make the permil character in the figures in my PLoS ONE paper: http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0118954

Since ggplot2 is used to make the plots in MisSIAR, try ggsave() to save the figures. That's how I generated the figures in that paper with the permil character intact. See the R code in here: https://github.com/jjvenky/Global-N2O-Ellipses/blob/master/figures%20for%20N2O%20isotopes%20ellipses.R

Something like: ggsave(filename = "myfigure.pdf", height = 5, width = 7, units = "in")

**Comment by brianstock** [comment]
Trying to make the PDFs with `ggsave()` still throws the warnings and the plot ends up with `(...)` in the label instead of the per mille.  On my machine at least, switching to `cairo_pdf` works, I may try that.

**Comment by jjvenky** [comment]
Hmmm. How do these work for you?

library(ggplot2)
library(Cairo)
qplot(1,1) +
   labs(x = expression(paste("\u03b4" ^15, "N-N" [2], "O (\u2030 air N" [2], ")")), 
       y = expression(paste("\u03b4" ^18, "O-N" [2], "O (\u2030 VSMOW)")) )
ggsave(filename = "myfigure1.pdf", width = 7, height = 5, units = "in")
cairo_pdf(filename = "myfigure2.pdf", width = 7, height = 5)
dev.print(cairo_pdf, "myfigure3.pdf")

**Comment by brianstock** [comment]
No, yes, and yes - looks like the fonts work with Cairo, but not the default pdf device. We have Windows and Mac computers in the lab, so I'll test this on those before updating the code (already made the switch to `cairo_pdf` on the develop branch).
```
library(ggplot2)
# library(Cairo) # don't actually need to load Cairo, cairo_pdf is in grDevices, in base R
p <- qplot(1,1) +
	labs(x = expression(paste("\u03b4" ^15, "N-N" [2], "O (\u2030 air N" [2], ")")),
			y = expression(paste("\u03b4" ^18, "O-N" [2], "O (\u2030 VSMOW)")) )
print(p)
```
Method 1 doesn't work for me... ggsave saves the plot as PDF, but with (...) instead of per mille, and lots of warnings:
```
ggsave(filename = "myfigure1.pdf", width = 7, height = 5, units = "in")
```
Method 2 works, using cairo_pdf:
```
cairo_pdf(filename = "myfigure2.pdf", width = 7, height = 5)
print(p) # cairo_pdf only opens the graphics device, need to print the plot
dev.off() # and need to close the device
```
Method 3 works too - first print the plot, then dev.print copies it to PDF
```
print(p)
dev.print(cairo_pdf, "myfigure3.pdf")
```
