### ISSUE TITLE
A problem with mixsiar GUI opening

### ISSUE THREAD

**Issue by Tahsin78** [brianstock/MixSIAR#263]
Hi MixSIAR users

I am new to R and MIXSIAR package. I followed the MixSIAR GUI installation step by step on Windows 10, x64. Everything went right, but at the end I got this Error **mixsiar_gui() : could not find function "mixsiar_gui"** and GUI didn't open. Please guide me to solve the problem.

**Comment by brianstock** [comment]
The [install instructions](https://github.com/brianstock/MixSIAR) state that the GUI is no longer in the MixSIAR package. Please see the following and post under https://github.com/brianstock/MixSIARgui/issues.
https://github.com/brianstock/MixSIAR/issues/224
https://github.com/brianstock/MixSIAR/issues/255
https://github.com/brianstock/MixSIAR/issues/261
