### ISSUE TITLE
Should source values change when creating isoplots?

### ISSUE THREAD

**Issue by naalipalo** [brianstock/MixSIAR#264]
I was trying to create plots that are publishable quality, refine and customize the symbiology etc. and noticed a pretty significant difference between the plot that is produced by MixSIAR script and when I write my own script in regards to plotting the source data.  When I run the script and look at the autogenerated plot, the source data is shifted from the actual initial input values.  My input is 
`

Sources | Meand13C | SDd13C | Meand15N | SDd15N | n
-- | -- | -- | -- | -- | --
Anthropogenic | -17.74 | 2.28 | 2.90 | 0.58 | 10
Aquatic | -20.45 | 0.67 | 12.98 | 2.24 | 5
Plants | -27.41 | 0.75 | -1.93 | 1.68 | 7
Meat | -24.09 | 1.73 | 3.63 | 1.91 | 17

` 
However, when I look at the isoplot from the model, it plots all of the means "higher" than the values I input.  I realize from the manual that MixSIAR is doing something to those values to account for the variance.  Which I assume this is why if you look at the plot produced by the MixSIAR scripts, Aquatic is plotted somewhere around 17 for a mean +/- 2SD for Nitrogen and -18 for Carbon and Anthropogenic now falls somewhere around 7.5 for N and -15 for C.  Should it be changing those input values so drastically?

 How can I extract those values so I can plot the data correctly?  OR do you have some example scripts that could help?  Right now my thought was to plot the source value from my input file and overlay the consumer values, however my personal attempt is creating a very different graph.

https://user-images.githubusercontent.com/45045924/103391740-66e28280-4ac7-11eb-84a0-a7cfa3c571bb.mp4

**Comment by ChrisHarrod** [comment]
I might be missing something, but isn't MixSIAR just adjusting the raw data for fractionation?

**Comment by brianstock** [comment]
As stated in the manual, MixSIAR adjusts the source data by the TDF means and variances. This is the relevant geometry to check to make sure your mixing model makes sense (consumers within source polygon), not the raw values. If you want to plot the raw values you can... but if I were reviewing a mixing model paper I would want to see the plot with source values adjusted by TDF, at least as a supplement. See section 3.1.4.

![Screenshot from 2020-12-31 10-31-57](https://user-images.githubusercontent.com/5124211/103416289-f9c8fe80-4b53-11eb-9dc5-38c52fe0504e.png)

**Comment by naalipalo** [comment]
Thank you for replying,I figured it was doing something to the source values.  Is there a way to extract those adjusted values and the SD or SE around those values from the MixSIAR object so I can create my own plots?  I am trying to remove the grid lines, generate a different legend, move the legend, change the shapes and remove the right and top bounding box lines etc. for publication in a journal.  I cannot use the default plot according to the reviewers/editor of the journal.
~K

Not all those who wander are lostK. L. Nicholson PhD
Certified Wildlife Biologist®
 

    On Thursday, December 31, 2020, 06:39:43 AM AKST, Brian Stock <notifications@github.com> wrote:  
 
 


As stated in the manual, MixSIAR adjusts the source data by the TDF means and variances. This is the relevant geometry to check to make sure your mixing model makes sense (consumers within source polygon), not the raw values. If you want to plot the raw values you can... but if I were reviewing a mixing model paper I would want to see the plot with source values adjusted by TDF, at least as a supplement. See section 3.1.4.

**Comment by brianstock** [comment]
Yes, you can make all the modifications you listed by having `plot_data` return the `ggplot2` object (set `return_obj = TRUE`). See [?plot_data](http://brianstock.github.io/MixSIAR/reference/plot_data.html). For example, to remove the gridlines:

```
g <- plot_data(filename, plot_save_pdf=F, plot_save_png=F, mix, source, discr, return_obj = TRUE)
g + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())
```

**Comment by naalipalo** [comment]
Thanks, I was trying to use this in the loop and keep getting errors. I wanted to move the legend slightly off so it wasn't overlapping the axis line, and eventually wanted to change colors/shapes/sizes of the scattered points but figured first step is to just get it to produce a graph like you suggest it should
 for(mod in 1:n.mod){  # create sub-directory and move into it  mainDir <- getwd()  subDir <- paste0("model_", mod)  dir.create(file.path(mainDir, subDir), showWarnings = FALSE)  setwd(file.path(mainDir, subDir))    # load source data  source[[mod]] <- load_source_data(filename=source.filename,                                    source_factors=NULL,                                    conc_dep=FALSE,                                    data_type="means",                                    mix[[mod]])  # load TEF data  discr[[mod]] <- load_discr_data(filename=discr.filename, mix[[mod]])    # isospace plot  plot_data(filename=paste0("isospace_plot_", mod),            plot_save_pdf=FALSE,            plot_save_png=TRUE,            mix[[mod]], source[[mod]], discr[[mod]],             return_obj = TRUE)  + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())  + theme(legend.position=c(-25.9,15))+  ggsave(file=paste0("plot_", mod,".png"), dpi=300)  
The various errors depending on how I tweak the code are things like:
Error: Cannot use `+.gg()` with a single argument. Did you accidentally put + on a new line?
OR If I use the code like you suggest of g<- plot_data(filename=paste0("isospace_plot_", mod),....... 
Error: Can't add `g` to a ggplot object.

For some reason I can get it to save a plot...but it looks awful. Font goes terribly small, shifts the margins, and just makes a mess

    On Monday, January 4, 2021, 02:46:50 PM AKST, Brian Stock <notifications@github.com> wrote:  
 
 


Yes, you can make all the modifications you listed by having plot_data return the ggplot2 object (set return_obj = TRUE). See ?plot_data. For example, to remove the gridlines:
g <- plot_data(filename, plot_save_pdf=F, plot_save_png=F, mix, source, discr, return_obj = TRUE)
g + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())
