### ISSUE TITLE
I can't get this done.

### ISSUE THREAD

**Issue by Vallvip** [brianstock/MixSIAR#265]
When I try to access the MixSIAR library it returns this message:

Erro: package or namespace load failed for ‘MixSIAR’ in inDL(x, as.logical(local), as.logical(now), ...):
impossible to load shared object 'C:/Program Files/R/R-3.6.3/library/stats/libs/x64/stats.dll':
  LoadLibrary failure:  The specified module could not be found.

**Comment by ericward-noaa** [comment]
Did you recently upgrade to R 4.0? There seems to be something going on with the versions. There's similar threads linked below - but it seems like deleting R / RStudio and doing clean installs of both should solve the problem:
https://stackoverflow.com/questions/61588561/base-packages-unavailable-after-updating-r
