### ISSUE TITLE
Are my data in the mixing polygon?

### ISSUE THREAD

**Issue by HendrikSchultz** [brianstock/MixSIAR#266]
Hi Brian,

I have posted on another Matter regarding this dataset before. 

About my data and model: I am using the MixSiar package to estimate diet proportions in a seabird. I have 68 consumer individuals some of which have been sampled once, twice and three times adding up to approx. 100 samples. I have 6 resources 3 of which I have grouped a priori resulting in 4 sources. I use a two tracer system (d13C, d15N). I would like to test for sex differences and have therefore included 'sex' as a fixed effect. Since I have multiple samples from some individuals I have included 'individual' as a random effect. I have included an isospace plot (females are in red, males in blue):

![CN plot MixSiar](https://user-images.githubusercontent.com/17837279/104852491-2e182980-5960-11eb-87fd-24aba778baf4.jpg)

I have submitted these data to a journal and got the question by one of the reviewers as to whether my data is within the mixing polygon. I see that many studies use Smith et 2013 al to test for this so I quickly ran the analysis on my data set. Unfortunately, with my current choice of TDFs and associated standard deviation, several data points ~10% fall outside of what Smith et al consider the mixing polygon (ie the 95% contour). 

However, I read in this forum that MixSiar actually just assumes that the sample means are in the mixing polygon, which I believe would be true for my data looking at the supplied isoplot.

My question is whether you think that the assumption that the data are in the mixing polygon are fulfilled? 

IF yes, how can I best explain this to the reviewer - given my model (sex as fixed factor, ID as random effect), could I plot both means for males and females in the isospace plot rather than individual values? Is there a reference in the literature I could provide re that Mixsiar only assumes sample means are in the mixing polygon?

If my data are indeed not in the mixing polygon, I could try a different set of TDFs, but I'd prefer not to change the model especially if it looks 'OK' to you from a modellers perspective.

Thank you very much in advance for getting back to me about this Brian, I really appreciate your help. Please let me know in case you need additional information.

All the best,

Hendrik

**Comment by ericward-noaa** [comment]
Yes, because of the compositional nature of these problems, all mixing models force that the mixture mean to be within the mixing polygon (so I don't think you need a reference). In addition to plotting the isoplot (your example plot), you could plot the raw means of the data, or posterior distribution of the estimated mixture, with some amount of uncertainty (e.g. 95% credible intervals).

**Comment by HendrikSchultz** [comment]
Dear Eric,

thank you very much for your comment, I really appreciate your quick response. I hope you don't mind me asking one further question. It appears that many studies follow Smith et al. 2013 to test whether all **individuals** fall within the mixing polygon (the 95% contour) rather than the **means**, is this appropriate? 

My aim is to satisfy the reviewer that the mixing model assumptions (consumer must fall inside this mixing polygon) are met by my data, although they don't meet the often cited test by Smith et al. 2013 (ie all **individuals** fall in the mixing polygon).

Smith J.A., Mazumder D., Suthers I.M., and Taylor M.D. 2013. To fit or not to fit: evaluating stable isotope mixing models using simulated mixing polygons. Methods Ecol. Evol. 4(7): 612–618.

**Comment by ericward-noaa** [comment]
I guess I'd respond that the Smith et al. approach is a self-descibed as estimating the "_probability that a consumer's isotopic signature can be explained by the proposed model_". In general, I wouldn't run frequentist diagnostics before fitting a Bayesian model -- there's plenty of diagnostics within Bayesian models that would signal identifiability issues, and lack of convergence. I also don't think the Smith et al. approach has been updated to represent existing for mixing models, using MixSIAR and the residual error structure described in Stock and Semmens, https://esajournals.onlinelibrary.wiley.com/doi/pdf/10.1002/ecy.1517

**Comment by HendrikSchultz** [comment]
Thank you very much for your help Eric, your comments were very helpful!

All the best,

Hendrik
