### ISSUE TITLE
Replicates as random effect?

### ISSUE THREAD

**Issue by AnjaSchmutz** [brianstock/MixSIAR#267]
Hi!

I am trying to calculate the importance of soil water in specific soil depths (see e.g. https://doi.org/10.1016/j.scitotenv.2017.07.133). The d2H and d18O in the soil depths are my sources, the plants are my mixtures. My plants were grown in different cultures (monocultures and mixed cultures, i.e. multiple species grown together) and I have from each culture three replicates. I have now defined these replicates (i.e. the ID of this specific species in this specific culture) as random effect and the species_culture (factor combining species and the culture) as fixed effect. My question now: Are the replicates as random effect appropriate?

I also have a question about the summary statistics output from random effects: The estimated proportion of the fixed effects are on the bottom, followed by the estimated proportion of the random effects. But when I am only interested in the fixed effects, do I just take the estimated proportion of the fixed effect and skip this from the random effect? In which case would I need the estimated proportions of the random effect? And what does the SD from the random effect on the top tell me exactly?

A lot of questions, sorry for that. Hope they are intelligible.
Thanks in advance!

Cheers,
Anja

**Comment by BingxiangLi** [comment]
I also have many questions about MixSIAR. First the GUI is not used in my machine. When i installed the script version, i find i can't  attach my data to codes. what should i do?

**Comment by brianstock** [comment]
1. Yes, random effects are appropriate for a "nuisance" variable you're not really interested in (implied by your use of "replicate").
2. I think in your case with `species_culture` as fixed effect (you care about) and `replicate` as random effect (you don't really care about the differences by replicate), just look at the proportions for `species_culture`. You'd look at the random effect proportions if you were interested in them... like in the [wolves ex](http://brianstock.github.io/MixSIAR/articles/wolves_ex.html).
3. Random effects in MixSIAR let you say the replicates (within a given level of `species_culture`) vary for some reason. The proportions of each replicate are assumed to follow a normal distribution with mean = the `species_culture` mean and estimated SD.
