### ISSUE TITLE
C and N concentrations differ among prey inputs

### ISSUE THREAD

**Issue by klato1** [brianstock/MixSIAR#270]
Hi Brian,

Some of my input prey data differ in their elemental concentrations of C and N and I am incorporating both plant and animal material as sources. Is there an option to incorporate these differences in the model like there is with 'simmr'? Is this what the option "concentration dependent" in the load_source_data() is for?

Additionally, I am working with the combine_sources() funtcion and looking to get some nice posterior plots of the new groups I created here. However, I keep running into an error when I try putting the combined_sources output into output_JAGS. Do you know how I am supposed to set that up? Here's what I have now with the associated error:

output_JAGS(combined$jags.1, mix = combined$mix, source = combined$source.new, output_options=list(
  summary_save = TRUE,# Save the summary statistics as a txt file?
  summary_name = "species_model_summary_statistics",    # If yes, specify the base file name (.txt will be appended later)
  sup_post = TRUE,                       # Suppress posterior density plot output in R?
  plot_post_save_pdf = TRUE,              # Save posterior density plots as pdfs?
  plot_post_name = "species_model_posterior_density",   # If yes, specify the base file name(s) (.pdf/.png will be appended later)
  sup_pairs = FALSE,                      # Suppress pairs plot output in R?
  plot_pairs_save_pdf = TRUE,             # Save pairs plot as pdf?
  plot_pairs_name = "pairs_plot",         # If yes, specify the base file name (.pdf/.png will be appended later)
  sup_xy = TRUE,                         # Suppress xy/trace plot output in R?
  plot_xy_save_pdf = TRUE,                # Save xy/trace plot as pdf?
  plot_xy_name = "species_xy_plot",               # If yes, specify the base file name (.pdf/.png will be appended later)
  gelman = TRUE,                          # Calculate Gelman-Rubin diagnostic test?
  heidel = FALSE,                          # Calculate Heidelberg-Welch diagnostic test?
  geweke = TRUE,                          # Calculate Geweke diagnostic test?
  diag_save = TRUE,                       # Save the diagnostics as a txt file?
  diag_name = "species_diagnostics",              # If yes, specify the base file name (.txt will be appended later)
  indiv_effect = FALSE,                   # Is Individual a random effect in the model? (already specified)
  plot_post_save_png = TRUE,             # Save posterior density plots as pngs?
  plot_pairs_save_png = TRUE,            # Save pairs plot as png?
  plot_xy_save_png = FALSE,
  diag_save_ggmcmc = FALSE))

Error in dimnames(x) <- dn : 
  length of 'dimnames' [1] not equal to array extent

**Comment by brianstock** [comment]
1. Yes, you are describing concentration dependence. This is shown in the [Geese example](http://brianstock.github.io/MixSIAR/articles/geese_ex.html). Check out `geese_sources.csv`.
2. Check out the documentation for `combine_sources`: http://brianstock.github.io/MixSIAR/reference/combine_sources.html#value. `combined$jags.1` is the **input** rjags object with the original sources. `combined$post` is the matrix of posterior draws with the new source grouping (`combined$source.new`). You can create posterior plots using `combined$post`.
