### ISSUE TITLE
How to account for variation of known prior data?

### ISSUE THREAD

**Issue by amchiapella** [brianstock/MixSIAR#271]
I have extensive stomach content data for my consumers, but the data is incredibly variable. Is there a way to include, e.g., the sd of my diet data when adding the known priors to my model?

**Comment by ericward-noaa** [comment]
See this recent paper for a worked example, using some of the same data in the MixSIAR manual

https://www.int-res.com/abstracts/meps/v649/p189-200/

**Comment by amchiapella** [comment]
Thank you! I finally got a copy of the paper and this approach looks like it will resolve my question
