### ISSUE TITLE
mixsiar_gui()

### ISSUE THREAD

**Issue by ESSANBRI** [brianstock/MixSIAR#273]
> mixsiar_gui()
Error in mixsiar_gui() : could not find function "mixsiar_gui"

What is the solution?

**Comment by brianstock** [comment]
Please read the documentation here: https://github.com/brianstock/MixSIAR#installation. The GUI has been split off into it's own package, [MixSIARgui](https://github.com/brianstock/MixSIARgui). The GUI works on my machine (on Ubuntu) and I cannot help troubleshoot installation errors on Windows or Mac. You can try what others have found to work and contribute to the discussion here: https://github.com/brianstock/MixSIARgui/issues.

In order for others to help you, you'll need to share more information, a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).
