### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by ESSANBRI** [brianstock/MixSIAR#274]
library(rgtk2) error in indl(x, as.logical(local), as.logical(now), ...) : unable to load shared object 'c:/r/r-3.6.3/library/rgtk2/libs/x64/rgtk2.dll': loadlibrary failure: %1 is not a valid win32 application.

**Comment by ESSANBRI** [comment]
library(rgtk2) error in indl(x, as.logical(local), as.logical(now), ...) : unable to load shared object 'c:/r/r-3.6.3/library/rgtk2/libs/x64/rgtk2.dll': loadlibrary failure: %1 is not a valid win32 application.

**Comment by brianstock** [comment]
First, `rgtk2` is not a valid package name. It's `RGtk2`: https://cran.r-project.org/web/packages/RGtk2/index.html.

Second, `RGtk2` is not required for MixSIAR to work. You must be trying to install the GUI, which is a separate package. See https://github.com/brianstock/MixSIARgui.

**Comment by ESSANBRI** [comment]
I want to instal Mixsiar gui 
first I instal 
install.packages(c("gWidgets", "RGtk2", "gWidgetsRGtk2", "devtools"))

second I library (RGtk2)  but not working give this message 
library(RGtk2)

Error in inDL(x, as.logical(local), as.logical(now), ...) : 
  unable to load shared object 'C:/Users/TOSHIBA/Documents/R/win-library/4.0/RGtk2/libs/x64/RGtk2.dll':
  LoadLibrary failure:  %1 is not a valid Win32 application.

trying URL 'http://ftp.gnome.org/pub/gnome/binaries/win64/gtk+/2.22/gtk+-bundle_2.22.1-20101229_win64.zip'
Content type 'application/zip' length 25830230 bytes (24.6 MB)
downloaded 24.6 MB

Learn more about GTK+ at http://www.gtk.org
If the package still does not load, please ensure that GTK+ is installed and that it is on your PATH environment variable
IN ANY CASE, RESTART R BEFORE TRYING TO LOAD THE PACKAGE AGAIN
Warning messages:
1: Failed to load RGtk2 dynamic library, attempting to install it. 
2: In dir.create(config_path, recursive = TRUE) :
  'C:\Users\TOSHIBA\Documents\R\win-library\4.0\RGtk2\gtk\x64\etc\gtk-2.0' already exists

**Comment by AndrewLJackson** [comment]
﻿Hi

The short answer and standard advice is just don’t. I strongly advise you use the script version and not the gui. The gui will not install from cran, and it is becoming increasingly difficult to support it.

Best wishes
Andrew

--

Dr Andrew Jackson, PhD, FTCD
Associate Professor
Irish Research Council Laureate
School of Natural Sciences, Department of Zoology
Trinity College Dublin, the University of Dublin
Dublin 2, Ireland.

+353 1 896 2728 | ***@***.******@***.***>
Twitter: @yodacomplex<https://twitter.com/yodacomplex>
http://www.tcd.ie/Zoology/research/<http://www.tcd.ie/Zoology/research/groups/jackson/>groups/jackson/

From: ESSANBRI ***@***.***>
Date: Wednesday, 26 May 2021 at 23:20
To: brianstock/MixSIAR ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [brianstock/MixSIAR] Please help (#274)

I want to instal Mixsiar gui
first I instal
install.packages(c("gWidgets", "RGtk2", "gWidgetsRGtk2", "devtools"))

second I library (RGtk2) but not working give this message
library(RGtk2)

Error in inDL(x, as.logical(local), as.logical(now), ...) :
unable to load shared object 'C:/Users/TOSHIBA/Documents/R/win-library/4.0/RGtk2/libs/x64/RGtk2.dll':
LoadLibrary failure: %1 is not a valid Win32 application.

trying URL 'http://ftp.gnome.org/pub/gnome/binaries/win64/gtk+/2.22/gtk+-bundle_2.22.1-20101229_win64.zip'
Content type 'application/zip' length 25830230 bytes (24.6 MB)
downloaded 24.6 MB

Learn more about GTK+ at http://www.gtk.org
If the package still does not load, please ensure that GTK+ is installed and that it is on your PATH environment variable
IN ANY CASE, RESTART R BEFORE TRYING TO LOAD THE PACKAGE AGAIN
Warning messages:
1: Failed to load RGtk2 dynamic library, attempting to install it.
2: In dir.create(config_path, recursive = TRUE) :
'C:\Users\TOSHIBA\Documents\R\win-library\4.0\RGtk2\gtk\x64\etc\gtk-2.0' already exists
