### ISSUE TITLE
Installation problem with MixSIAR Gui

### ISSUE THREAD

**Issue by Ucaslinda** [brianstock/MixSIAR#278]
When I install gWidgets and gWidgetsRGtk2, there is always warning message that gWidgets, gWidgetsRGtk2 are not available for R version 4.0.5. Therefore, I uninstall R version 4.0.5 and try to use R version 3.5.2.. Warning message also inform me that these two packages are not avaialbe for version 3.5.2.

So if it is possible, could you please tell me how can I solve it.

Thank you very much and I'm looking forward to your reply.

**Comment by Ucaslinda** [comment]
I have run the text according to MixSIAR mannual step by step. However, the last step "mixSIAR_gui ()", when I run it. It always inform me that “”Error in mixsiar_gui(): function mixsiar_gui don not exist“
”

**Comment by sblumens** [comment]
Indeed!  I had the very same problems today.  Tried new & old versions of R;  also having problems with accepting rtools40.

**Comment by Ucaslinda** [comment]
> Indeed! I had the very same problems today. Tried new & old versions of R; also having problems with accepting rtools40.

The rtools40 coule be installed in 4.0.5 version of R, I had succesfully install it.
 
However, I can only use R script and could not install sucessfully mixSIAR_gui untill now.

**Comment by AndrewLJackson** [comment]
Hi. My very sincere appeal and suggestion is to give up on using the gui and just use the script interface. The gui code no longer installs via CRAN as it is not supported. Using scripts is much more reproducible and for that aspect alone far superior. - Andrew

**Comment by Ucaslinda** [comment]
> Hi. My very sincere appeal and suggestion is to give up on using the gui and just use the script interface. The gui code no longer installs via CRAN as it is not supported. Using scripts is much more reproducible and for that aspect alone far superior. - Andrew

Thanks a lot for your reply!

**Comment by brianstock** [comment]
I agree with Andrew - use the script version.

If you really want to try... the `mixsiar_gui()` function is no longer in the `MixSIAR` package, I had to move it to a separate `MixSIARgui` package. See:
https://github.com/brianstock/MixSIAR/issues?q=is%3Aissue+mixsiargui+
https://github.com/brianstock/MixSIARgui
