### ISSUE TITLE
Interpretation of LOO results and proportional contributions

### ISSUE THREAD

**Issue by naalipalo** [brianstock/MixSIAR#281]
I just need assistance with the proper approach to interpretation of results. I ran 9 models on my data and only 2 of the models have any weight. One of them is 0.98, the other is 0.02. The model with the most weight is with size as a continuous variable and the 2 categorical geographic locations, the other model is geographic location and treatment type (3 categorical variable). Also, within either model, within the 4 food groups, 1 group is on average <=2% of the proportional diet contribution. 

In the interpretation, should there be any time invested in discussing the implications of both models? or just the one that holds 98% of the explanatory value. As in, there is some evidence though weak that treatment may be playing a role?  Therefore, we can spend a great amount of time on that model, plot results from that model and extrapolate from that?  The continuous variable is harder to plot (i don't have great code) and ends up looking awful and is kind of confusing.

Since location is within both models, I could possibly run the modeling within both locations? I thought I read somewhere in one of the papers that this is an option and then we'd compare something...but its not an exact comparison because its not all in the same error structure.

In the interpretation of the food types, is 2% something that is in the realm of probable error due to statistical methodologies? Like, the model is going to "force" this to appear because we aren't giving it any other option besides the 4 categories.

Thoughts would be greatly appreciated.

Also, figuring out how to plot the change in proportional food contributions with size by location would be extremely helpful. Im at a total loss there.

**Comment by ericward-noaa** [comment]
I think I'd just focus on the model with the largest weight, but report the difference in LOOIC or ELPD values (or whatever metric you're using), along with the standard errors of those. 

Yes, extracting the continuous covariate effects is pretty confusing for these types of proportional models. I think the Lake example includes a simple demonstration of this, 
https://cran.r-project.org/web/packages/MixSIAR/vignettes/lake_ex.html

If you have the continuous covariate shared among 2 regions, it seems like you want to back transform the estimates for each region / size classes. There's a function called plot_continous_var.R that would be helpful -- either in making the plot, or helping understand the transformations you need to do to generate a custom plot.

**Comment by naalipalo** [comment]
Thanks for your suggestions. I decided to "bin" my continuous variable because I used it in the SIBER isopleth analysis and am getting interesting plots from that.  However, I am looking into the plot_contiuous_var as an option still. Thanks again.
