### ISSUE TITLE
Error message using SIAR

### ISSUE THREAD

**Issue by meganmskinner** [brianstock/MixSIAR#29]
I have getting the error message "Error in siarmcmcdirichletv4(RBT.NT.pred, RBT.NT.prey, RBT.NTdisc, concdep = 0,  : NAs in foreign function call (arg 5)" when I run SIAR with one of my datasets (this is rainbow trout diet to be specific).  

I've examined the data every which way and everything looks fine.  The model runs perfectly for another fish species, but it just won't for this one.  Has anyone else had this issue before?  Looking for helpful advice and suggestions...

Megan

**Comment by brianstock** [comment]
Hi Megan,

Sorry, but I don't maintain SIAR or SIBER - that's primarily Andrew Jackson. You should get a reply here: https://www.facebook.com/pages/SIAR-Stable-Isotope-Analysis-in-R/148501811896914.

Best,
Brian

**Comment by meganmskinner** [comment]
Thanks Brian- I’ll try the Facebook page.

Megan


On Apr 21, 2015, at 4:35 PM, Brian Stock <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Megan,

Sorry, but I don't maintain SIAR or SIBER - that's primarily Andrew Jackson. You should get a reply here: https://www.facebook.com/pages/SIAR-Stable-Isotope-Analysis-in-R/148501811896914.

Best,
Brian

**Comment by AndrewLJackson** [comment]
thanks brian. i picked it up on FB

On 22 April 2015 at 05:12, meganmskinner <notifications@github.com> wrote:

> Thanks Brian- I’ll try the Facebook page.
>
> Megan
>
>
> On Apr 21, 2015, at 4:35 PM, Brian Stock <notifications@github.com<mailto:
> notifications@github.com>> wrote:
>
>
> Hi Megan,
>
> Sorry, but I don't maintain SIAR or SIBER - that's primarily Andrew
> Jackson. You should get a reply here:
> https://www.facebook.com/pages/SIAR-Stable-Isotope-Analysis-in-R/148501811896914
> .
>
> Best,
> Brian
>
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/brianstock/MixSIAR/issues/29#issuecomment-94974799>.
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brianstock/MixSIAR/issues/29#issuecomment-95024069>.
>



-- 
*You can now follow SIAR on Facebook
<http://www.facebook.com/pages/SIAR-Stable-Isotope-Analysis-in-R/148501811896914>
or
try my video podcasts
<http://www.tcd.ie/Zoology/research/research/theoretical/Rpodcasts.php> for
R

Dr Andrew Jackson
Assistant Professor
School of Natural Sciences
Zoology Building, Trinity College Dublin, Dublin 2, Ireland
Tel. + 353 1 896 2728, Fax. + 353 1 677 8094, Email. a.jackson@tcd.ie,
Twitter: @yodacomplex <https://twitter.com/yodacomplex>
http://www.tcd.ie/Zoology/research/research/theoretical/AndrewJackson.php
