### ISSUE TITLE
More on the plots...

### ISSUE THREAD

**Issue by KGurney** [brianstock/MixSIAR#30]
Hello again Brian;

Thanks again for sending the code for the CI boxplots.

I have been trying to work through it with my own data today, and admittedly, I am rather new to R, so forgive me if this is a stupid question.

I am wondering if all the data that you are using in your plots comes out of the "summary_statistics.txt" file? In looking through the GUI directory, I can't find any other objects that look like they contain the posterior chains.

If you have any insights about where I might find the objects that you use to construct your data frames as below, I'd be super grateful.

Thanks again for your help.

kbg

# Get posterior chains into one tidy data frame
attach.jags(jags.1)
post.grass <- data.frame(habitat = "Seagrass",aw = p.fac1[,1,1], bs = p.fac1[,1,2], clam = p.fac1[,1,3], crab = p.fac1[,1,4], fish = p.fac1[,1,5], snail = p.fac1[,1,6])
post.coral <- data.frame(habitat = "Coral",aw = p.fac1[,2,1], bs = p.fac1[,2,2], clam = p.fac1[,2,3], crab = p.fac1[,2,4], fish = p.fac1[,2,5], snail = p.fac1[,2,6])
grass <- post.grass %>% gather(source,value,2:7)
coral <- post.coral %>% gather(source,value,2:7)
all <- rbind(grass,coral)

**Comment by brianstock** [comment]
No worries, not a stupid question.

When you click on the "Run Model" button in the GUI, the output is saved as the ```jags.1``` object in R, within the ```mixsiar``` environment.  If you want to access this in a future R session, you need to save your R workspace, ```save.image("workspacename.RData")```. You can then close R, re-open, and load your previous output with ```load("workspacename.RData")```.

You can see a less-tidy summary using:
```
summary(mixsiar$jags.1)
```
To access the posterior chains, first need to run:
```
attach.jags(mixsiar$jags.1)
```
The posterior chains that exist depend on the model you ran, how many factors (if any) and levels of each factor.  As an example, the wolf dataset has 2 factors (Region, Pack), and they have 3 and 8 levels, respectively.  Factor 1 is stored as ```p.fac1``` and Factor 2 is ```p.fac2```.  They're indexed as ```p.fac1[draws, level, source]```, so ```p.fac1[,1,2]``` is the chain for Region 1 marine mammals.  Sources are indexed alphabetically.  You can then calculate summary stats (i.e. mean, sd, 95% CI) or plot them as you see fit.  E.g.
```
# Calculate the mean of Region 1 Marine Mammals contribution to diet
> mean(p.fac1[,1,2])
[1] 0.1081181
```
And
```
# Histogram of Region 1 Marine Mammals' contribution to diet
hist(p.fac1[,1,2])
```
![region1mm](https://cloud.githubusercontent.com/assets/5124211/7640585/de548538-fa38-11e4-9dfa-9020b21465fb.png)

**Comment by KGurney** [comment]
Awesome!

 

Thank you so much for that explanation – much appreciated.

 

I was able to produce the plots that I wanted, and also learned a few things about R.  Always good to learn new things…

 

Have a great weekend.

 

kbg

**Comment by emilymck** [comment]
I think this is a related question to the above, as I would like to access some of the model output. I want to put credible intervals around the median lines for my sources from a model with a continuous effect. It seems that this is more complex than just pulling out the p.global chains, as the continuous variable is not in the same format in the jags.1 object (i.e. isometric log space)? 

From the code, I can see that the plot_continuous_var.r uses a dataframe with median values spread out over the continuous variable, for each source. Could you give some suggestions as to how to extract credible intervals around these median values for plotting (i.e. with geom_ribbon)? The figure I would like to replicate is something like Fig 5 and Fig 8 in the Parnell et al. 2013 Environmetrics. Thanks for any suggestions.

**Comment by alex-koiter** [comment]
If you do not want to attach the jags object you can also use df <- jags.1$BUGSoutput$sims.matrix. This is my preferred option as I am not a big fan of attach().

**Comment by brianstock** [comment]
Thanks Alex for the tip... CRAN is not a fan of attach either!

**Comment by BrianHayden** [comment]
Hi Brian,
I'm trying to access the posterior chains when I have multiple factors but am having difficulty as the method you provide above seems to be restricted to one factor. For example, in the wolf data above you show how to get the posterior chain for Region 1 marine mammals but how do I obtain the posterior chain for (for example)  Pack 2  Region 1 marine mammals. Am I missing something??

Thanks,

B

**Comment by brianstock** [comment]
Hi Brian,

Sorry... this got buried in vacation emails. If it's still helpful:

Check out the [model description supplement](https://dfzljdn9uc3pi.cloudfront.net/2018/5096/1/articleS1_revised.pdf) to the PeerJ paper, section on "Fixed/random/continuous effects". If fac2 is nested within fac1, as in the wolves example, MixSIAR calculates the fac2 (Pack) proportions of Pack l as:
```
p_l = ILR^{-1}[beta0 + beta1_l + beta2_l]
```
where beta0 is the overall/mean proportion, beta1_l is the fac1 offset for the Region that Pack l is in, and beta2_l is the offset for Pack l.

If fac2 is NOT nested within fac1, the fac2 proportions just don't add the fac1 offset:
```
p_l = ILR^{-1}[beta0 + beta2_l]
```
