### ISSUE TITLE
Isospace plot not to scale

### ISSUE THREAD

**Issue by ncttrinh** [brianstock/MixSIAR#303]
Hi Brian,
Trinh is Trinh. Please help why when I tried to make an Isospace plot, it seems that the plot is not properly made. I can see the legend on top left while the data in bottom right (see attachment below).

Please help on how to fix this. Many thanks, Brian!
![image](https://user-images.githubusercontent.com/84255278/156864822-f3cd7375-30cb-42ea-adf6-fbb14f9fb9ba.png)

**Comment by brianstock** [comment]
Hi Trinh, the issue is that the source labels are offset by +1 for d15N and -1 for d13C, i.e. up and left from the data points. For your data you will need to reduce this offset. See https://github.com/brianstock/MixSIAR/issues/316.
