### ISSUE TITLE
Problems in the output_posteriors function

### ISSUE THREAD

**Issue by brunakliemann** [brianstock/MixSIAR#312]
I'm trying to use the output_posteriors function and there is a warning that the function cannot be found, even when loading the MixSIAR package. Does this function no longer exist?

**Comment by Samzood** [comment]
Hi @brunakliemann, did you find a solution to this? I am having the same issue!

**Comment by cls03** [comment]
Did this get solved? I structured my model according to the vignette. I need to move my legend and found the youtube video Brian explains how to do small modifications if return_object =T. However I can't get it to recognize it. I have output_options <- list(summary_save = TRUE,                 
                       summary_name = "summary_statistics", 
                       sup_post = FALSE,                    
                       plot_post_save_pdf = TRUE,           
                       plot_post_name = "posterior_density",
                       sup_pairs = FALSE,             
                       plot_pairs_save_pdf = TRUE,    
                       plot_pairs_name = "pairs_plot",
                       sup_xy = TRUE,           
                       plot_xy_save_pdf = FALSE,
                       plot_xy_name = "xy_plot",
                       gelman = TRUE,
                       heidel = FALSE,  
                       geweke = TRUE,   
                       diag_save = TRUE,
                       diag_name = "diagnostics",
                       indiv_effect = FALSE,       
                       plot_post_save_png = FALSE, 
                       plot_pairs_save_png = TRUE,
                       plot_xy_save_png = TRUE,
                       diag_save_ggmcmc = TRUE,
                       return_obj = TRUE)

but when I run, g.post  <- output_posteriors(jags.1, mix, source, output_options)
g.post$global, I get the warning, Error object g.post not found. I can't figure out how to solve this.
