### ISSUE TITLE
What does the epsilon values mean? How to interpret?

### ISSUE THREAD

**Issue by brunakliemann** [brianstock/MixSIAR#314]
In the wolves example, epsilon values indicate dietary variations for random factors. My model has no random effects and there is only one fixed (local) effect for two tracers (C and N). If so, what do the epsilon values mean? How to interpret? Can someone help me?

**Comment by brianstock** [comment]
The interpretation of the epsilon values doesn't change if you include fixed/random effects to explain differences in diet by group. In brief, the epsilon = 1 if the consumer tracer variance is as expected given the source variances, if the consumers are sampling from the source tracer distribution exactly once (or at one value). Epsilon < 1 is what you expect if the consumers sample from the source distribution in multiple places. Epsilon > 1 means the consumer tracer variance is greater than expected from the source variance alone - the most likely explanation is that not all consumers have the same diet and there is some other factor influencing diet that's not in the model.

See https://esajournals.onlinelibrary.wiley.com/doi/10.1002/ecy.1517

**Comment by brunakliemann** [comment]
Yeah right, got it. Thank you for replying.
But in the case of my model it generated two epsilon values, epsilon.1 and epsilon.2. What does each epsilon correspond to?

**Comment by brianstock** [comment]
There is an epsilon for each tracer.

**Comment by brunakliemann** [comment]
hmmm ok thanks
