### ISSUE TITLE
IsoSpace plot data labels too far from the data points

### ISSUE THREAD

**Issue by Ciaosu777** [brianstock/MixSIAR#316]
Hi everyone.

I am a beginner in using Rstudio and MixSIAR thus I have no idea how to fix my issue. 
I am using the package mainly to plot the iso space plot between salmon shark and its potential prey animals. However, the data is not as "clean" as I wanted it to be: the labels for each prey animal are quite far from the actual data points, thus making it unclear what data each label represents. Any suggestion/help would be highly appreciated! 

Thanks in advance
![Plottest](https://user-images.githubusercontent.com/106370215/176378468-cc2315b4-e1d7-492a-8271-e89e5ff46b02.jpeg)
.

**Comment by ncttrinh** [comment]
I have the same issue with Ciaosu777, 
but my case is even worse.. 
Brian, I figure it out this is not the legend problem.. it is the label of the sources is offset (too far away) from the datapoints. Could you please help solve this? Please see my data plot below. Thanks.


![image](https://user-images.githubusercontent.com/84255278/181039819-e6eeebea-d8a6-4eb4-bfd6-48d30057aee8.png)

**Comment by ericward-noaa** [comment]
I think these are more ggplot issues than MixSIAR ones -- one fix is that when you call `plot_data()`, you can use the `return_obj = TRUE` argument to return the ggplot object, e.g. `plot_data(..., return_obj = TRUE)` (by default this isn't returned). There's a few SO posts about avoiding overlap with labels like this one that suggests jittering or using ggrepel: https://stackoverflow.com/questions/40542685/how-to-jitter-remove-overlap-for-geom-text-labels

**Comment by ncttrinh** [comment]
Thanks Eric,
My plot g is actually an ggplot2 object now. I will try your suggested link to see if it works. 
My recommendation is if MixSIAR could fix this issue it will be great, so everyone dont need to border the plot issue anymore. And MixSIAR citation will be spiked!! (Even though now it is cited alot). 
I will revert. Thanks.

**Comment by brianstock** [comment]
I don't think this is an issue to fix. It's difficult to make default plots look good for publication in every case, so I assume users will need to modify the code to create publication-ready figures for their situation (changing the position of source labels, legend, etc.). You have 2 options:

1. Directly modify the plot code. The mix/source data plot code is plot_data.R, which calls plot_data_two_iso.R if you have 2 tracers, or plot_data_one_iso.R if you have 1. The default for two isotopes is to shift the source labels left 1 unit and up 0.75, see https://github.com/brianstock/MixSIAR/blob/master/R/plot_data_two_iso.R#L84. Code for one isotope plot is at https://github.com/brianstock/MixSIAR/blob/master/R/plot_data_one_iso.R#L83.
2. Save the ggplot object and then modify, like Eric mentioned.
