### ISSUE TITLE
updates for MixSIAR manual

### ISSUE THREAD

**Issue by AndrewLJackson** [brianstock/MixSIAR#32]
The file "MixSIAR GUI User Manual 1.0.pdf" requires a bit of updating.
(below sent to me by Igor Eulaers)
The manual states the following code:
source('mixsiar.r')
mixsiar()

while in fact it should be updated to:
source('mixsiar_gui.r')
mixsiar_gui()

Then the text about how error is included on fractionation / enrichment correction factors needs some editing so that it is clear that variation can be included, but only via means and standard deviations, and can't be fitted to raw data in the same way source error can be estimated. This is the discussion we recently had with Chris Harrod.

One way to consider facilitating edits to this manual is to upload the raw code for it in e.g. R-markdown  *.Rmd format which is LaTeX friendly. Then we could create pull requests for proposed edits.

**Comment by brianstock** [comment]
Agreed!  Hope to get to this soon.

**Comment by AndrewLJackson** [comment]
cool. thanks. you're far nicer than me btw re that other thread. Ive lost my patience a bit with people of late... and have been egged on somewhat by not-so-innocent bystanders!
