### ISSUE TITLE
Can we use only 3 food sources in MixSIAR? If less than 5 sources, I get an error message when loading the source file.

### ISSUE THREAD

**Issue by EmmiKurosawa** [brianstock/MixSIAR#324]
Can we use only 3 food sources in MixSIAR? If less than 5 sources, I get an error message when loading the source file. Please let me know.

**Comment by brianstock** [comment]
Yes, see the snail example:
https://github.com/brianstock/MixSIAR/blob/master/inst/example_scripts/mixsiar_script_snail.R.
That has only 1 isotope and 2 sources. The alligator ex has 2 sources and 2
isotopes. And some of the other examples have 3 sources, eg wolves.

**Comment by EmmiKurosawa** [comment]
Dear Brian,

Thanks for getting back to me promptly. When I have only two to foursources, I get the following error.

> source <- load_source_data(filename="source_EH_SP_Ui_TEST2022.csv",                            source_factors=NULL, conc_dep=FALSE, data_type="means", mix)

Warning message:In read.table(file = file, header = header, sep = sep, quote = quote,  :  incomplete final line found by readTableHeader on 'source_EH_SP_Ui_TEST2022.csv'


When I make triplicates and have total of 6 sources, the program accepts the source table. Please let me know how I can make it work with just two sources. Below is the source table.

Sources Meand13C        SDd13C  Meand15N        SDd15N  n
Seston  -28.78  0.12    0.99    0.17    5
Water   -30.59  4.37    0.66    2.04    3


Thank you so much for your help!


Emmi Kurosawa


PhD candidate

Dept. of Molecular, Cellular, and Organismal Biology

University of Massachusetts Boston

USA


________________________________

**Comment by brianstock** [comment]
Try reading in your csv without mixsiar, using read.csv(). Sometimes you
have an extra empty line in the CSV file, can open in excel and delete the
(blank) several rows below your data, re-save, and retry. Or maybe there
are extra blank columns - the error says something about readtableheader.

**Comment by EmmiKurosawa** [comment]
Dear Brian,

Thank you for pointing this out. As you said, it was a problem with my file, not MixSIAR. In short, I was able to fix the problem. However, I am writing the following message for those who might have the similar problem in the future.

The error message I get when I load my source data file (it reliably occurs only when I have less than 5 sources) was:
Warning message: In read.table(file = file, header = header, sep = sep, quote = quote, : incomplete final line found by readTableHeader on 'my_data.csv'

This site tells us how to fix the error. https://www.statology.org/r-incomplete-final-line-found-by-readtableheader/. Some other sites also mentioned the same way = Press "enter" the last line in your csv. to insert a blank line. In my case, it did nothing.

But I found that the file was actually loaded correctly despite the warning. So I simply ignored the warning, and proceeded forward with MixSIAR script. I was able to get the source proportions without a problem.
[https://www.statology.org/wp-content/uploads/2022/06/incomp1.jpg]<https://www.statology.org/r-incomplete-final-line-found-by-readtableheader/>
How to Fix in R: incomplete final line found by readTableHeader<https://www.statology.org/r-incomplete-final-line-found-by-readtableheader/>
One warning you may encounter in R is: Warning message: In read.table(file = file, header = header, sep = sep, quote = quote, : incomplete final line found by readTableHeader on 'my_data.csv'
www.statology.org



Emmi Kurosawa


PhD candidate

Dept. of Molecular, Cellular, and Organismal Biology

University of Massachusetts Boston

USA


________________________________

**Comment by EmmiKurosawa** [comment]
Dear Brian,

After running output_JAGS, I often get an error message: “Error in UseMethod("depth"): no applicable method for 'depth' applied to an object of class "NULL", and won't be able to get the output. It’s devastating after 5 hrs of running MCMC. Sometimes if I ignore the error message and repeat the command "output_JAGS", it gives me the output. However, when I run more complicated models, once I get the error message, no matter how many times I repeat the command, the same error message appears. I ran R 4.0.3 on Ventura 13.1 on Mac. Please help me solve this issue.

Kind regards,

-Emmi


Emmi Kurosawa


PhD candidate

Dept. of Molecular, Cellular, and Organismal Biology

University of Massachusetts Boston

USA

**Comment by brianstock** [comment]
Sorry, I haven't seen this before and there isn't enough information here to help...

If your models take 5 hours to run I suggest writing your script so that it saves the fit model object immediately afterward.

R 4.0.3 sounds pretty old (years?). You could try updating R and reinstalling the latest MixSIAR version:
```
install.packages("devtools")
remotes::install_github("brianstock/MixSIAR", dependencies=T)
```

**Comment by EmmiKurosawa** [comment]
Dear Brian,

Thank you for getting back to me.

Could you kindly tell me the code to save the fit model object immediately afterwards?

I was afraid to upgrade R studio, because then I'd have to upgrade all my libraries to work properly. And I was afraid that might introduce unknown complications for running MixSIAR etc. Which R version do you use? Have you come across any complications after upgrading R?

Please let me know.

Kind regards,


Emmi Kurosawa


PhD candidate

Biology Dept.

University of Massachusetts Boston

USA


________________________________

**Comment by brianstock** [comment]
You can either save all objects in your workspace with `save.image()` or save individual objects with `saveRDS`.

https://stat.ethz.ch/R-manual/R-devel/library/base/html/save.html
https://stat.ethz.ch/R-manual/R-devel/library/base/html/readRDS.html

Keeping your version of R (RStudio is less important, just a user interface) and packages updated is a good idea. The current version is 4.2.3 so that is what I use. When developing packages, they are tested in the current R release and the in-progress next version.

R version history: https://cran.r-project.org/bin/windows/base/old/

**Comment by EmmiKurosawa** [comment]
Thanks, Brian.  I will try!


Emmi Kurosawa


PhD candidate

Biology Dept.

University of Massachusetts Boston

USA


________________________________
