### ISSUE TITLE
Problem installing GUI

### ISSUE THREAD

**Issue by Ulagai** [brianstock/MixSIAR#327]
I have installed: R-4.2.2, RStudio-2022.12.0-353, rtools42-5355-5357, JAGS-4.3.1. Windows 10 64 system. Installed MixSIAR.
Decided to install graphical user interface. It turned out that the packages gWidgets, RGtk2, gWidgetsRGtk2 were removed from the CRAN repository. I downloaded them from the archive and tried to install them locally using devtools. gWidgets is installed, but RGtk2 (versions 2.20.34, 2.20.36) is not installed, the following message is displayed:

In file included from ./RGtk2/atk.h:4,
                 from RGtk2/gtk.h:4,
                 from RGtkDataFrame.h:1,
                 from RGtkDataFrame.c:1:
./RGtk2/gobject.h:7:10: fatal error: glib.h: No such file or directory
    7 | #include <glib.h>
      | ^~~~~~~~
compilation terminated.
make: *** [C:/PROGRA~1/R/R-42~1.2/etc/x64/Makeconf:253: RGtkDataFrame.o] Error 1
ERROR: compilation failed for package 'RGtk2'
* removing 'C:/Users/MU513/AppData/Local/R/win-library/4.2/RGtk2'
warning message:
In i.p(...) :
  installing package 'C:/Users/MU513/AppData/Local/Temp/RtmpWmnOtw/file3cfc9492b9b/RGtk2_2.20.36.tar.gz' has non-zero exit status

How to be in this situation?

**Comment by brianstock** [comment]
The GUI had a lot of installation issues and so I moved it to a separate package, see https://github.com/brianstock/MixSIARgui.

I don't recommend spending too much time trying to figure out the install... but if you want you can try the suggestions in the README and here: https://github.com/brianstock/MixSIARgui/issues/1.
