### ISSUE TITLE
ILR slope terms are inconsistent with ggplot visual output

### ISSUE THREAD

**Issue by sydneylwilliams** [brianstock/MixSIAR#331]
Hi Brian,

I'm hoping to gain some clarity around the inconsistency I may be observing between the ILR slope terms and the ggplot visualization outputted by one of my model frameworks. Below is the ggplot object from plot_continuous_var() and then histograms of the ILR slope terms from ilr.cont1[1] and ilr.cont1[2].

![GitHubQuestion](https://user-images.githubusercontent.com/57406969/213771543-6de08946-c484-4099-aaab-d982768273de.svg)

There seems to be a negative correlation between the continuous variable and source 2; however, the ILR slope terms of ilr.cont1[2] are skewing positive, even more so then those of ilr.cont1[1]. I'm hoping to present summary stats (average slope terms and 95% CIs) for sources 1 and 2 along with the visualization but an average value of 0.41 for source 2 does not align with its median line displayed by the ggplot. 

Thank you very much in advance for any clarification on this!! 

All the best,
Sydney

**Comment by brianstock** [comment]
Hi Sydney,

The plot_continuous_var function (left plot) is showing the proportions of sources 1-3, not in ILR space. The relationship between proportions and your continuous variable Density (ILR-space slope terms, ilr.cont1) is estimated in ILR space, then back-transformed to proportion space. The ilr.cont1 don't correspond to sources - there are only 2 of them and 3 sources.

I would be careful saying that there is a negative correlation between Density and source 2... one can easily draw a straight line through that CI.

You have the full posteriors for ilr.cont1[1] and [2] and can present summary stats as you decide.
