### ISSUE TITLE
Concentration dependence meaning in MixSIAR

### ISSUE THREAD

**Issue by ncttrinh** [brianstock/MixSIAR#335]
Hi Brian,

I have a quick question and I am not sure it it is explained clearly elsewhere, including the manual.
Can you explain briefly what "concentration dependent" mean? Does it mean the consumer (or the "sink", if it is a more appropriate word) isotopic value depends on the concentration of the sources? How do you determine if it is dependent or independent? In the Geese example, I can see in the "discrimination" excel file, there are mean +/- SD of the sources, so I assume the "concentration dependent" is related to bioaccumulation, am I correct? 

Thanks hugely for your reply, Brian :)

_Originally posted by @ncttrinh in https://github.com/brianstock/MixSIAR/issues/232#issuecomment-1461126679_

**Comment by ncttrinh** [comment]
Hi Brian,
Not sure if you have any idea on this? Thanks!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! 
Also, on a separated note, looks like you are not working in NOAA now?

**Comment by ncttrinh** [comment]
Anyone has any ideas for my question? Thanks.

**Comment by AndrewLJackson** [comment]
I suggest this paper which outlines the theory and is the model MixSIAR incorporates:

Incorporating Concentration Dependence in Stable Isotope Mixing Models
Donald L. Phillips & Paul L. Koch
Oecologia, Vol. 130, No. 1 (Jan., 2002), pp. 114-125 (12 pages)
https://www.jstor.org/stable/4223146
