### ISSUE TITLE
include sampling precision error into MixSIAR model

### ISSUE THREAD

**Issue by jesmith5** [brianstock/MixSIAR#336]
For every source type and the consumer I ran three replicates of one sample through the mass spac to obtain an analytical precision error term for each source. To check for example homogenous sample prep. Is there any way to include this in the model? 

The terms vary from 0.01 per mil to about 0.4 per mil.

Cheers

**Comment by brianstock** [comment]
You could include 'replicate' as a random effect for the consumer.

For the sources, you could add the additional variance to the TDF/discrimination variance. Think that should work whether you are treating source data as raw or means/SD/n.

**Comment by jesmith5** [comment]
Thanks so much, adding to the TDF variance worked well. 

Cheers!
