### ISSUE TITLE
Your 'iso_names' do not match column names 

### ISSUE THREAD

**Issue by Niemand112233** [brianstock/MixSIAR#338]
Hi,

I created a mixture file 
[Mix_test.csv](https://github.com/brianstock/MixSIAR/files/11037696/Mix_test.csv)

and I wanted to load it with this code:
```

find.package("MixSIAR")

options(max.ptint=10000000)

library(MixSIAR)

mix.filename <- "C:/Users/xxx/Documents/R/Mix_test.csv"

mix <- load_mix_data(filename=mix.filename,
                     iso_names=c("206Pb","207Pb","208Pb"),
                     factors="Lab", 
                     fac_random=FALSE,
                     fac_nested=FALSE,
                     cont_effects=NULL)
```

But I get this error: 
`Error in load_mix_data(filename = mix.filename, iso_names = c("206Pb",  : 
  *** Error: Your 'iso_names' do not match column names in your
        mixture data file (case sensitive). Please check your mix .csv data 
        file and load_mix_data line, then try again. ***`

I copy-pasted the column names; I replaced them with "A", "B", and "C", but this won't work either.

Any ideas?

**Comment by brianstock** [comment]
I get your same error. I think the problem is that your column names start with numbers. When I replace with A, B, C, the data are loaded correctly.

[Mix_test3.csv](https://github.com/brianstock/MixSIAR/files/11130514/Mix_test3.csv)

```
mix.filename3 = 'C://Users//a37789//Documents//mixsiar_help//issue_338//Mix_test3.csv'
mix <- load_mix_data(filename=mix.filename3,
                     iso_names=c("A","B","C"),
                     factors="Lab", 
                     fac_random=FALSE,
                     fac_nested=FALSE,
                     cont_effects=NULL)
```

**Comment by LeahEit** [comment]
Hi, 

I wanna load my data for the MIXIAR model with the following code: 

mix_veg <- load_mix_data(filename=mix_filename_veg,
                          iso_names = c("O","H"),
                          factor = "Site",
                          fac_random = TRUE,
                          fac_nested = FALSE,
                          cont_effects = NULL) 

but always get this error message:
 
Error in load_mix_data(filename = mix_filename_veg, iso_names = c("O",  : 
  *** Error: Your 'iso_names' do not match column names in your
        mixture data file (case sensitive). Please check your mix .csv data 
        file and load_mix_data line, then try again. ***

I renamed the columns several times, but it continues giving me the error code. 
I also tried to do it with the test data set form the previous comment and then it worked. 

Could you help me to solve this problem? 
I would appreciate it a lot! 
Thank you :) 


[Veg_MIXIAR_test.csv](https://github.com/user-attachments/files/16195885/Veg_MIXIAR_test.csv)
