### ISSUE TITLE
Error when using MixSIAR "dot-dot notation was deprecated

### ISSUE THREAD

**Issue by mcaputo3** [brianstock/MixSIAR#340]
I'm getting a lot of warnings when trying to run mixsiar and one of my posterior plots won't load:

Error in UseMethod("depth") : 
  no applicable method for 'depth' applied to an object of class "NULL"
In addition: There were 16 warnings (use warnings() to see them)
1-15: In par(usr) : argument 1 does not name a graphical parameter
16: The dot-dot notation (`..scaled..`) was deprecated in ggplot2 3.4.0.
ℹ Please use `after_stat(scaled)` instead.
ℹ The deprecated feature was likely used in the MixSIAR package.

I am using R-studio most recent version and  R version 4.2.2

**Comment by mcaputo3** [comment]
Warning:
The dot-dot notation (`..scaled..`) was deprecated in ggplot2 3.4.0.
ℹ Please use `after_stat(scaled)` instead.
ℹ The deprecated feature was likely used in the MixSIAR package.
  Please report the issue at <https://github.com/brianstock/MixSIAR/issues>.
---
Backtrace:
     ▆
  1. └─MixSIAR::output_JAGS(jags.test, mix, source)
  2.   ├─base::print(...)
  3.   └─ggplot2:::print.ggplot(...)
  4.     ├─ggplot2::ggplot_build(x)
  5.     └─ggplot2:::ggplot_build.ggplot(x)
  6.       └─ggplot2:::by_layer(...)
  7.         ├─rlang::try_fetch(...)
  8.         │ ├─base::tryCatch(...)
  9.         │ │ └─base (local) tryCatchList(expr, classes, parentenv, handlers)
 10.         │ │   └─base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
 11.         │ │     └─base (local) doTryCatch(return(expr), name, parentenv, handler)
 12.         │ └─base::withCallingHandlers(...)
 13.         └─ggplot2 (local) f(l = layers[[i]], d = data[[i]])
 14.           └─l$compute_aesthetics(d, plot)
 15.             └─ggplot2 (local) compute_aesthetics(..., self = self)
 16.               └─ggplot2:::is_calculated_aes(aesthetics, warn = TRUE)
 17.                 └─base::vapply(...)
 18.                   └─ggplot2 (local) FUN(X[[i]], ...)
 19.                     └─ggplot2:::is_calculated(quo_get_expr(x), warn = warn)
 20.                       └─ggplot2:::deprecate_warn0("3.4.0", what, with, id = "ggplot-warn-aes-dot-dot")

**Comment by brianstock** [comment]
Hi, thanks. I'm not so concerned about the dot dot warnings because they're just warnings, not errors, and shouldn't affect anything (I think, at least they don't for me).

Can you run the examples without errors? 

When do you get that error message?

Do you get the error if you use R on its own instead of RStudio? Looks like that may be a problem: https://github.com/tidyverse/ggplot2/issues/2514.

**Comment by mcaputo3** [comment]
one of my posterior density plots isn't working (just a blank sheet) .. it's only happening in Rstudio.

**Comment by mcaputo3** [comment]
Error in UseMethod("depth") : 
  no applicable method for 'depth' applied to an object of class "NULL"
In addition: There were 15 warnings (use warnings() to see them)

still getting this error in R and Rstudio... none of my posterior plots are working. Think I have a problem with my R install? I tried to reload MixSIAR using the remotes:: but it didn't work either.

**Comment by mcaputo3** [comment]
FYI I fixed this by putting in: options(expressions=500000)

**Comment by paulchittaro-NOAA** [comment]
> options(expressions=500000)

I am experiencing the same issue. mcaputo3 can you give more details as to where you entered 'options(expressions=500000)'. 
Thanks for any help.

**Comment by mcaputo3** [comment]
> > options(expressions=500000)
> 
> I am experiencing the same issue. mcaputo3 can you give more details as to where you entered 'options(expressions=500000)'. Thanks for any help.

Hi Paul, what error are you getting? the depth?

**Comment by paulchittaro-NOAA** [comment]
Yes, the depth: 'Error in UseMethod("depth")'

**Comment by nattycep** [comment]
I have this problem too: 
Error in UseMethod("depth") : 
  no applicable method for 'depth' applied to an object of class "NULL"
In addition: Warning messages:
1: In par(usr) : argument 1 does not name a graphical parameter
2: In par(usr) : argument 1 does not name a graphical parameter
3: In par(usr) : argument 1 does not name a graphical parameter

**Comment by mcaputo3** [comment]
So i get this error when i've run a bunch of mixing models and have lots of Quartz windows open. I think that happens to me if i have too many quartz windows with plots or if i need to re size a quartz window. But also could be something to do with memory and is often solved for me by putting: 
>options(expressions=500000)
 
I've read on some tidyverse github discussions about others having this issue especially with ggplots but the options above (close some quartz windows or use options(expressions=500000)) should work. Hope this helps!

**Comment by nattycep** [comment]
Thanks for the quick response.  Unfortunately, I'm still getting the error.  hmm...
