### ISSUE TITLE
Error in DISCR[, discr_sig_cols] * DISCR[, discr_sig_cols] 

### ISSUE THREAD

**Issue by MaxWijntje** [brianstock/MixSIAR#366]
Hi when i try to run my soil data I occur the following problem.
I already tried to put n on 1000 (proposed in other problem), but that didn't seem to fix it.
Does anyone know?

> library(MixSIAR)
# Create a sample source data matrix (replace this with your actual data)
> source_matrix <- matrix(c(
+   "Garden", -17.70, 0.01, 8.53, 0.3,1000,
+   "Grazing",-18.82, 0.01, 14.54, 0.3, 1000,
+   "Goat", -14.79, 0.01, 9.72, 0.3, 1000,
+   "Agri", -20.81, 0.01, 12.87, 0.3, 1000
+ ), ncol = 6, byrow = TRUE)

> colnames(source_matrix) <- c("source","Meand13C","SDd13C", "Meand15N","SDd15N","n")
 
> setwd("path")

> source_df <- as.data.frame(source_matrix)
 
> write.csv(source_df, "source.csv", row.names = FALSE)

# Create a sample mixture data matrix (replace this with your actual data)
> mix_matrix <- matrix(c(
+   1,"Pond",-22.24, 13.81, 1, "random_effect"
+ ), ncol = 6, byrow = TRUE)

> colnames(mix_matrix) <- c("sn", "source", "d13C", "d15N", "n", "FAC")

> setwd("path")

> mix_df <- as.data.frame(mix_matrix)

> write.csv(mix_df, "mix.csv", row.names = FALSE) 

# Create a sample discrimination data matrix (replace this with your actual data)
> discr_matrix <- matrix(c(
+   "Garden", 0, 0.001, 0, 0.001, 1000,
+   "Grazing", 0, 0.001, 0, 0.001, 1000,
+   "Goat", 0, 0.001, 0, 0.001, 1000,
+   "Agri", 0, 0.001, 0, 0.001, 1000), ncol = 6, byrow = TRUE)

> colnames(discr_matrix) <- c("source", "Meand13C","SDd13C", "Meand15N","SDd15N","n")

> setwd("path")

> discr_df <- as.data.frame(discr_matrix)
>  
> write.csv(discr_df, "discr.csv", row.names = TRUE)

# Load data
> mix <- load_mix_data(filename = "mix.csv", 
+                      iso_names = c("d13C", "d15N"),
+                      factors = "source",
+                      fac_random = FALSE,
+                      fac_nested = FALSE,
+                      cont_effects = NULL
+                      )
> source <- load_source_data(filename = "source.csv", 
+                            mix = mix, 
+                            conc_dep = FALSE, 
+                            data_type = "means",
+                            )
> discr <- load_discr_data(filename = "discr.csv", mix = mix)
Error in DISCR[, discr_sig_cols] * DISCR[, discr_sig_cols] : 
  non-numeric argument to binary operator

**Comment by MargotIvanova** [comment]
Hello, 

I am encountering the same issue when I try to load my discrimination data ; did you find what was the problem for you ? 
Thank you :)
