### ISSUE TITLE
Functions not found: Modifying MixSIAR plots

### ISSUE THREAD

**Issue by amroco** [brianstock/MixSIAR#367]
Hi there,

I am running MixSIAR 3.2.12 in R version 4.3.2.

I would like to access the posterior chains to modify plots sensu the vignette: https://brianstock.github.io/MixSIAR/articles/modify_output.html

When I run:
`ls("package: MixSIAR")`

I get the following functions listed as available:
```
 "calc_area"           "combine_sources"     "compare_models"      "load_discr_data"     "load_mix_data"       "load_source_data"    "output_JAGS"         "plot_continuous_var"
"plot_data"           "plot_data_one_iso"   "plot_data_two_iso"   "plot_intervals"      "plot_prior"          "run_model"           "summary_stat"        "write_JAGS_model"  
```

Note that the functions "output_diagnostics" and "output_stats" are not listed. I would like to use these functions as shown in the vingnette above, am I doing something incorrectly?

Thanks so much for any help.

Best,
A

**Comment by brianstock** [comment]
Did you install the latest version from GitHub? From the vignette:

Install MixSIAR from Github
The latest changes are not yet on CRAN. Install the GitHub version:
install.packages("devtools")
remotes::install_github("brianstock/MixSIAR", dependencies=T)

**Comment by amroco** [comment]
Hi when I reinstall from Github again I get the following message:

`remotes::install_github("brianstock/MixSIAR", dependencies=T)
Skipping install of 'MixSIAR' from a github remote, the SHA1 (037978f3) has not changed since last install.
  Use `force = TRUE` to force installation`

And I then ran:
`force = TRUE`

and the functions are back!

Thank you :)
