### ISSUE TITLE
plotting biplots of three tracers

### ISSUE THREAD

**Issue by zouzoukuzyk** [brianstock/MixSIAR#37]
Hi Brian, When using the mixsiar script with  a dataset that has 3 tracers, it produces a biplot of the first 2 tracers but not the third one.
Thanks!
Zou Zou

**Comment by brianstock** [comment]
Hi Zou Zou,

Strange... I'm running a dataset with 8 tracers now and it produces all {8 choose 2} = 28 biplots like it should.  Perhaps it's a graphics window issue with your setup?

-Brian
