### ISSUE TITLE
issue in opening MixSIAR GUI

### ISSUE THREAD

**Issue by arnab-pal** [brianstock/MixSIAR#371]
I am currently trying to use the MixSIAR package in R for the isotope mixing model. I have installed the MixSIAR package in the R (version: 4.3.3). But while trying to open the GUI it is giving a response as: "Error in mixsiar_gui() : could not find function "mixsiar_gui"". Please help so that I can use the GUI of the package for the analysis. I have followed MixSIAR GUI User Manual v3.1 for reference.

**Comment by leahbecu** [comment]
I think the GUI has been removed. You can still run the model, you just have to adjust the script yourself to your purposes.

Leah
