### ISSUE TITLE
model that combines a fixed and random effect doesnt load mixture data

### ISSUE THREAD

**Issue by BriceSemmens** [brianstock/MixSIAR#38]
the may be due to the fact that MixSIAR only accepts numerical fixed effects names (1....4).

**Comment by JasonMHill** [comment]
That doesn't appear to be correct. Just tested it out by changing my fixed factor levels to alpha, bravo, charlie, and the model runs just fine and correctly labels output. I don't think MixSIAR currently supports mixed effects models. The examples in the User Manual (v. 1.0) exclusively use random effects or continuous effects, and I don't see any cautionary notes about naming fixed effects in the manual. There are no mixed effects examples either.

**Comment by brianstock** [comment]
I've fixed the cases with 2 fixed effects and 1 FE + 1 RE.  In the manual update, I don't have an example with mixed effects, but you can easily see that it works now by changing  `fac_random` in the Wolves Example at line 51 (`load_mix_data`).

Original model (Region and Pack both random effects):
```
fac_random=c(TRUE,TRUE)
```
Mixed effect model (Region = fixed effect, Pack = random effect):
```
fac_random=c(FALSE,TRUE)
```

**Comment by JasonMHill** [comment]
Awesome, thank you Brian for maintaining this great package.
Jason
