### ISSUE TITLE
Distance dependence tracer values of sources

### ISSUE THREAD

**Issue by mason-linscott** [brianstock/MixSIAR#381]
Hi MixSIAR team,

Is there a way to incorporate variation in sources that is a function of site attribute (i.e. site distance from a source where the source's tracer values change as function of distance)? The particular use case I am considering is how sea spray and distance from the ocean may alter meteoric 13C values (or water vapor) at a given site which can shift shell 13C values of land snails. 

I considered just running each site individually with different source values for each site but that seems cumbersome.

Thank you for your time and I wish you all the best,
Mason

**Comment by brianstock** [comment]
You can include a categorical/group variable on the sources in mixsiar, see
the Deer example.

For anything more complicated you'll need to code your own model. For
inspiration, see the neat extension of the Geese dataset in the Parnell et
al. 2013 environmetrics paper.

**Comment by mason-linscott** [comment]
Thank you for your recommendations! I will let you know if I need any other help.
