### ISSUE TITLE
Results from MixSiar working examples do not match

### ISSUE THREAD

**Issue by marioliveira** [brianstock/MixSIAR#39]
Hi,

    I installed the MixSiar in my computer a week ago and started to practice the working examples. The model runs, everything is fine, however the results I´ve got from it were slightly different compared to those shown in the manual (wolves example, zooplankton example...)...I reinstalled all of it again, double checked the inputs data and variables but it still gives results a little bit different from what it´s expected. Not feeling confortable to run my own data under this situation. Did anyone had similar problems and could help me, please?

**Comment by brianstock** [comment]
Hello!  Let's look at the Wolves example first:

1) How different are your results from what the manual has?
2) Has the model converged?  Can you print the 10 worst variables by Gelman diagnostic here?  What MCMC parameters are you using (manual uses chain length of 50,000 = "short")?
3) Double-check that all of the GUI options match those of the Wolves ex.

The MCMC chain length I used for the Wolves example ("Short" = 50,000) is shorter than I would use for a final analysis, in the interest of a new user not having to wait too long for results.  Try increasing the chain length until the model is fully converged, then the results should not be different if you run the same model a second time.  See https://github.com/brianstock/MixSIAR/issues/33.

-Brian

**Comment by marioliveira** [comment]
Hi,

      So, some examples of how my results were different from those in the example. By factor: 

- Region: 1.33 (example), 1.41 (my results);
- Pack: 0.53(example), 0.51 (my results);
- Ind.: 0.30 (ex.), 0.36 (my results).

Gelman diagnostics:

Out of 238 variables: 91 > 1.01
                      7 > 1.05
                      3 > 1.1

The worst variables are:
            Point est.
p.global[1]   2.123732
p.global[3]   1.338716
p.global[2]   1.314160
p.fac1[2,2]   1.073390
p.fac1[3,1]   1.066908
p.fac1[3,3]   1.063149
fac1.sig      1.061115
p.ind[64,1]   1.049090
p.fac2[8,1]   1.048518
p.fac1[2,1]   1.047798
            Upper C.I.
p.global[1]   3.648870
p.global[3]   2.029295
p.global[2]   1.891905
p.fac1[2,2]   1.204968
p.fac1[3,1]   1.216530
p.fac1[3,3]   1.189275
fac1.sig      1.179263
p.ind[64,1]   1.156644
p.fac2[8,1]   1.154731
p.fac1[2,1]   1.125848


     Actually, they were all slight differences, the results overall pattern was maintained. In fact, the model didn´t converged with the short chain lenght used in the manual. I had assumed that in the Wolves example it had converged,  my mistake. However, I ran the model again twice, using the "long" chain option. According to the Gelman diagnostics, both converged, although it was not very supported by the other diagnostics methods. See below. 

Test 1 (long chain)

Out of 238 variables: 20 > 1.01
                      1 > 1.05
                      0 > 1.1

The worst variables are:
            Point est.
p.global[1]   1.055758
p.global[2]   1.030397
p.fac1[3,1]   1.027153
p.global[3]   1.022650
fac1.sig      1.020352
p.fac1[3,3]   1.013907
p.ind[66,3]   1.013826
p.ind[66,2]   1.013273
p.fac2[8,3]   1.012387
p.ind[65,2]   1.011971
            Upper C.I.
p.global[1]   1.184076
p.global[2]   1.076592
p.fac1[3,1]   1.090770
p.global[3]   1.069715
fac1.sig      1.044448
p.fac1[3,3]   1.043759
p.ind[66,3]   1.042360
p.ind[66,2]   1.040230
p.fac2[8,3]   1.039276
p.ind[65,2]   1.035092

################################################################################
# Geweke Diagnostic
################################################################################

The Geweke diagnostic is a standard z-score, so we'd expect 5% to be outside +/-1.96
Number of variables outside +/-1.96 in each chain (out of 238):

       Chain 1   10    Chain 2   31    Chain 3   10

Test 2 (long chain)

Out of 238 variables: 30 > 1.01
                      2 > 1.05
                      0 > 1.1

The worst variables are:
            Point est. Upper C.I.
fac1.sig      1.072652   1.160618
p.global[1]   1.060865   1.178945
p.global[3]   1.046761   1.141952
p.fac1[3,3]   1.029722   1.085044
p.ind[64,3]   1.022896   1.062299
p.fac2[8,3]   1.021245   1.057304
p.ind[62,3]   1.020457   1.054601
p.ind[66,3]   1.020227   1.054262
p.ind[63,3]   1.020075   1.056019
p.ind[64,2]   1.019772   1.051141

################################################################################
# Heidelberger and Welch Diagnostic
################################################################################

A few failures is normal and acceptable...
Number of failures in each chain (out of 238 variables):

             Chain 1 Chain 2 Chain 3
Stationarity       2       4       1
Half-width        22      93      13

################################################################################
# Geweke Diagnostic
################################################################################

The Geweke diagnostic is a standard z-score, so we'd expect 5% to be outside +/-1.96
Number of variables outside +/-1.96 in each chain (out of 238):

              Chain 1 Chain 2 Chain 3
Geweke      37      65      15

       Interestingly,  results were slightly different the second time I ran it. For instance, results by factor:

- Region: 1.27 (first attempt using long chain), 1.42 (second one);
- Pack: 0.51 (first attempt), 0.51(second one);
- Ind: 0.36 (firts one), 0.36 (second one).

   All data were double-checked before I ran the models. As I mentioned, the results overall patterns doesn´t change at all. Are these small differences in the results acceptable??

**Comment by marioliveira** [comment]
Hi,

      So, some examples of how my results were different from those in the example. By factor: 

- Region: 1.33 (example), 1.41 (my results);
- Pack: 0.53(example), 0.51 (my results);
- Ind.: 0.30 (ex.), 0.36 (my results).

Gelman diagnostics:

Out of 238 variables: 91 > 1.01
                      7 > 1.05
                      3 > 1.1

The worst variables are:
            Point est.
p.global[1]   2.123732
p.global[3]   1.338716
p.global[2]   1.314160
p.fac1[2,2]   1.073390
p.fac1[3,1]   1.066908
p.fac1[3,3]   1.063149
fac1.sig      1.061115
p.ind[64,1]   1.049090
p.fac2[8,1]   1.048518
p.fac1[2,1]   1.047798
            Upper C.I.
p.global[1]   3.648870
p.global[3]   2.029295
p.global[2]   1.891905
p.fac1[2,2]   1.204968
p.fac1[3,1]   1.216530
p.fac1[3,3]   1.189275
fac1.sig      1.179263
p.ind[64,1]   1.156644
p.fac2[8,1]   1.154731
p.fac1[2,1]   1.125848


     Actually, they were all slight differences, the results overall pattern was maintained. In fact, the model didn´t converged with the short chain lenght used in the manual. I had assumed that in the Wolves example it had converged,  my mistake. However, I ran the model again twice, using the "long" chain option. According to the Gelman diagnostics, both converged, although it was not very supported by the other diagnostics methods. See below. 

Test 1 (long chain)

Out of 238 variables: 20 > 1.01
                      1 > 1.05
                      0 > 1.1

The worst variables are:
            Point est.
p.global[1]   1.055758
p.global[2]   1.030397
p.fac1[3,1]   1.027153
p.global[3]   1.022650
fac1.sig      1.020352
p.fac1[3,3]   1.013907
p.ind[66,3]   1.013826
p.ind[66,2]   1.013273
p.fac2[8,3]   1.012387
p.ind[65,2]   1.011971
            Upper C.I.
p.global[1]   1.184076
p.global[2]   1.076592
p.fac1[3,1]   1.090770
p.global[3]   1.069715
fac1.sig      1.044448
p.fac1[3,3]   1.043759
p.ind[66,3]   1.042360
p.ind[66,2]   1.040230
p.fac2[8,3]   1.039276
p.ind[65,2]   1.035092

################################################################################
# Geweke Diagnostic
################################################################################

The Geweke diagnostic is a standard z-score, so we'd expect 5% to be outside +/-1.96
Number of variables outside +/-1.96 in each chain (out of 238):

       Chain 1   10    Chain 2   31    Chain 3   10

Test 2 (long chain)

Out of 238 variables: 30 > 1.01
                      2 > 1.05
                      0 > 1.1

The worst variables are:
            Point est. Upper C.I.
fac1.sig      1.072652   1.160618
p.global[1]   1.060865   1.178945
p.global[3]   1.046761   1.141952
p.fac1[3,3]   1.029722   1.085044
p.ind[64,3]   1.022896   1.062299
p.fac2[8,3]   1.021245   1.057304
p.ind[62,3]   1.020457   1.054601
p.ind[66,3]   1.020227   1.054262
p.ind[63,3]   1.020075   1.056019
p.ind[64,2]   1.019772   1.051141

################################################################################
# Heidelberger and Welch Diagnostic
################################################################################

A few failures is normal and acceptable...
Number of failures in each chain (out of 238 variables):

             Chain 1 Chain 2 Chain 3
Stationarity       2       4       1
Half-width        22      93      13

################################################################################
# Geweke Diagnostic
################################################################################

The Geweke diagnostic is a standard z-score, so we'd expect 5% to be outside +/-1.96
Number of variables outside +/-1.96 in each chain (out of 238):

              Chain 1 Chain 2 Chain 3
Geweke      37      65      15

       Interestingly,  results were slightly different the second time I ran it. For instance, results by factor:

- Region: 1.27 (first attempt using long chain), 1.42 (second one);
- Pack: 0.51 (first attempt), 0.51(second one);
- Ind: 0.36 (firts one), 0.36 (second one).

   All data were double-checked before I ran the models. As I mentioned, the results overall patterns doesn´t change at all. Are these small differences in the results acceptable??

**Comment by brianstock** [comment]
I expect those slight differences will go away as the model converges further, i.e. if you run the "very long" setting and see all Gelman diagnostics < 1.01.  The "long" chains still had a couple >1.05.  You should find that the model with Region, Pack and Individual takes longer to converge than the model with only Region and Pack.

Like you say, the overall patterns don't change, but if you're doing a final analysis for publication, you don't want the results to change at all.

**Comment by marioliveira** [comment]
Yes, sure. I am gonna keep trying. Just a last question: is it possible that these differences are resulting from some problem during the MixSiar installation? Initially I had some problems to install the MixSiar in my computer. I think it is unlikely once the software is working well but just to be sure. Thank you!

**Comment by brianstock** [comment]
No, I don't think that's possible. Once MixSIAR and all the dependent R
packages are installed and loading correctly, you should be good.

**Comment by marioliveira** [comment]
Great! Thanks a lot for your help!
