### ISSUE TITLE
Error message in load source data

### ISSUE THREAD

**Issue by FanLanFeng** [brianstock/MixSIAR#40]
I am having difficulty running models with mixed effects for “Lake” and “Palmyra” examples.
When I try to load “source data”, it always shows an error message as “Error in colVars(x, ...) : Argument 'x' must be a matrix or a vector.”
Can you tell me how to solve this problem.

LanFeng

**Comment by brianstock** [comment]
Hi LanFeng,

I'm assuming there is a mismatch between the options you've selected in the GUI and the data you're inputting.  Double check that you're clicking the options listed in the manual... are you clicking "Load raw source data" or "Load source means and SDs"?
