### ISSUE TITLE
Working with single data

### ISSUE THREAD

**Issue by Pactzar** [brianstock/MixSIAR#42]
Hi! I wanted to know if is it possible to work with single data in the MixSIAR_script with priors (preferably) or in MIxSIAR. 
SIAR has a special command named siarsolomcmcv4 for this purpose. Is it the same in this case when we run the model?

**Comment by eric-ward** [comment]
You can't estimate residual error with a single data point, but MixSIAR should work if you turn any residual or hierarchical errors off.

**Comment by brianstock** [comment]
Yes, it is the same. MixSIAR (without residual error) and SIAR (siarsolomcmcv4) are both using the original MixSIR model error structure.
