### ISSUE TITLE
Running MixSIAR with >2 tracers

### ISSUE THREAD

**Issue by Cynoscion** [brianstock/MixSIAR#54]
I am trying to run the MixSIAR on CSIA of amino acid data. This means that I have 5 tracers (amino acids) to put into the model and all the TEF is set to zero, as there is no trophic fractionation with CSIA of essential amino acids.
However, when I run 2 tracers the model works. However, increasing it to 3 tracers it gives the following error:
Error: RUNTIME ERROR:
Cannot invert matrix: not positive definite 

I have tried several combinations of 2 amino acids and the model runs. Therefore, it could not be the data of individual tracers itself. However, adding a 3rd tracer will result in the above error message.
Any ideas of why this is happening? Is this model built for only 2 tracers (normally C and N)?

**Comment by brianstock** [comment]
Hmm, are your source variances also zero?  Since the TEF and source variances are added together, one of them can be zero but not both (see Fig 2 legend on page 12 in manual, or footnote #5 on page 13).

MixSIAR is not limited by the number of tracers - see the Isopod and Cladocera examples with 8 and 22 tracers (fatty acid profile data), respectively.

**Comment by Cynoscion** [comment]
At this point of my data collection all source data have at least 3 data points for each tracer. They are put in the model as 'raw data'. However, all my data, including source and consumer data, are negative values (in contrast to the Isopod and Cladocera example).

**Comment by brianstock** [comment]
Negative tracer values shouldn't matter - most d13C stable isotope values are negative.

MixSIAR fits different models depending on the type of data you have, and relies on the user to correctly match the options in the GUI/script with their data. There are two cases where matrix inversion happens (searching for "inverse" in "write_JAGS_model.r"): 1) fitting raw source data, and 2) the "resid*process" error term.  I would try manually calculating each source mean + SD and inputting the source data as "means + SD", as well as selecting the "Resid only" error option.  Then no matrices will be inverted and we can see if that is the problem.

Are your source data "by factor" or not?

**Comment by Cynoscion** [comment]
As I have briefly discussed this problem with A. Parnell and A. Jackson during one of their courses, I ended up using the MixSIAR script next to the GUI interface. They could not find the problem at that time.
I have added the script so you can see the input. 
To answer your question, source data are not 'by factor'

Here is the script when I input 3 tracers with raw data.
mix <- load_mix_data_script(filename="CSIA_consumer.csv", 
                            iso_names=c("Val", "Ile", "Thr"), 
                            factors=c("X"), 
                            fac_random=c(TRUE), 
                            fac_nested=c(FALSE), 
source <- load_source_data(filename="CSIA_source.csv", 
                           source_factors=NULL, 
                           conc_dep=FALSE, 
                           data_type="raw", mix)    
discr <- load_discr_data(filename="CSIA_TEF.csv", mix)
                            cont_effects=NULL)

When I use mean+SD source data (with the file setup as given in the Isopod example) and 'Resid only' selected in the GUI interface, I get another error message:
Error in jags.model(model.file, data = data, inits = init.values, n.chains = n.chains,  : 
  RUNTIME ERROR:
Non-conforming parameters in function inprod

Even with two tracers it will give this error message.

**Comment by brianstock** [comment]
My guess is that there's a mismatch between the data structure in the files and the selected model options.  Hard to tell without seeing the .csv files.  If you send them via email I can take a look: b1stock@ucsd.edu

**Comment by rjbest** [comment]
Hi Brian - I'm having the same issue (Error: RUNTIME ERROR:Cannot invert matrix: not positive definite) when using more than 2 tracers, raw source data, and values of 0 for the discrimination means and SDs. When I calculate the source means and SDs and use that instead, it works fine. The issues are the same with the GUI or script methods. Did you uncover any obvious mistakes in this past example? I'm not sure if it's my data formatting or something structural about covariance among tracers...Thanks very much for any insight and all your work on this package...
