### ISSUE TITLE
MixSIAR density plots

### ISSUE THREAD

**Issue by BrianHayden** [brianstock/MixSIAR#55]
Hi Brian, 

Is it possible to generate density box plots, such as the 50-75-95% CI plots as per SIAR, with MIxSIAR. Although not as informative as the current MixSIAR density plots, they are easier to manipulate and present in papers etc. Also, is it possible to test for differences in resource use between groups, other than a comparison of 95% CIs.

Top work, thanks

B

**Comment by brianstock** [comment]
Yes, you can access the MCMC chains for aggregating a posteriori (https://github.com/brianstock/MixSIAR/issues/53) and/or plotting (https://github.com/brianstock/MixSIAR/issues/30).  Unfortunately I haven't written functions to do these common tasks, so you'll have to do it on your own.  Hopefully you can adapt some code I shared from another analysis on mantis shrimp: https://github.com/brianstock/mantis_shrimp_diet/blob/master/Fig3_diet_boxplot_uninf.r).

**Comment by BrianHayden** [comment]
Perfect, I'll get stuck in.

B
