### ISSUE TITLE
Isospace issue and Error message confusion

### ISSUE THREAD

**Issue by zariatorres** [brianstock/MixSIAR#56]
I am new to mixSIAR, and I did follow the Manual provided and did the Wolves and Geese examples.  I felt confident enough to try mixSIAR with my own data, but now I am running into a two issues.  

1) When I select, "Make isospace plot", the plot only shows me my Mixture data (see below), and no Source data.
![image](https://cloud.githubusercontent.com/assets/17519492/13375592/70b33c08-dd69-11e5-96ef-1ea69aeea94e.png)

I also tried loading my Source by means and SDs, but got the same result.  I don't feel comfortable with using my means and SDs for Source values since the isospace geometry (graphed it separately using excel) will not make sense.

2)Below is the error message I am getting after I load my Mixture, Source (raw data values, with n), and Discrimination data. 
 
**Error in jags.model(model.file, data = data, inits = init.values, n.chains = n.chains,  : 
  RUNTIME ERROR:
Unable to resolve the following parameters:
frac_mu[1:9,1] (line 117)
frac_mu[1:9,2] (line 117)
frac_sig2[1:9,1] (line 139)
frac_sig2[1:9,2] (line 139)
mix.cov[1,1:2,1:2] (line 142)
mix.cov[2,1:2,1:2] (line 142)
mix.cov[3,1:2,1:2] (line 142)
mix.cov[4,1:2,1:2] (line 142)
mix.cov[5,1:2,1:2] (line 142)
mix.cov[6,1:2,1:2] (line 142)
mix.cov[7,1:2,1:2] (line 142)
mix.cov[8,1:2,1:2] (line 142)
mix.mu[1:2,1] (line 148)
mix.mu[1:2,2] (line 148)
mix.mu[1:2,3] (line 148)
mix.mu[1:2,4] (line 148)
mix.mu[1:2,5] (line 148)
mix.mu[1:2,6] (line 148)
mix.mu[1:2,7] (line 148)
mix.mu[1:2,8] (line 148)
Either supply values for these nodes with the data
or define them on the left hand side of a relation.**

Since this is through jags, I don't know how I would properly "supply values to these nodes".

I am doing my best to learn the different types of mixing models to run my data with, but I fear that I am one of the scientists that you all warn, "researchers with a large number of potential sources should carefully consider whether it is appropriate to use mixing models to assessing the relative diet proportions of such a generalist".

**Comment by zariatorres** [comment]
I think I figured out where I went wrong and got everything working smoothly.

**Comment by ChrisHarrod** [comment]
e
CDD., H FJT
