### ISSUE TITLE
Bug? 

### ISSUE THREAD

**Issue by SharonEv** [brianstock/MixSIAR#57]
Hi,

 I put aside my mixing modelling work for 2 months and now I can't seem to get things working again. I am using OSX version 10.11.3 (15D21). First I used the interface and I could get the wolf example to work but not my own. I kept getting an error about the source factors not matching but I had run this data 2 months ago without the problem. So I updated everything (R etc...). But the problem still remained. I then thought to enter the code directly without the interface and I got a similar error code (with your geese example). It then came up with the following bug report: 

 Error in if (source$by_factor) { : missing value where TRUE/FALSE needed
function (isotopes, mix, source, discr, filename, plot_save_pdf, 
    plot_save_png) 
{
    df <- data.frame(x = mix$data_iso[, isotopes[1]], y = mix$data_iso[, 
        isotopes[2]])
    if (length(grep("C", mix$iso_names[isotopes[1]])) == 1) 
        x_label <- expression(paste(delta^13, "C (‰)", sep = ""))
    if (length(grep("N", mix$iso_names[isotopes[1]])) == 1) 
        x_label <- expression(paste(delta^15, "N (‰)", sep = ""))
    if (length(grep("S", mix$iso_names[isotopes[1]])) == 1) 
        x_label <- expression(paste(delta^34, "S (‰)", sep = ""))
    if (length(grep("O", mix$iso_names[isotopes[1]])) == 1) 
        x_label <- expression(paste(delta^18, "O (‰)", sep = ""))
    if (length(grep("SP", mix$iso_names[isotopes[1]])) == 1) 
        y_label <- expression(paste(delta^15, "N-SP (‰)", sep = ""))
    if (length(grep("C", mix$iso_names[isotopes[2]])) == 1) 
        y_label <- expression(paste(delta^13, "C (‰)", sep = ""))
    if (length(grep("N", mix$iso_names[isotopes[2]])) == 1) 
        y_label <- expression(paste(delta^15, "N (‰)", sep = ""))
    if (length(grep("S", mix$iso_names[isotopes[2]])) == 1) 
        y_label <- expression(paste(delta^34, "S (‰)", sep = ""))
    if (length(grep("O", mix$iso_names[isotopes[2]])) == 1) 
        y_label <- expression(paste(delta^18, "O (‰)", sep = ""))
    if (length(grep("SP", mix$iso_names[isotopes[2]])) == 1) 
        y_label <- expression(paste(delta^15, "N-SP (‰)", sep = ""))
    if (!exists("x_label")) 
        x_label <- mix$iso_names[isotopes[1]]
    if (!exists("y_label")) 
        y_label <- mix$iso_names[isotopes[2]]
    if (!is.na(source$by_factor)) {
        source_linetype <- sort(rep(1:source$n.sources, source$S_factor_levels))
        source_color <- factor(as.numeric(source$S_factor1))
        index <- seq(from = 1, to = 1 + (source$n.sources - 1) * 
            source$S_factor_levels, by = source$S_factor_levels)
        discr_mu_plot <- array(NA, dim = c(length(source$S_MU[, 
            1]), mix$n.iso))
        discr_sig2_plot <- array(NA, dim = c(length(source$S_MU[, 
            1]), mix$n.iso))
        for (i in 1:source$n.sources) {
            discr_mu_plot[index[i]:(index[i] + source$S_factor_levels - 
                1), ] <- matrix(rep(discr$mu[i, ], source$S_factor_levels), 
                nrow = source$S_factor_levels, ncol = mix$n.iso, 
                byrow = T)
            discr_sig2_plot[index[i]:(index[i] + source$S_factor_levels - 
                1), ] <- matrix(rep(discr$sig2[i, ], source$S_factor_levels), 
                nrow = source$S_factor_levels, ncol = mix$n.iso, 
                byrow = T)
        }
    }
    else {
        source_linetype <- 1:source$n.sources
        source_color <- factor(rep("black", source$n.sources))
        index <- 1:source$n.sources
        discr_mu_plot <- discr$mu
        discr_sig2_plot <- discr$sig2
    }
    MU_plot <- array(NA, dim = c(length(source$S_MU[, 1]), 2))
    SIG_plot <- array(NA, dim = c(length(source$S_SIG[, 1]), 
        2))
    for (iso in 1:2) {
        MU_plot[, iso] <- source$S_MU[, isotopes[iso]] + discr_mu_plot[, 
            isotopes[iso]]
        SIG_plot[, iso] <- sqrt(source$S_SIG[, isotopes[iso]]^2 + 
            discr_sig2_plot[, isotopes[iso]])
    }
    df_sources <- data.frame(x = MU_plot[, 1], y = MU_plot[, 
        2], ymin = MU_plot[, 2] - SIG_plot[, 2], ymax = MU_plot[, 
        2] + SIG_plot[, 2], xmin = MU_plot[, 1] - SIG_plot[, 
        1], xmax = MU_plot[, 1] + SIG_plot[, 1], linetype = source_linetype, 
        scolour = source_color)
    source.labels <- data.frame(x = MU_plot[index, 1] - rep(1, 
        source$n.sources), y = MU_plot[index, 2] + rep(0.75, 
        source$n.sources), label = source$source_names)
    .e <- environment()
    dev.new()
    if (mix$n.effects == 2) {
        shapes <- c(16, 17, 15, 3, 7, 8, 1, 6, 35, 36, 37, 4, 
            18, 14, 11, 9, 13)
        shapes <- shapes[1:mix$FAC[[2]]$levels]
        if (source$by_factor) {
            g <- ggplot2::ggplot(data = df, ggplot2::aes(x = x, 
                y = y), environment = .e) + ggplot2::geom_point(ggplot2::aes(colour = factor(mix$FAC[[1]]$values), 
                shape = factor(mix$FAC[[2]]$values)), size = 2.5, 
                show_guide = T) + ggplot2::scale_colour_discrete(breaks = levels(factor(mix$FAC[[1]]$values)), 
                labels = mix$FAC[[1]]$labels) + ggplot2::scale_shape_manual(values = shapes, 
                labels = mix$FAC[[2]]$labels) + ggplot2::geom_pointrange(data = df_sources, 
                ggplot2::aes(ymin = ymin, ymax = ymax, colour = scolour), 
                size = 1, linetype = source_linetype, show_guide = F) + 
                ggplot2::geom_errorbarh(data = df_sources, ggplot2::aes(xmin = xmin, 
                  xmax = xmax, colour = scolour), size = 1, height = 0, 
                  linetype = source_linetype, show_guide = F) + 
                ggplot2::geom_text(data = source.labels, ggplot2::aes(x = x, 
                  y = y, label = label), show_guide = F) + ggplot2::ylab(y_label) + 
                ggplot2::xlab(x_label) + ggplot2::theme_bw() + 
                ggplot2::theme(legend.position = c(0, 1), legend.justification = c(0, 
                  1), legend.title = ggplot2::element_blank())
            print(g)
        }
        else {
            g <- ggplot2::ggplot(data = df, ggplot2::aes(x = x, 
                y = y), environment = .e) + ggplot2::geom_point(ggplot2::aes(colour = factor(mix$FAC[[1]]$values), 
                shape = factor(mix$FAC[[2]]$values)), size = 2.5, 
                show_guide = T) + ggplot2::scale_colour_discrete(breaks = levels(factor(mix$FAC[[1]]$values)), 
                labels = mix$FAC[[1]]$labels) + ggplot2::scale_shape_manual(values = shapes, 
                labels = mix$FAC[[2]]$labels) + ggplot2::geom_pointrange(data = df_sources, 
                ggplot2::aes(ymin = ymin, ymax = ymax), size = 1, 
                linetype = source_linetype, show_guide = F) + 
                ggplot2::geom_errorbarh(data = df_sources, ggplot2::aes(xmin = xmin, 
                  xmax = xmax), size = 1, height = 0, linetype = source_linetype, 
                  show_guide = F) + ggplot2::geom_text(data = source.labels, 
                ggplot2::aes(x = x, y = y, label = label), show_guide = F) + 
                ggplot2::ylab(y_label) + ggplot2::xlab(x_label) + 
                ggplot2::theme_bw() + ggplot2::theme(legend.position = c(0, 
                1), legend.justification = c(0, 1), legend.title = ggplot2::element_blank())
            print(g)
        }
    }
    if (mix$n.effects == 1) {
        if (source$by_factor) {
            g <- ggplot2::ggplot(data = df, ggplot2::aes(x = x, 
                y = y), environment = .e) + ggplot2::geom_point(ggplot2::aes(colour = factor(mix$FAC[[1]]$values)), 
                show_guide = T) + ggplot2::scale_colour_discrete(breaks = levels(factor(mix$FAC[[1]]$values)), 
                labels = mix$FAC[[1]]$labels) + ggplot2::geom_pointrange(data = df_sources, 
                ggplot2::aes(ymin = ymin, ymax = ymax, colour = scolour), 
                size = 1, linetype = source_linetype, show_guide = F) + 
                ggplot2::geom_errorbarh(data = df_sources, ggplot2::aes(xmin = xmin, 
                  xmax = xmax, colour = scolour), size = 1, height = 0, 
                  linetype = source_linetype, show_guide = F) + 
                ggplot2::geom_text(data = source.labels, ggplot2::aes(x = x, 
                  y = y, label = label), show_guide = F) + ggplot2::ylab(y_label) + 
                ggplot2::xlab(x_label) + ggplot2::theme_bw() + 
                ggplot2::theme(legend.position = c(0, 1), legend.justification = c(0, 
                  1), legend.title = ggplot2::element_blank())
            print(g)
        }
        else {
            g <- ggplot2::ggplot(data = df, ggplot2::aes(x = x, 
                y = y), environment = .e) + ggplot2::geom_point(ggplot2::aes(colour = factor(mix$FAC[[1]]$values)), 
                show_guide = T) + ggplot2::scale_colour_discrete(breaks = levels(factor(mix$FAC[[1]]$values)), 
                labels = mix$FAC[[1]]$labels) + ggplot2::geom_pointrange(data = df_sources, 
                ggplot2::aes(ymin = ymin, ymax = ymax), size = 1, 
                linetype = source_linetype, show_guide = F) + 
                ggplot2::geom_errorbarh(data = df_sources, ggplot2::aes(xmin = xmin, 
                  xmax = xmax), size = 1, height = 0, linetype = source_linetype, 
                  show_guide = F) + ggplot2::geom_text(data = source.labels, 
                ggplot2::aes(x = x, y = y, label = label), show_guide = F) + 
                ggplot2::ylab(y_label) + ggplot2::xlab(x_label) + 
                ggplot2::theme_bw() + ggplot2::theme(legend.position = c(0, 
                1), legend.justification = c(0, 1), legend.title = ggplot2::element_blank())
            print(g)
        }
    }
    if (mix$n.effects == 0) {
        g <- ggplot2::ggplot(data = df, ggplot2::aes(x = x, y = y)) + 
            ggplot2::geom_point() + ggplot2::geom_pointrange(data = df_sources, 
            ggplot2::aes(ymin = ymin, ymax = ymax), size = 1, 
            linetype = source_linetype, show_guide = F) + ggplot2::geom_errorbarh(data = df_sources, 
            ggplot2::aes(xmin = xmin, xmax = xmax), size = 1, 
            height = 0, linetype = source_linetype, show_guide = F) + 
            ggplot2::geom_text(data = source.labels, ggplot2::aes(x = x, 
                y = y, label = label), show_guide = F) + ggplot2::ylab(y_label) + 
            ggplot2::xlab(x_label) + ggplot2::theme_bw()
        print(g)
    }
    if (plot_save_pdf == TRUE) {
        mypath <- file.path(paste(getwd(), "/", filename, "_", 
            isotopes[1], "_", isotopes[2], ".pdf", sep = ""))
        cairo_pdf(filename = mypath, width = 7, height = 7)
        print(g)
        dev.off()
    }
    if (plot_save_png == TRUE) {
        mypath <- file.path(paste(getwd(), "/", filename, "_", 
            isotopes[1], "_", isotopes[2], ".png", sep = ""))
        png(filename = mypath)
        print(g)
        dev.off()
    }

Hope you can work it out! 

Thanks 
Sharon

**Comment by brianstock** [comment]
Hi Sharon,

Thanks for the bug report, it was a small mistake and should be fixed now.  Try:

```
library(MixSIAR)
mixsiar.dir <- find.package("MixSIAR")
source(paste0(mixsiar.dir,"/example_scripts/mixsiar_script_geese.R"))
```

**Comment by SharonEv** [comment]
Thanks Brain, 

That gave me this: 
Error in source(paste0(mixsiar.dir, "/example_scripts/mixsiar_script_geese.R")) : 
  /Library/Frameworks/R.framework/Versions/3.2/Resources/library/MixSIAR/example_scripts/mixsiar_script_geese.R:53:38: unexpected ','
52: #jags.1 <- run_model(run="short", mix, source, discr, model_filename,
53:                         alpha.prior=1,
                                         ^

So I tried my own data and that loaded correctly but can you explain why I keep getting this error- it happened on the interface and now when I entered the code: 

Error in if (source$by_factor) { : missing value where TRUE/FALSE needed

Hope you don't mind but I'll send you files to see if you can see error.

**Comment by brianstock** [comment]
Sharon,

I fixed both of those errors today: the first was in "mixsiar_script_geese.R", and the second in the "plot_data" function.  Try installing the current version of MixSIAR and run the Geese Ex script again:

```
library(devtools)
devtools::install_github("brianstock/MixSIAR",
                         dependencies = TRUE, 
                         build_vignettes = TRUE) # FALSE if no pandoc
library(MixSIAR)
mixsiar.dir <- find.package("MixSIAR")
source(paste0(mixsiar.dir,"/example_scripts/mixsiar_script_geese.R"))
```

**Comment by SharonEv** [comment]
Brian you are a legend its fixed!

**Comment by brianstock** [comment]
Awesome, glad it works... and sorry about breaking your code!
