### ISSUE TITLE
pandoc and pandoc-citeproc

### ISSUE THREAD

**Issue by jjvenky** [brianstock/MixSIAR#58]
In Linux (Ubuntu 15.10), both pandoc and pandoc-citeproc must be installed in order for the vignettes to build properly.

Without pandoc-citeproc, this error is thrown:

* creating vignettes ... ERROR
Warning in engine$weave(file, quiet = quiet, encoding = enc) :
  Pandoc (>= 1.12.3) and/or pandoc-citeproc is not available. Please install both.

So the instructions should be more like:

devtools::install_github("brianstock/MixSIAR",
                         dependencies = TRUE, 
                         build_vignettes = TRUE) # FALSE if no pandoc and pandoc-citeproc

**Comment by brianstock** [comment]
Thanks Jason, hope the README is clearer now!
