### ISSUE TITLE
How to run MixSIAR GUI in R(Windows)?

### ISSUE THREAD

**Issue by liangxuehong** [brianstock/MixSIAR#60]
I do not know any about MixSIAR. And I want to analysis of  stable isotopes by MixSIAR.
     Could you please tell me the steps about the question.
     Thanks a lot !

**Comment by brianstock** [comment]
Please see the README, visible on the main page by scrolling down: https://github.com/brianstock/MixSIAR.

**Comment by liangxuehong** [comment]
Hi Brian Stock , thank you!

**Comment by liangxuehong** [comment]
I  follow the steps ,but i can't run mixsiar GUI.
The MixSIAR GUI dose not appear .
1. Download and install/update R. You can check which version of R (and any packages) you are running using the commandsessionInfo(). If you have an older version of R installed, the easiest thing to do is use the installr package. 
2. Download and install JAGS. 
3. (Optional) If you want to build the vignettes, install pandoc or RStudio.
4. Open R (or R Studio). 
5. Install GTK+ dependent packages.
install.packages(c("gWidgets", "RGtk2", "gWidgetsRGtk2", "devtools"))
6. LoadRGtk2. You will be prompted to install GTK+. **Follow the automatic prompts and do not interrupt the GTK+ installation!**:
library(RGtk2)
7. Restart R.
 8. Install MixSIAR package:
library(devtools) devtools::install_github("brianstock/MixSIAR@*release", # gets latest release dependencies = TRUE, build_vignettes = TRUE) # FALSE if no pandoc/R Studio
8. Load MixSIAR and run GUI:
library(MixSIAR) 
mixsiar_gui()
The MixSIAR GUI should then appear as a separate window

**Comment by ruyi638** [comment]
I have the same problems on loading mixsiar_gui function as you, have you solve this problem?

**Comment by brianstock-NOAA** [comment]
We had to split the GUI into its own package for MixSIAR to remain on CRAN. Please see the following:
https://github.com/brianstock/MixSIAR/issues/224
https://github.com/brianstock/MixSIARgui

We highly advise that you learn to use the script version, as then your analyses are reproducible. If you still want to try to get the GUI working, see:
https://github.com/brianstock/MixSIARgui/issues/1
