### ISSUE TITLE
How to access individual model runs and output a file?

### ISSUE THREAD

**Issue by AndrewS90** [brianstock/MixSIAR#63]
Hi MixSIAR users, I would like to access the individual model runs from which the summary statistics are derived and output as a file (I realise that can generate a large file).  Your advice appreciated - thanks Andrew.

**Comment by brianstock** [comment]
Hi Andrew,

Good question.  It's come up before, see #30.  In the context of aggregating sources a posteriori: #53.  Check those out and let me know if that doesn't work.

-Brian

**Comment by AndrewS90** [comment]
Hi Brian,

RE: [brianstock/MixSIAR] How to access individual model runs and output a file? (#63)

Thanks for your reply – I’ll let you know how I get on.

Best regards - Andrew

**Comment by AndrewS90** [comment]
Hi Brian,
FYI - I found that one extra line of code - "require(R2jags)" required before "attach.jags" line to access the posterior chains (isotope source proportions) data.  Thanks for help.

regards - Andrew

save.image(“yourfilename.RData”)  
require(R2jags)  
attach.jags(mixsiar$jags.1)
write.table(p.global,file="Filename.out",append=TRUE,sep= " ",na ="NA")
