### ISSUE TITLE
NAs or Zeros in the source data file

### ISSUE THREAD

**Issue by pablodlpa** [brianstock/MixSIAR#65]
Hello,

I´m analysing stable isotope signatures of d13C and d15N from a mixture (eg. predator) throught 2 different time periods and I would like to see the effect of a new source (eg. new prey available) on the predator´s diet. 

My question is: If I want to be able to compare between the 2 models from each period of time, do I have to include the new source signature values of d13C and d15N in the first model even if it wasn´t available for the predator at that time? And, if so, can I include it as "NAs" on the d13C and d15N values of that prey? Or should I consider it as 0s? Is the model able to cope with NAs or zeros in the data files?

I hope the question is clear enough.. I tried to search for this in the manual and the Rscript but I couldn´t find anything...

Thanks

P

**Comment by brianstock** [comment]
Hi Pablo,

In MixSIAR you'll have to run two separate mixing models with the different prey fields.  Don't use 0s - those are valid d13C and d15N values, so the model with run fine using them (not what you want!).  Not sure how it handles NAs (have you tried?).

Two ways to run an analysis with two different sets of available prey:
  1. (easier) Create two separate consumer and source data files, one for each time period
  2. Create two separate consumer files, one source file with all prey, then run models with a) uninformative prior (all sources available) and b) informative prior giving the non-available prey effectively 0 weight.

Hope that helps!

-Brian
