### ISSUE TITLE
What is the area of my source polygon and how do I know a consumer is outside of it?

### ISSUE THREAD

**Issue by Krustenechse** [brianstock/MixSIAR#68]
Hey,
I am still new to the field and I hope this is not a dumb question. I want to include a MixSIAR analysis into my master thesis, but even after searching and reading for a while I am still not sure about this issue.

So this is my problem: How do I know if a datapoint is outside of my source polygon? And how do I now the area of my source polygon? Can I extract it somehow?

I really want to avoid breaking one of the number one rules:
"If the mixture data are well outside the source polygon, you have a serious violation of mixing model assumptions, and it must be true that either 1) You're missing a source, or 2) You're using an incorrect discrimination factor."

So this is what one of my plots look like:

![bild1](https://cloud.githubusercontent.com/assets/18753574/14937660/dd9c5a62-0f0e-11e6-809e-7d8e0132a7f6.png)

The Tdf seems to be acceptable. But I probably miss two sources  (No samples available) that are mentioned in the literature (faeces analysis) . The first one contribute to the diet  <5% and the second to <1%.

The red circles are somehow  outside of my sources SD. 
But as I understand it: the SD of the Tdf  is added to the SD of the sources.
Is this visualized in the plot? Is their a possibility to check if my data is inside or ouside of the polygon?

I hope you can give me some advice,
Thanks 
Theresa

**Comment by ChrisHarrod** [comment]
It’s not a MixSiar thing, but you could try Smith, J.A., Mazumder, D., Suthers, I.M. & Taylor, M.D. (2013) To fit or not to fit: evaluating stable isotope mixing models using simulated mixing polygons. Methods in Ecology and Evolution, 4, 612-618.

Cheers
Chris


><> ><> ><> ><> ><> ><> ><> ><> ><> ><> ><> ><> ><> ><> ><> ><> ><>
Professor Chris Harrod
(Fish & Aquatic Ecology)
Email: chris@harrodlab.net
Twitter: @chris_harrod
www.harrodlab.net
HarrodLab: Fish and Stable Isotope Ecology Laboratory
Instituto de Ciencias Naturales Alexander von Humboldt,
Universidad de Antofagasta,
Avenida Angamos 601, Antofagasta, Chile
Chile Mobile: +56 9 7399 7792
Chile Office: +56 55 2637400
<>< <>< <>< <>< <>< <>< <>< <>< <>< <>< <>< <>< <>< <>< <>< <>< <><

**Comment by eric-ward** [comment]
The biggest situation where the distribution of the data and source polygon matter is where you have a couple data points from the consumer, and they're all outside the polygon. Based on your data, it's hard to say whether the missing sources / TEFs are a bigger issue. But remember that unless you're modeling variation between individuals or groups, you're really modeling how the sources related to the mean of your data points. Mixing models are very flexible, and can still fit these data -- variances of the mixture can be made up of (1) variances of the sources, (2) variances of the TEFs, and (3) additional residual variances. Allowing this additional component in MixSIAR will allow for a lot of flexibility.

**Comment by Krustenechse** [comment]
Thank you so much.

The paper and comment was really helpful. 

Cheers Theresa
