### ISSUE TITLE
unexpecte process output in wolves examples with longer MCMC run lenght

### ISSUE THREAD

**Issue by fitogil** [brianstock/MixSIAR#72]
I m a new MixSIAR user and tryin to folow the manual. Now I will look for the wolve examples. When I chanfg the MCMC run lenght and I go to process output  I not found the expected answer after 30 minute (i put it as normal):

  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100%
  |**************************************************| 100%
Error in array(x, c(length(x), 1L), if (!is.null(names(x))) list(names(x),  : 
  'data' must be of a vector type, was 'NULL'

**Comment by brianstock** [comment]
Sorry about the error... haven't seen that before.  Are you using the GUI or script version?

**Comment by fitogil** [comment]
Thank you Brian, I start again with wolve examples. I am using GUI. The first error is when start and try to make a isospace plot:

 

> library(MixSIAR)

> mixsiar_gui()

Loading required package: gWidgetsRGtk2

Loading required package: RGtk2

Loading required package: gWidgets

Loading required package: cairoDevice

Error in grid.Call.graphics(L_text, as.graphicsAnnot(x$label), x$x, x$y,  : 

  Metric information not available for this family/device

> The MixSIAR

 

 

 

De: Brian Stock [mailto:notifications@github.com] 
Enviado el: lunes, 06 de junio de 2016 06:44 p.m.
Para: brianstock/MixSIAR
CC: fitogil; Author
Asunto: Re: [brianstock/MixSIAR] unexpecte process output in wolves examples with longer MCMC run lenght (#72)

 

Sorry about the error... haven't seen that before. Are you using the GUI or script version?

**Comment by caijian89** [comment]
I m a new MixSIAR user and also faced the same errors when i processed ouput follow as the manual. But diffrently, I have not changed MCMC run length yet. Excepting the error codes shown as above,  a grey grahphic appeared after the Overall Population graph.

**Comment by brianstock** [comment]
Did you search for your error online?  It seems to be a computer/platform-specific issue with the delta and permil symbols in the isospace plot axes.  In the future, bug/error reports are more useful when you specify your OS and versions of installed software.

1. What OS are you running and what is the output of `sessionInfo()`?

2. Does the following reproduce your error?

```
# ggplot2 font issue (Github #72)
# Minimal working example

library(ggplot2)
df <- data.frame(x=1:10,y=1:10)
x_label <- expression(paste(delta^13, "C (\u2030)",sep=""))
ggplot2::ggplot(data=df, ggplot2::aes(x=x,y=y)) + 
ggplot2::geom_point() +
ggplot2::xlab(x_label)
```

**Comment by caijian89** [comment]
Thank you! I check the output of sessionInfo() , the details were pasted as below
`R version 3.3.0 (2016-05-03)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=Chinese (Simplified)_China.936  LC_CTYPE=Chinese (Simplified)_China.936   
[3] LC_MONETARY=Chinese (Simplified)_China.936 LC_NUMERIC=C                              
[5] LC_TIME=Chinese (Simplified)_China.936    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggplot2_2.1.0        gWidgetsRGtk2_0.0-83 cairoDevice_2.23     gWidgets_0.0-54      RGtk2_2.20.31       
[6] MixSIAR_3.1.0        devtools_1.11.1     

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.5         DEoptimR_1.0-4      RColorBrewer_1.1-2  git2r_0.15.0        plyr_1.8.3         
 [6] compositions_1.40-1 tools_3.3.0         testthat_1.0.2      boot_1.3-18         digest_0.6.9       
[11] jsonlite_0.9.19     memoise_1.0.0       gtable_0.2.0        lattice_0.20-33     curl_0.9.7         
[16] parallel_3.3.0      coda_0.18-1         withr_1.0.1         httr_1.1.0          knitr_1.13         
[21] rjags_4-6           R2jags_0.5-7        grid_3.3.0          robustbase_0.92-6   R6_2.1.2           
[26] bayesm_3.0-2        tensorA_0.36        magrittr_1.5        scales_0.4.0        R2WinBUGS_2.1-21   
[31] MASS_7.3-45         abind_1.4-3         colorspace_1.2-6    labeling_0.3        energy_1.6.2       
[36] munsell_0.4.3       crayon_1.3.1  `

Secondly, I run the code of your suggestion to test, there is no error with the delta and permil symbols in the plot axes. So I  repeated the manual method to analyse the wolves data, and same error reoccur.

Error in array(x, c(length(x), 1L), if (!is.null(names(x))) list(names(x),  : 
  'data' must be of a vector type, was 'NULL'

**Comment by brianstock** [comment]
That's a different error than before... When does this error occur?  Does the isospace plot come up correctly?

**Comment by caijian89** [comment]
Thanks for your kind reply
It happened after I pressed the output button， the isospace plot is absolutely similar with the graph of manual.

**Comment by brianstock** [comment]
If `library(RGtk2)` fails, then GTK+ is probably not installed where R can see it.  The first time you `install.packages(RGtk2)` (on Windows), an error will come up, but then a box should pop up asking if you want to install GTK+.  If you click ok and let it install, then restart R and try `library(RGtk2)`, I have never seen this not work.  Can't help much here... try deleting 'D:\Program Files\R\R-3.3.0\library\RGtk2\gtk\x64\etc\gtk-2.0'.

If the GUI has an error, how are you running the examples?

My guess is there is a mismatch between the options you're choosing in the MixSIAR functions and the data structure.  To test that ALL the examples work on your machine:

```
library(MixSIAR)

# find MixSIAR directory
mixsiar.dir <- find.package("MixSIAR")
# run all examples
source(paste0(mixsiar.dir,"/example_scripts/run_all_examples.R"))
```

**Comment by caijian89** [comment]
Thank you Brian！ I try to test ALL examples by your code，the error still occur，I traceback the R command and paste it as below:


> 12 array(x, c(length(x), 1L), if (!is.null(names(x))) list(names(x), 
    NULL) else NULL) 
11 as.matrix.default(p.fac1[, f1, src]) 
10 as.matrix(p.fac1[, f1, src]) 
9 output_JAGS(jags.1, mix, source, output_options) at mixsiar_script_wolves.R#170
8 eval(expr, envir, enclos) 
7 eval(ei, envir) 
6 withVisible(eval(ei, envir)) 
5 source(paste0(mixsiar.dir, "/example_scripts/mixsiar_script_wolves.R")) at run_all_examples.R#13
4 eval(expr, envir, enclos) 
3 eval(ei, envir) 
2 withVisible(eval(ei, envir)) 
1 source(paste0(mixsiar.dir, "/example_scripts/run_all_examples.R"))

**Comment by fitogil** [comment]
I have a similar error. I think my problem is with GTK+. I follow your isntruction:
install.packages(RGtk2)
Error in install.packages(RGtk2) : objeto 'RGtk2' no encontrado

I deleted the previous RGtk2 but never change and the box  you mention no appear.
Thank you in advance

**Comment by fitogil** [comment]
I continue exploring it. Now I run again. I can make a isospace and run model and plot prior. But when I ask by process output it appear:
Loading required package: gWidgetsRGtk2
Loading required package: gWidgets
Loading required package: cairoDevice
Error in grid.Call.graphics(L_text, as.graphicsAnnot(x$label), x$x, x$y,  : 
  Metric information not available for this family/device
module glm loaded
Compiling model graph
   Resolving undeclared variables
   Allocating nodes
Graph information:
   Observed stochastic nodes: 66
   Unobserved stochastic nodes: 63
   Total graph size: 9772

Initializing model


  |                                                        
  |                                                  |   0%
  |                                                        
  |++                                                |   4%
  |                                                        
  |++++                                              |   8%
  |                                                        
  |++++++                                            |  12%
  |                                                        
  |++++++++                                          |  16%
  |                                                        
  |++++++++++                                        |  20%
  |                                                        
  |++++++++++++                                      |  24%
  |                                                        
  |++++++++++++++                                    |  28%
  |                                                        
  |++++++++++++++++                                  |  32%
  |                                                        
  |++++++++++++++++++                                |  36%
  |                                                        
  |++++++++++++++++++++                              |  40%
  |                                                        
  |++++++++++++++++++++++                            |  44%
  |                                                        
  |++++++++++++++++++++++++                          |  48%
  |                                                        
  |++++++++++++++++++++++++++                        |  52%
  |                                                        
  |++++++++++++++++++++++++++++                      |  56%
  |                                                        
  |++++++++++++++++++++++++++++++                    |  60%
  |                                                        
  |++++++++++++++++++++++++++++++++                  |  64%
  |                                                        
  |++++++++++++++++++++++++++++++++++                |  68%
  |                                                        
  |++++++++++++++++++++++++++++++++++++              |  72%
  |                                                        
  |++++++++++++++++++++++++++++++++++++++            |  76%
  |                                                        
  |++++++++++++++++++++++++++++++++++++++++          |  80%
  |                                                        
  |++++++++++++++++++++++++++++++++++++++++++        |  84%
  |                                                        
  |++++++++++++++++++++++++++++++++++++++++++++      |  88%
  |                                                        
  |++++++++++++++++++++++++++++++++++++++++++++++    |  92%
  |                                                        
  |++++++++++++++++++++++++++++++++++++++++++++++++  |  96%
  |                                                        
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100%

  |                                                        
  |                                                  |   0%
  |                                                        
  |**                                                |   4%
  |                                                        
  |****                                              |   8%
  |                                                        
  |******                                            |  12%
  |                                                        
  |********                                          |  16%
  |                                                        
  |**********                                        |  20%
  |                                                        
  |************                                      |  24%
  |                                                        
  |**************                                    |  28%
  |                                                        
  |****************                                  |  32%
  |                                                        
  |******************                                |  36%
  |                                                        
  |********************                              |  40%
  |                                                        
  |**********************                            |  44%
  |                                                        
  |************************                          |  48%
  |                                                        
  |**************************                        |  52%
  |                                                        
  |****************************                      |  56%
  |                                                        
  |******************************                    |  60%
  |                                                        
  |********************************                  |  64%
  |                                                        
  |**********************************                |  68%
  |                                                        
  |************************************              |  72%
  |                                                        
  |**************************************            |  76%
  |                                                        
  |****************************************          |  80%
  |                                                        
  |******************************************        |  84%
  |                                                        
  |********************************************      |  88%
  |                                                        
  |**********************************************    |  92%
  |                                                        
  |************************************************  |  96%
  |                                                        
  |**************************************************| 100%
Error in array(x, c(length(x), 1L), if (!is.null(names(x))) list(names(x),  : 
  'data' must be of a vector type, was 'NULL'
> The MixSIAR

**Comment by brianstock** [comment]
@fitogil @caijian89 Big thank you for posting here, and I'm sorry for being slow to see this as a bug. When I run the Wolves script example, I also get the same error on my machine:

```
Error in array(x, c(length(x), 1L), if (!is.null(names(x))) list(names(x), :
'data' must be of a vector type, was 'NULL'
```

I'm working on a fix and hope to post a new version soon!

**Comment by brianstock** [comment]
Fixed and tagged a [new release](https://github.com/brianstock/MixSIAR/releases/tag/3.1.5). Update via:

```
library(devtools)
devtools::install_github("brianstock/MixSIAR@*release", # gets latest release
                         dependencies = TRUE, 
                         build_vignettes = TRUE)
```

Check that all examples run successfully:
```
library(MixSIAR)
mixsiar.dir <- find.package("MixSIAR")
source(paste0(mixsiar.dir,"/example_scripts/run_all_examples.R"))
```
