### ISSUE TITLE
error loading source file(s) of examples

### ISSUE THREAD

**Issue by marknovak** [brianstock/MixSIAR#75]
I run into problems similar to the following in attempting to load the 'source' files of all the given examples....

Here's the error for the 'wolves' data set:

`Error in load_source_data(filename = source.filename, source_factors = "Region",  : 
  *** Error: Source sample sizes missing or entered incorrectly.
        Check your source_means.csv data file to be sure you have a column
        titled "n" with the sample sizes for each source isotope estimate.
In addition: Warning message:
In load_source_data(filename = source.filename, source_factors = "Region",  :
  NAs introduced by coercion`

Here's the error for the 'palmyra' data set:

`Error in `colnames<-`(`*tmp*`, value = c("d13C", "d15N")) : 
  attempt to set 'colnames' on an object with less than two dimensions
In addition: Warning message:
In load_source_data(filename = source.filename, source_factors = NULL,  :
  NAs introduced by coercion`

**Comment by brianstock** [comment]
Hi Mark,

Sorry, I can't replicate your error on Linux, Mac, or Windows machines here...

What OS are you on?  What versions of R and MixSIAR do you have installed?  What is the output of `sessionInfo()`?  First thing I'd try is to make sure your R, MixSIAR, and packages are all the latest versions (R 3.3.1, MixSIAR from CRAN is 3.1.6).

**Comment by marknovak** [comment]
Thanks for the quick response.  Here's the session info.  I'll try on a different machine as well and will report back.

> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.5 (Yosemite)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] MixSIAR_3.1.6

loaded via a namespace (and not attached):
[1] DEoptimR_1.0-6      tools_3.3.1         bayesm_3.0-2        Rcpp_0.12.5         robustbase_0.92-6  
[6] energy_1.6.2        tensorA_0.36        boot_1.3-18         compositions_1.40-1

**Comment by marknovak** [comment]
You may not like the implication of this....
I tried it on a different Mac (after updating it's version of R and reinstalling MixSIAR with all dependencies) and the error did NOT occur!
I did not, however, update to the most recent version of R as used above (i.e. v3.3.1), choosing instead to install v3.2.3 as indicated in the MixSIAR documentation.
It also worked on the original machine after deleting v3.3.1 and reverting to v3.2.3.

So "issue resolved" from my perspective.  Good luck figuring out what got changed between versions!

(Incidentally, there was still a different error on both machines caused by package "splancs" not being automatically installed.  Happy to post this as a different issue if you'd like.)

**Comment by marknovak** [comment]
```
Error in calc_area(source = source, mix = mix, discr = discr) : 
  *** Error: 'splancs' package not installed. 'splancs' is
        required to run the 'calc_area' function. Install 'splancs' by
        entering 'install.packages('splancs')' in the R console. ***
In addition: Warning messages:
1: In cairo_pdf(filename = mypath, width = 7, height = 7) :
  unable to load shared object '/Library/Frameworks/R.framework/Resources/library/grDevices/libs//cairo.so':
  dlopen(/Library/Frameworks/R.framework/Resources/library/grDevices/libs//cairo.so, 6): Library not loaded: /opt/X11/lib/libXrender.1.dylib
  Referenced from: /Library/Frameworks/R.framework/Resources/library/grDevices/libs//cairo.so
  Reason: image not found
2: In cairo_pdf(filename = mypath, width = 7, height = 7) :
  failed to load cairo DLL
```

**Comment by brianstock** [comment]
Hmm, that is strange that it worked with R 3.2.3 and not 3.3.1... In submitting to CRAN I tested on R-devel, which will become 3.4.0. I didn't have these errors using any of these versions.  Thank you for reporting!

Yeah, `spancs` is only necessary to use the optional `calc_area` function.  I made it a suggested package--like the GUI-related ones--to keep the script version of MixSIAR less dependent on other code.  Should install with `dependencies=TRUE`... unless it's due to that `cairo`-related error. On Mac, sometimes you need to install the latest X11 application, xQuartz: https://www.xquartz.org/.

As an aside, if you comment out the `calc_area` call, and in the `plot_data` function change to `plot_save_pdf=FALSE`, those errors shouldn't come up.

**Comment by SoniaGasmi** [comment]
Hi guys, 
I am trying to apply the MixSIAR example for wolves. I have problem plotting the isospace. 
Here is the error message I get: 
"> plot_data(filename="isospace_plot", plot_save_pdf=TRUE, plot_save_png=FALSE, mix,source,discr)
Warning message:
In cairo_pdf(filename = mypath, width = 7, height = 7) :
  failed to load cairo DLL"

I tried different solutions found on the internet but nothing really works. 
I have the last R version 3.5.1. 

Thanks for your help!
