### ISSUE TITLE
One mix datapoint, process error only (MixSIR)

### ISSUE THREAD

**Issue by Pactzar** [brianstock/MixSIAR#76]
Hi, I´m working with samples for which I only have 1 datapoint. In the manual you say I should use the original MixSIR error model that behaves as "siarsolo" in SIAR. Where can I find this error model and how do I introduce it when writing the JAGS model?
Thanks a lot!             Darío

**Comment by eric-ward** [comment]
I think if you're using SIAR, the function is actually 'siarsolomcmc' . The error model with a single data point is the MixSIR model described by Moore & Semmens (2008) -- error is additive, and not estimated as an additional parameter (rather it's derived from the mixture proportions and source variances). 

The easiest way to get the files would be to implement the model in MixSIAR. I'm also attaching a version of the code from a workshop we did at Trinity College in 2011. 
[MixSIR.txt](https://github.com/brianstock/MixSIAR/files/376915/MixSIR.txt)

Link to full workshop materials here:
http://conserver.iugo-cafe.org/user/brice.semmens/Trinity%20Stable%20Isotope%20Mixing%20Model%20Lab%20Files

**Comment by Pactzar** [comment]
Thanks Eric. I´ll take a look. I´m working with MixSIAR.

**Comment by Pactzar** [comment]
Is there any script example where it uses this function in MixSIAR?
How do I implement the model in MIxSiAR?

**Comment by brianstock** [comment]
In the GUI, error option is in the top right. Choose "process only (N=1)":
![mixsiar_resid_error](https://cloud.githubusercontent.com/assets/5124211/17043906/0175a9b0-4f70-11e6-8c60-8e29087df62d.png)
This is used in the Cladocera example, p.46 in the manual.

For a script version example, see the Cladocera vignette. Unfortunately, there is a mistake in the section where I specify the error option (wouldn't have found it without your question - thank you!)... You want to specify `resid_err <- FALSE` and `process_err <- TRUE`.
```
# Write the JAGS model file
model_filename <- "MixSIAR_model.txt"
resid_err <- FALSE
process_err <- TRUE
write_JAGS_model(model_filename, resid_err, process_err, mix, source)
```

**Comment by Pactzar** [comment]
Thanks!
All of you are doing a great job with MixSIAR and responding to all of our questions.
