### ISSUE TITLE
Problem with wolf vignette?

### ISSUE THREAD

**Issue by groemer** [brianstock/MixSIAR#77]
Hello,

Q1: I've been playing the wolf vignette using the provided data and substituting my own and in each case I get the following error after the output_JAGS function is implemented:

output_JAGS(jags.1, mix, source, output_options)
Error in array(x, c(length(x), 1L), if (!is.null(names(x))) list(names(x),  : 
  'data' must be of a vector type, was 'NULL'

It seems it is not finishing all of the plots, as it quits and some of the plots are blank, etc.

Q2: I then explored the number of items within the object and was curious if this was a complete list:

> names(jags.1)
[1] "model"              "BUGSoutput"         "parameters.to.save"
[4] "model.file"         "n.iter"             "DIC"  

Q3: Finally, in the description of the output_JAGS function, shown below, there are a number of summary files created that are supposed to be stored in the working directory, but, and I apologize ahead of time, I cannot find these files whether by going to my working directory or by searching for the filenames.  Could the error above have stopped the function and prevented the files from being created? Any advice would be most appreciated.

Description

output_JAGS processes the mixing model output, prints and saves (in the working directory):

diagnostics

summary statistics

posterior density plots

pairs plot

trace/XY plots

**Comment by brianstock** [comment]
1. What version of MixSIAR are you using?  I've seen that error before and had to fix it (https://github.com/brianstock/MixSIAR/issues/72).

If you aren't using the latest version from CRAN, reinstall, reload, and try running the wolves ex again:
```
install.packages("MixSIAR", dependencies=TRUE)
library(MixSIAR)
mixsiar.dir <- find.package("MixSIAR")
source(paste0(mixsiar.dir,"/example_scripts/mixsiar_script_wolves.R"))
```

2. Yes

3. Yes, that's probably what happened.

**Comment by groemer** [comment]
Thanks Brian!

It worked.

I was running 3.1.0 or 3.1.2 - I installed your newest version before looking, but that is what I remember. I certainly wasn’t running 3.1.6.

Thanks so much for getting back in touch so quickly.

Best,

Gary

Dr. Gary Roemer, Professor
Dept. Fish, Wildlife & Conservation Ecology
New Mexico State University
Las Cruces, NM 88003
Off: 575-646-3394
groemer@nmsu.edu
http://web.nmsu.edu/~groemer/

**Comment by groemer** [comment]
Hey Brian,

Is there anyway to access the posterior probability distributions for the dietary proportions?

Thanks,

Gary

PS: I can post to Github if you like.

Dr. Gary Roemer, Professor
Dept. Fish, Wildlife & Conservation Ecology
New Mexico State University
Las Cruces, NM 88003
Off: 575-646-3394
groemer@nmsu.edu
http://web.nmsu.edu/~groemer/

**Comment by brianstock** [comment]
Great!  Yes, see https://github.com/brianstock/MixSIAR/issues/30, https://github.com/brianstock/MixSIAR/issues/66, https://github.com/brianstock/MixSIAR/issues/53, and https://github.com/brianstock/MixSIAR/issues/21.

**Comment by groemer** [comment]
Thanks Brian! And my apologies for not being more astute.

Best,

Gary

Dr. Gary Roemer, Professor
Dept. Fish, Wildlife & Conservation Ecology
New Mexico State University
Las Cruces, NM 88003
Off: 575-646-3394
groemer@nmsu.edu
http://web.nmsu.edu/~groemer/
