### ISSUE TITLE
Informative priors and correlated tracers

### ISSUE THREAD

**Issue by alex-koiter** [brianstock/MixSIAR#79]
Hi Brian,
I have two questions I was hoping you could shed some light on.
1) Can you only set the informative prior at the global level? For example, in the wolves example how might you incorporate prior information on the diet of individual packs or regions (e.g.,, Pack 1 consumed ~20% salmon and ~80% deer, Pack 2 consumed ~30% salmon and ~70%  and so on). I have a situation where I know the availability of a source is limited in some regions and abundant in other region
2) Is there a way, or is it even important to, include information on the correlation between different tracers?

Thanks,
Alex

**Comment by brianstock** [comment]
Hi Alex,

Good questions!

1) In theory, no.  In current MixSIAR code, yes.  You can modify the existing code to add different priors on p.fac1.  Or you could run separate mixing models for each region and include a prior on p.global.  The main downside to that, apart from having to separate your input files and MixSIAR calls, is the source means/vars are then fit differently in each independent model.

2) The current MixSIAR code fits the mix data as multivariate normal with covariance---in the cases where this is possible.  The error structure paper, preprint at http://onlinelibrary.wiley.com/doi/10.1002/ecy.1517/full, doesn't explain this but did use the multivariate code.  The MixSIAR manuscript (in review) goes into it, stay tuned. For now, the details are in `write_JAGS_model.R`:

MixSIAR fits mix data WITHOUT covariance when there's no information on it:
  - Process error (MixSIR, N = 1 data point), which assumes a variance of the mix data based on the variances of the sources, lines 746-766
  - Only 1 tracer... obviously no covariance, lines 732-741
  - Process*resid error, and no covariance in source data (means+SD, no raw data), lines 618-662

MixSIAR DOES fit mix data with covariance in these cases:
  - Resid only error and > 1 tracer (inverse Wishart prior), lines 718-728
  - Process*resid error and > 1 tracer, covariance in source data (raw data), lines 667-705

**Comment by jamiemcaulay** [comment]
Hi all, 
Wondering if anyone has attempted the suggestion above "modify the existing code to add different priors on p.fac1" to use different priors for different levels of a factor in MIXSIAR. 
Many thanks, 
Jamie

**Comment by brianstock** [comment]
Hi, an updated thought... I'm not sure this is possible with the way MixSIAR is structured. We can set an informative Dirichlet prior on the global p's easily because they are in proportion-space. However, these p's are then transformed to ILR-space, and the fixed/random effects are additive offsets in ILR-space, and the combined ILRs are back transformed to p's later. I don't know how you'd set an appropriate informative prior in ILR space.

**Comment by jamiemcaulay** [comment]
Hi, 
Thanks very much for your reply and thoughts - much appreciated. 
Jamie
