### ISSUE TITLE
Why the unknownGroups.R. function does not require a matrix of isotope fractionation values for each of the sources used in the mixing model?

### ISSUE THREAD

**Issue by pablojorgensen** [brianstock/MixSIAR#93]
I have an undetermined stable isotope (SI) trophic model with 2 tracers and 5 sources for a consumer (mix). To address this undetermined model I applied the mixSIR.unknownGroupsR function (http://conserver.iugo-cafe.org/user/eric.ward/Mixing%20model%20with%20unknown%20groups) to combine sources into groups and estimate the proportional contributions of the resultant grouped sources to the consumer (Ward EJ, Semmens BX, Phillips DL, et al (2011) Ecosphere 2:art19. doi: 10.1890/ES10-00190.1). Among the input data required by the R function are: a matrix with the consumer SI data (X); a matrix of raw source SI means (u); a matrix of raw SI source variances (v); and a matrix of sample sizes (k). However, the unknownGroups.R. function does not require the input of a matrix of means (and variances) isotope fractionation values (i.e. trophic fractionation or discrimination) for each of the sources used in the model, as usual in other mixing models (e.g.: mixSIR, SIAR, MixSIAR, FRUITS).

**Comment by eric-ward** [comment]
Hi Pablo, the matrix of means and variances you pass in should include the TEF corrections (which you'll need to do prior to being passed in)

**Comment by pablojorgensen** [comment]
Ok, thanks for the reply. Pablo
