### ISSUE TITLE
Error reading in CSV data files (`read.table` incomplete final line)

### ISSUE THREAD

**Issue by ccatherines** [brianstock/MixSIAR#94]
I am setting up a simple model with 1 biotracer (d15N), no factors, and 3 sources.  I can load the consumer data, but when I try to load mean source data (Meand15N, SDd15N, n) and discrimination data (Meand15N, SDd15N) I get the following error message:

Warning message:
In read.table(file = file, header = header, sep = sep, quote = quote,  :
  incomplete final line found by readTableHeader on 'discrimination.csv'

I have solved this for the source data by just loading the raw data (d15N) for each source.  However I cannot load discrimination data.  Is this a bug or am I doing something wrong?  Thanks!

**Comment by ccatherines** [comment]
And of course I am "eliminating" one of the sources.  However even if I try to load data with just 2 sources I get the same error message.

**Comment by brianstock** [comment]
Hi Catherine,

Sorry... Hard to tell without seeing your data files, but I'd guess there's
a problem with how you're loading the data, or the data themselves (e.g. SD
=0 or some such). If you want, you can email them to b1stock@ucsd.edu, or
post here. Changing the numbers is fine, just preserve the structure and
file names. Sending the .R script you're trying to run would be helpful too.

-Brian

**Comment by ccatherines** [comment]
Hi, thanks.  Turns out I may have found a workaround.  If I type in the discrimination data separated by commas, then save it as a .txt file, that will load with the new filename "discrimination_text.txt".  If I try to re-save as a .csv file, "discrimination.csv", that will not work and I get the old error message.  I'm working on a mac with the latest R version 3.3.2.  I will send you the data in case this is something you are still interested in, meanwhile will use my workaround.  Thanks!

**Comment by brianstock** [comment]
Could also try opening your source and discrimination data in Excel and manually deleting rows (not below your data (not just contents of the cells, the entire rows). I've seen that throw off R reading in CSV files before.

**Comment by ccatherines** [comment]
Thanks! I will try that. So far by making a .txt file using commas for the discrimination data that seems to work too.
