### ISSUE TITLE
Different numbers of sources for each factor level

### ISSUE THREAD

**Issue by andrewcparnell** [brianstock/MixSIAR#95]
When users try to input a source.csv file which has different numbers of sources for different levels of the factor the error message is quite unhelpful - it says that they haven't included an n column containing the sample sizes, but usually they have.

Could you make the error message more informative in this case to remind people that they cannot have differing numbers of sources for each factor level?

Thanks.

**Comment by brianstock** [comment]
Ah, yes I can see that being frustrating... Please extend my condolences to anyone who pulled their hair out over this!  On the to-do list.

**Comment by brianstock** [comment]
Hi @andrewcparnell,

Just added a check and error message for this, see 2d04bcd4468dda3d78283e1c1eb9a82f094ae98a. I'll make further changes before updating the version no. and CRAN, but for now you can direct users to download the current Github code.
