### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by alex-koiter** [brianstock/MixSIAR#96]
Just to be clear, to cite the use of the MixSIAR package you would like us to use:
 B.C. Stock and B.X. Semmens (2013). MixSIAR GUI User Manual. Version 3.1. https://github.com/brianstock/MixSIAR.<doi:10.5281/zenodo.56159>. 

I just find the year a bit odd since version 3.1 was released in 2016.
Just want to make sure I have it right.
Thanks,

**Comment by brianstock** [comment]
Hi Alex,

Thank you for clarifying!  Yes, that is odd... We will change that from 2013 to 2016.  We were trying to keep a stable citation without having an associated "MixSIAR paper" (unfortunately still in progress).

**Comment by alex-koiter** [comment]
Thanks for the response.
